extends Gram
## Deutsch. Ein Dorf aus den Märchen: Hänsel und Gretel, ein Mädchen mit roter Kappe,
## der Wolf Isegrim, der Fuchs Reineke, Till mit der Narrenkappe, der Struwwelpeter.
## Das Ungeheuer heißt hier Werwolf. Namen werden nicht dekliniert, {who.pos} gibt „Gretels".


func code() -> String:
	return "de"


func name_case(name: String, case: String, _female: bool) -> String:
	if case == "pos":
		return name + ("'" if name.right(1) in ["s", "ß", "x", "z"] else "s")
	return name


func data() -> Dictionary:
	return {
		"and": " und ",
		"you": {"nom": "du", "acc": "dich", "gen": "dich", "dat": "dir", "ins": "dir", "pos": "deine"},
		"you_name": "Du",
		"someone": {"nom": "jemand anderes", "acc": "jemand anderen", "gen": "jemand anderem", "dat": "jemand anderem", "pos": "jemandes"},
		## nom — Schild und Listen; in — wo („in der Scheune"); to — wohin („in die Scheune");
		## of — bei („bei der Scheune"); gen — „die Tür der Scheune".
		"houses": [
			{"nom": "Haus am Fluss", "in": "im Haus am Fluss", "to": "ins Haus am Fluss", "of": "beim Haus am Fluss", "gen": "des Hauses am Fluss"},
			{"nom": "Scheune", "f": true, "in": "in der Scheune", "to": "in die Scheune", "of": "bei der Scheune", "gen": "der Scheune"},
			{"nom": "Kapelle", "f": true, "in": "in der Kapelle", "to": "in die Kapelle", "of": "bei der Kapelle", "gen": "der Kapelle"},
			{"nom": "Keller", "in": "im Keller", "to": "in den Keller", "of": "beim Keller", "gen": "des Kellers"},
			{"nom": "Garage", "f": true, "in": "in der Garage", "to": "in die Garage", "of": "bei der Garage", "gen": "der Garage"},
		],
		"names": [
			["Gretel", true], ["Hänsel", false], ["Lotte", true], ["Till", false], ["Heidi", true], ["Peter", false],
			["Otto", false], ["Liesel", true], ["Isegrim", false], ["Frieda", true], ["Reineke", false], ["Berta", true],
		],
		"looks": "res://config/looks_de.tres",
		"ph.ANNOUNCE": [
			"Ich bin heute Nacht {house.in}.",
			"Ich gehe {house.to}. Wer kommt mit?",
			"Ich schlafe {house.in}, falls jemand fragt.",
			"{house.nom}. Abgemacht.",
		],
		"ph.ACCUSE_STRONG": [
			"{who}, erklär mal, wie du den Morgen erlebt hast.",
			"Für mich ist alles klar. {who}.",
			"{who} war direkt daneben, als es passiert ist. Zufall?",
			"Ich stimme für {who}. Ohne Wenn und Aber.",
		],
		"ph.ACCUSE_STREET": [
			"{who} war die ganze Nacht draußen und ist zurückgekommen. Das schafft kein Mensch.",
			"{who}, du warst die ganze Nacht draußen. Willst du nichts sagen?",
		],
		"ph.ACCUSE_LIAR": [
			"{who} hat von {house.nom} geredet und woanders geschlafen. Warum lügen?",
			"{who}, du wolltest doch woandershin. Was hat sich geändert?",
		],
		"ph.DEFEND": [
			"Ja, ich war da. Na und?",
			"Ich bin kein Werwolf. Prüft mich heute Nacht.",
			"Ich hatte einfach Pech mit dem Zimmer.",
			"Werft mich jetzt raus, und morgen fehlen euch noch zwei.",
		],
		"ph.UPYR_DEFLECT": [
			"An eurer Stelle würde ich auf {who} achten.",
			"Ihr streitet, und gleich wird es Nacht.",
			"Nicht so hastig. Wenn wir uns irren, verlieren wir einen von uns.",
			"{who}, warum schweigst du die ganze Zeit?",
			"Ich war gestern still und habe überlebt. Also habe ich alles richtig gemacht.",
		],
		"ph.FILLER": [
			"Wir werden immer weniger. Zählt selbst.",
			"Entscheiden wir schneller, es wird dunkel.",
			"Ich traue niemandem. Gar niemandem.",
			"Einer von euch lügt gerade.",
		],
		"ph.REPLY_TO_ACCUSED_HUMAN": [
			"Ich? Im Ernst? Schau lieber {who} an.",
			"Du verwechselst mich.",
			"Gut. Werft mich raus. Morgen versteht ihr es.",
		],
		"ph.REPLY_TO_ACCUSED_UPYR": [
			"Witzig. Reden wir lieber über dich.",
			"So versenkt man die eigenen Leute. Praktisch.",
			"Du hast es auffällig eilig, mich loszuwerden.",
		],
		"ph.AGREE_ACCUSE": [
			"Stimmt. {who} gefällt mir auch nicht.",
			"Bin dabei. {who}.",
		],
		"ph.DISAGREE_ACCUSE": [
			"Nee, {who} ist doch in Ordnung. Was hast du?",
			"Schwach. Wo sind die Beweise?",
		],
		"ph.INVITE_YES": [
			"Gut. Wir treffen uns {house.of}.",
			"Na schön, ich gehe mit dir {house.to}.",
			"Einverstanden. Lass mich nur nicht hängen.",
		],
		"ph.INVITE_NO": [
			"Nein, mit dir gehe ich nicht. Nichts für ungut.",
			"Dir traue ich noch nicht.",
			"Ich habe schon jemanden.",
		],
		"ph.ASK_ANSWER_HUMAN": [
			"Ich bin {house.in}. Kein Geheimnis.",
			"Hab ich doch gesagt: {house.nom}.",
		],
		"ph.ASK_ANSWER_UNSURE": [
			"Noch nicht entschieden.",
			"Ich schaue, wer wohin geht.",
		],
		"ph.PLAYER_DEFEND_REACTION": [
			"Ja, ja.",
			"Mal sehen.",
			"Das sagen alle.",
			"Gut, ich glaube dir. Vorerst.",
		],
		"ph.GENERIC_REACTION": [
			"Und was willst du damit sagen?",
			"Glatt. Zu glatt.",
			"Erzählst du das dir selbst oder uns?",
			"Gehört. Überzeugt mich nicht.",
		],
		"ph.AT_PLAYER": [
			"Ausgerechnet an dich habe ich die meisten Fragen.",
			"Du bist viel zu ruhig.",
			"Du verheimlichst etwas.",
			"Schau lieber dich selbst an.",
			"Dir traue ich nicht. Kein bisschen.",
		],
		"ph.PLEA_AFTER_STREET": [
			"Gestern haben sie mich schon nicht reingelassen. Ein zweites Mal überlebe ich nicht.",
			"Ich habe die ganze Nacht draußen gesessen. Mach auf.",
		],
		"ph.PLEA_SUSPECT": [
			"Ich weiß, wie es aussieht. Aber ich bin kein Werwolf.",
			"Glaub mir ein Mal. Danach kannst du mich rauswerfen.",
		],
		"ph.PLEA_NORMAL": [
			"Mach auf, hier ist es kalt.",
			"Ich bin's. Lass mich rein.",
			"Zu zweit schaffen wir es bis zum Morgen.",
			"Beeil dich, da draußen läuft jemand herum.",
		],
		"ph.PLEA_PACT": [
			"Ich bin's, wir hatten eine Abmachung.",
			"Mach auf, wie verabredet.",
		],
		"ph.JOB_FAKE": [
			"{who} stand {place} herum, und nichts ist dabei herausgekommen.",
			"Ich habe gesehen, wie {who} {place} herumgewerkelt und nichts geschafft hat.",
			"Seltsam. {who} war {place}, aber die Vorräte sind nicht mehr geworden.",
			"{who} tut nur so, als würde {who:er|sie} arbeiten. War {place}: nichts.",
			"Was hat {who} {place} gemacht? Die Eimer sind so leer wie vorher.",
		],
		"ph.JOB_FAKE_AT_PLAYER": [
			"Du vertrödelst {place} nur Zeit. Die Vorräte sind nicht mehr geworden.",
			"Du tust {place} nur so, als würdest du arbeiten. Ich habe es gesehen.",
			"Was bringst du {place}? Die Eimer sind immer noch leer.",
		],
		"ph.MIMIC_PLEAS": [
			"Lass mich rein. Ich bin's. Ich bin's, {who}. Lass mich rein.",
			"Mach auf, bitte. Bitte. Es ist kalt. Kalt.",
			"Du kennst mich doch. Mach die Tür auf. Mach die Tür auf.",
			"Ich bin nach Hause gekommen. Lass mich nach Hause.",
		],
		"ph.SABOTAGE_SEEN": [
			"{who} hat sich {place} herumgetrieben, und jetzt ist dort alles kaputt.",
			"Ich habe gesehen, wie {who} {place} etwas gemacht hat. Das war {who:er|sie}.",
			"Wer verdirbt unsere Vorräte? {who} war als {who:Letzter|Letzte} {place}.",
		],
		"ph.SABOTAGE_SEEN_AT_PLAYER": [
			"Was machst du da {place}? Ich habe es gesehen: nach dir ist alles kaputt.",
			"Nach dir ist {place} alles kaputt. Ich habe es gesehen.",
		],
		"ph.ELDER_UPYR": [
			"Ich bin [der Älteste|die Älteste]. Ich habe die Zeichnungen gelesen: {who} ist ein Werwolf.",
			"Hört zu. Ich bin [der Älteste|die Älteste], und auf den Zeichnungen ist {who} kein Mensch.",
		],
		"ph.ELDER_HUMAN": [
			"Ich bin [der Älteste|die Älteste]. {who} ist ein Mensch, ich habe nachgesehen.",
			"Laut den Zeichnungen ist {who} sauber. Ich bin [der Älteste|die Älteste], mir könnt ihr glauben.",
		],
		"ph.MEETING_CALL": [
			"Schluss mit Reden. Wir stimmen jetzt ab: {who}.",
			"Ich läute die Glocke. {who} lügt, wir entscheiden vor der Dunkelheit.",
			"Versammlung. Ich schlafe nicht neben {who}.",
		],
		"ph.BOX_NOTE": [
			"In der Kiste ist ein Zettel: „{a} oder {b}\". Einer von beiden ist ein Werwolf.",
			"Ich habe die Kiste geöffnet. Darin ein Zettel: „{a} oder {b}. Einer von beiden ist kein Mensch.\"",
		],
		"ph.BOX_OIL": [
			"In der Kiste ist Lampenöl. Heute Nacht wird es heller.",
			"Ich habe die Kiste geöffnet: Öl. Wir füllen die Lampen auf.",
		],
		"ph.BOX_CHALK": [
			"In der Kiste ist Kreide. Ich habe das Bannzeichen {house.of} nachgezogen.",
		],
		"plea.shared.label": "Wir haben schon zusammen übernachtet",
		"plea.shared.text": "Wir haben doch schon zusammen übernachtet, und nichts ist passiert.",
		"plea.promise.label": "Versprechen, morgen aufzumachen",
		"plea.promise.text": "Lass mich rein. Morgen mache ich dir als Erstes auf.",
		"plea.name.label": "Den Werwolf nennen",
		"plea.name.text": "Ich weiß, wer es ist. Lass mich rein, dann sage ich es dir.",
		"plea.beg.label": "Einfach betteln",
		"plea.beg.text": "Bitte. Hier draußen überlebt man nicht.",
		"spoil.water": "die Eimer sind umgekippt",
		"spoil.wood": "das Holz liegt im Dreck verstreut",
		"spoil.lamp": "das Öl ist ausgelaufen",
		"spoil.fish": "der Fang ist zurück in den Fluss geworfen",
		"spoil.any": "alles ist kaputt",
		"quick.house": "Ich schlafe {house.in}. Wer kommt mit?",
		"quick": ["Ich bin kein Werwolf. Ich schwöre.", "Wer von draußen zurückkommt, ist der Werwolf.", "Bleiben wir paarweise zusammen.", "Wer über seinen Schlafplatz lügt, fliegt raus."],
		"intent.accuse": ["werwolf", "wolf", "er war", "sie war", "lügt", "lügner", "verdächtig", "traue nicht", "raus", "mörder", "schuldig"],
		"intent.invite": ["komm mit", "mit mir", "zusammen", "gehen wir", "lass uns", "bei mir"],
		"intent.defend": ["nicht ich", "ich bin kein", "mensch", "schwöre", "unschuldig", "glaubt mir"],
		"intent.ask": ["wo ", "wohin", "welches haus"],
		"intent.houses": ["fluss", "scheune", "kapelle", "keller", "garage"],
		"ev.street": "kam lebend von draußen zurück",
		"ev.times": " ({n}-mal)",
		"ev.liar": "hat gelogen, wo {who:er|sie|du} schläft",
		"ev.death": "war in der Nähe, als jemand starb",
		"ev.fake": "hat umsonst gearbeitet",
		"ev.sabotage": "war bei einer verdorbenen Arbeit",
		"ev.tunnel": "kroch durch den Tunnel in ein fremdes Haus",
		"ev.sep": "; ",
		"sys.sabotage": "Jemand hat {place} Unfug getrieben: {what}. Die Vorräte sind geschrumpft.",
		"claim.elder_upyr": "nannte sich {me:der Älteste|die Älteste}: {who} ist ein Werwolf",
		"claim.elder_human": "nannte sich {me:der Älteste|die Älteste}: {who} ist ein Mensch",
		"claim.healer": "{role}: hat {who} in Nacht {n} gerettet",
		"when.night": "Nacht {n}",
		"when.day": "Tag {n}",
		"chron.line": "{title}: {text}",
		"chron.morning": "Morgens: {text}",
		"log.exiled": "das Dorf verbannte {who}.",
		"log.supplies": "Vorräte gesammelt: {p}%.",
		"log.tunnel": "{who.cap} {who:wurde|wurde|wurdest} {from.of} abgewiesen und {who:kroch|kroch|krochst} durch den Tunnel {house.to}.",
		"log.street_upyr": "{who.cap} {who:wurde|wurde|wurdest} {house.of} abgewiesen, {who:hat|hat|hast} aber bis zum Morgen überlebt.",
		"log.street_dead": "{who.cap} {who:wurde|wurde|wurdest} {house.of} abgewiesen. {who:Am Morgen fand man ihn auf der Straße.|Am Morgen fand man sie auf der Straße.|Du bist draußen gestorben.}",
		"log.street_ok": "{who.cap} {who:hat|hat|hast} die Nacht draußen verbracht und überlebt.",
		"log.mimic_knock": "an der Tür {house.gen} klopfte jemand mit {voice.pos} Stimme. Niemand machte auf.",
		"log.mimic_spared": "{house.in} ließ man {voice.pos} Stimme herein. Es war nicht {voice}, aber alle überlebten bis zum Morgen.",
		"log.mimic_kill": "{house.in} ließ man {voice.pos} Stimme herein. Es war der Nachahmer: er holte {who}.",
		"log.alone_dead": "{who.cap} {who:war|war|warst} allein {house.in}. Das Bannzeichen erlosch.",
		"log.killed": "{who.cap} {who:starb|starb|starbst} {house.in}. In der Nähe: {others}.",
		"log.clean": "{house.in} schliefen {list}. Alle sind heil.",
		"log.creature": "das Bannzeichen {house.gen} war gebrochen. Das Ding aus dem Wald holte {who}.",
		"log.liar": "{who.cap} {who:sprach|sprach|sprachst} von {said}, {who:schlief|schlief|schliefst} aber {house.in}.",
		"log.talisman_cracked": "das Bannzeichen {house.gen} bekam einen Riss.",
		"log.talisman_broken": "das Bannzeichen {house.gen} zerbrach.",
		"log.saved": "{house.in} wurde {who} angegriffen, aber {healer} {h:pflegte|pflegte|pflegtest} {who:ihn|sie|dich} gesund.",
		"log.meeting": "{who.cap} {who:läutete|läutete|läutetest} die Glocke: Notversammlung.",
		"log.event": "{e}.",
		"sys.dawn1": "Es dämmert. Alle kommen auf den Platz.",
		"sys.dawn": "Tag {d}. Noch am Leben: {n}.",
		"job.water.title": "Wasser holen",
		"job.water.place": "am Brunnen",
		"job.water.done": "Wasser bis zum Morgen.",
		"job.wood.title": "Holz hacken",
		"job.wood.place": "beim Holzstapel",
		"job.wood.done": "Holz für die ganze Nacht.",
		"job.lamp.title": "Lampen füllen",
		"job.lamp.place": "an der Laterne",
		"job.lamp.done": "Die Lampen sind voll.",
		"job.fish.title": "Fische fangen",
		"job.fish.place": "am Fluss",
		"job.fish.done": "Fisch fürs Abendessen.",
		"job.talisman.title": "Bannzeichen ausbessern",
		"job.talisman.place": "am Bannzeichen",
		"job.talisman.done": "Das Bannzeichen ist wie neu.",
		"job.box.title": "Kiste öffnen",
		"job.box.place": "bei der Kiste",
		"role.elder": "{who:Ältester|Älteste|Ältester}",
		"role.elder.mid": "{who:der Älteste|die Älteste|der Älteste}",
		"role.healer": "{who:Heiler|Heilerin|Heiler}",
		"role.healer.mid": "{who:der Heiler|die Heilerin|der Heiler}",
		"role.headman": "{who:Schultheiß|Schultheißin|Schultheiß}",
		"role.headman.mid": "{who:der Schultheiß|die Schultheißin|der Schultheiß}",
		"role.named": "{role} {who}",
		"event.fog.title": "Nebel",
		"event.fog.mid": "Nebel",
		"event.fog.text": "Nebel dämpft die Glocke: weniger Zeit zum Laufen, draußen ist es gefährlicher.",
		"event.moon.title": "Vollmond",
		"event.moon.mid": "Vollmond",
		"event.moon.text": "Vollmond: bis zum Morgen werden alle Bannzeichen schwächer.",
		"event.quiet.title": "Stille Nacht",
		"event.quiet.mid": "stille Nacht",
		"event.quiet.text": "Stille Nacht: draußen ist es ruhiger, der Nachahmer kommt nicht.",
		"event.rain.title": "Wolkenbruch",
		"event.rain.mid": "Wolkenbruch",
		"event.rain.text": "Der Regen ertränkt die Lampen: das Öl aus den Vorräten hilft heute Nacht nicht.",
		"recap.street_host": "Man hat dich {house.of} nicht reingelassen: dort war {who} der Wirt.",
		"recap.street": "Du hast die Nacht draußen verbracht. Dort sterben fast alle.",
		"recap.street_p": "Chance, in dieser Nacht draußen zu sterben: {p} %.",
		"recap.killer": "{who} hat dich getötet. {who:Er|Sie} war ein Werwolf.",
		"recap.you_opened": "Du hast {who} selbst die Tür geöffnet.",
		"recap.killer_opened": "{who} hat dir selbst die Tür geöffnet.",
		"recap.near": "In der Nähe: {others}.",
		"recap.alone": "Du warst allein {house.in}. Allein hält das Bannzeichen nicht bis zum Morgen.",
		"recap.alone_p": "Chance, allein in diesem Haus zu sterben: {p} %. Hol dir tagsüber jemanden dazu.",
		"recap.creature": "Das Bannzeichen {house.gen} war gebrochen, und das Ding aus dem Wald kam herein.",
		"recap.creature_tip": "Tagsüber hätte man das Bannzeichen ausbessern können: das ist eine Arbeit auf dem Platz.",
		"recap.mimic_you": "Du hast {voice.pos} Stimme die Tür geöffnet. Es war der Nachahmer.",
		"recap.mimic_host": "{who} hat {voice.pos} Stimme hereingelassen. Es war der Nachahmer.",
		"recap.voice_dead": "{voice} war da schon tot.",
		"recap.voice_away": "Und {voice} war zu der Zeit {house.in}.",
		"recap.exiled": "Du wurdest an Tag {d} verbannt. Gegen dich: {list}.",
		"recap.exiled_many": "Du wurdest an Tag {d} verbannt. Gegen dich: die Mehrheit.",
		"recap.seen": "Das Dorf hat gesehen: {ev}.",
		"recap.exiled0": "Du wurdest verbannt.",
		"recap.died": "Du bist in Nacht {n} gestorben. {why}",
		"verdict.mimic": "In Nacht {n} hast du dem Nachahmer die Tür geöffnet, {voice.pos} Stimme.",
		"verdict.let_upyr": "In Nacht {n} hast du {who} hereingelassen, und {who:er|sie} war ein Werwolf.",
		"verdict.vote_upyr": "An Tag {n} hat deine Stimme geholfen, einen Werwolf zu verbannen: {who}.",
		"verdict.vote_human": "An Tag {n} hast du gegen {who} gestimmt, und {who:er|sie} war ein Mensch.",
		"verdict.clean": "Du hast nie einem Werwolf die Tür geöffnet und den Morgen erlebt.",
		"verdict.dead": "Du hast den Morgen nicht erlebt.",
		"verdict.kills": " Auf deinem Konto: {n}.",
		"verdict.upyr_won": "Das Dorf hat nie gemerkt, dass du der Werwolf bist.",
		"verdict.upyr_lost": "Du hast den Morgen erlebt, aber das Dorf hat durchgehalten.",
		"sys.box": "Am Rand des Platzes steht eine Kiste. Gestern war sie nicht da.",
		"sys.elder_upyr": "Die Zeichnungen des Ältesten: {who} ist ein Werwolf. Das weißt nur du.",
		"sys.elder_human": "Die Zeichnungen des Ältesten: {who} ist ein Mensch. Das weißt nur du.",
		"sys.bell_you": "Du läutest die Glocke. Notversammlung!",
		"sys.bell": "{who} läutet die Glocke. Notversammlung!",
		"box.note": "In der Kiste ein Zettel: „{a.cap} oder {b}\". Einer von beiden ist ein Werwolf. Den Zettel siehst nur du.",
		"box.oil": "In der Kiste ist Lampenöl: Vorräte +{n}.",
		"box.chalk": "In der Kiste ist Kreide: das Bannzeichen {house.gen} ist nachgezogen.",
		"box.empty": "Die Kiste ist leer.",
		"say.accuse": "Ich glaube, es ist {who}.",
		"say.invite": "{who}, gehen wir zusammen {house.to}?",
		"say.ask": "{who}, wo schläfst du heute?",
		"say.defend": ["Ich bin kein Werwolf. Ich schwöre.", "Ich gehöre zu euch. Prüft mich heute Nacht.", "Nicht ich. Sucht weiter."],
		"toast.elder_upyr": "Zeichnungen: {who} ist ein Werwolf",
		"toast.elder_human": "Zeichnungen: {who} ist ein Mensch",
		"toast.box_taken": "Die Kiste wurde schon geöffnet",
		"toast.job_done": "„{job}\": für heute erledigt",
		"toast.box": "Auf dem Platz ist eine Kiste aufgetaucht",
		"toast.back_exit": "Noch einmal drücken zum Beenden",
		"quit.ask": "Partie abbrechen?",
		"quit.stay": "Bleiben",
		"quit.leave": "Zum Menü",
		"cfg.players": "Spieler",
		"cfg.monsters": "Werwölfe",
		"cfg.shelters": "Unterkünfte",
		"cfg.capacity": "Plätze pro Unterkunft",
		"cfg.nights": "Nächte bis zum Morgen",
		"cfg.day_seconds": "Tag, Sekunden",
		"cfg.door_seconds": "Entscheidung an der Tür, Sekunden",
		"cfg.run_seconds": "Lauf nach Hause, Sekunden",
		"cfg.outside_death": "Tod draußen, %",
		"cfg.first_night_outside_death": "Dasselbe in der ersten Nacht, %",
		"cfg.vote_from_day": "Verbannung ab Tag",
		"diff.easy": "Leicht",
		"diff.normal": "Normal",
		"diff.hard": "Schwer",
		"diff.custom": "Eigene",
		"diff.cast": "{p} Dorfbewohner, {u} {u#Werwolf|Werwölfe}.",
		"diff.human": " Du bist immer ein Mensch.",
		"diff.easy_note": " Längerer Tag.",
		"diff.hard_note": " Kürzerer Tag, gefährlichere Straße.",
		"diary.exiled": "Verbannt an Tag {n}.",
		"diary.died": "Gestorben in Nacht {n}.",
		"diary.night": "{n}: {where}",
		"diary.street": "draußen",
		"diary.said": " (sagte: {house})",
		"diary.nights": "Nächte: {list}.",
		"diary.today": "Will heute: {house}.",
		"diary.evidence": "Indizien: {ev}.",
		"diary.own_claim": "{text}.",
		"diary.claim": "{who.cap} {text}.",
		"diary.seen_upyr": "Deine Zeichnungen: Werwolf.",
		"diary.seen_human": "Deine Zeichnungen: Mensch.",
		"diary.nothing": "Noch nichts bekannt.",
		"diary.head": "Tagebuch: was wir über jeden wissen",
		"diary.gone": "{who} · tot",
		"journal.who": "{who}:",
		"journal.head": "Protokoll des Tages",
		"ui.close": "Schließen",
		"ui.cancel": "Abbrechen",
		"say.placeholder": "Oder schreib selbst",
		"say.send": "Sagen",
		"chip.exiled": " · verbannt",
		"supplies": "Vorräte {a} von {b}",
		"howto.art_accuse": "Du bist der Werwolf!",
		"howto.art_street": "‹ draußen",
		"howto.art_door": "Reinlassen?",
		"game.title": "Lass mich rein",
		"menu.tale": "Nachts überlebt draußen niemand.\nEs gibt weniger Unterkünfte als Menschen.\n\nJemand steht an der Tür und bittet um Einlass. Jemand drinnen entscheidet.",
		"menu.hint": "Werwölfe sind unter euch. Sie kennen sich nicht einmal untereinander.",
		"menu.howto": "Spielregeln",
		"menu.play": "Spielen",
		"lang.pick": "Sprache",
		"diff.note": "{d}: {text}",
		"diff.note_custom": "Eigener Schwierigkeitsgrad: {text}",
		"settings.title": "Einstellungen",
		"settings.lang": "Sprache",
		"settings.sound": "Ton",
		"settings.music": "Musik",
		"settings.sfx": "Effekte",
		"settings.ambience": "Atmosphäre",
		"settings.haptics_on": "Vibration: an",
		"settings.haptics_off": "Vibration: aus",
		"settings.difficulty": "Schwierigkeit",
		"settings.hints": "Hinweise wieder zeigen",
		"settings.hints_reset": "Hinweise erscheinen wieder",
		"settings.note": "Jede Stufe wurde in 1500 Partien getestet. Am stärksten verschieben die Zahl der Unterkünfte und Nächte das Gleichgewicht.",
		"settings.start": "Mit diesen Einstellungen starten",
		"ui.back": "Zurück",
		"howto.day.title": "Tag",
		"howto.day.text": "Im Dorf leben Menschen, und unter ihnen Werwölfe. Werwölfe sehen aus wie alle anderen. Du bist ein Dorfbewohner mit Laterne.\n\nTagsüber sind alle auf dem Platz. Tippe auf einen Bewohner: beschuldige ihn, lade ihn zum gemeinsamen Übernachten ein oder frag, wo er schläft. Ein rotes Auge über dem Kopf heißt: das Dorf verdächtigt ihn.\n\nTippe auf ein Arbeitssymbol: Wasser, Holz, Lampen. Je mehr Vorräte, desto heller die Nacht. Werwölfe tun nur so, als würden sie arbeiten, oder verderben sogar Geschafftes. Manchmal taucht auf dem Platz eine Kiste auf: wer sie zuerst öffnet, bekommt den Fund.",
		"howto.night.title": "Nacht",
		"howto.night.text": "Abends läutet die Glocke, und alle laufen nach Hause. Solange sie läutet, tippe auf ein Haus. Es gibt weniger Unterkünfte als Menschen: wer draußen bleibt, erlebt den Morgen kaum.\n\nAllein im Haus ist es auch gefährlich. Verabrede tagsüber, mit wem du übernachtest, und bessere ein rissiges Bannzeichen aus: in ein Haus mit gebrochenem kommt das Ding aus dem Wald.",
		"howto.door.title": "Die Tür",
		"howto.door.text": "Wer zuerst am Haus ist, entscheidet, wer hereinkommt.\n\nLässt du einen Werwolf rein, erlebst du den Morgen nicht. Lässt du niemanden rein, bist du allein. Schau morgens, wer wo geschlafen und wer gelogen hat.\n\nManchmal klopft es mit der Stimme von jemandem, der gerade in einem anderen Haus ist oder schon tot. Das ist der Nachahmer: nicht aufmachen.\n\nManche Menschen haben Rollen: Ältester, Heiler, Schultheiß. Einmal pro Partie kannst du tagsüber die Glocke läuten und sofort abstimmen lassen. Alles, was über jeden bekannt ist, steht im Tagebuch.",
		"howto.title": "Spielregeln · {a} von {b}",
		"howto.got_it": "Verstanden",
		"ui.next": "Weiter",
		"ui.skip": "Überspringen",
		"crash.title": "Bericht",
		"crash.head": "Die letzte Sitzung wurde unerwartet beendet",
		"crash.text": "Das ist ein Fehler im Spiel, nicht deiner. Tippe auf „Bericht kopieren\" und schick ihn uns: daran sieht man, bei welchem Schritt alles abgebrochen ist.",
		"crash.steps": "Letzte Schritte:",
		"crash.copy": "Bericht kopieren",
		"crash.copied": "Kopiert: füge ihn in den Chat ein",
		"ui.continue": "Weiter",
		"prologue.title": "Vor der ersten Nacht",
		"prologue.pre": "Deine Rolle…",
		"prologue.upyr": "Du bist ein Werwolf",
		"prologue.human": "Du bist ein Mensch",
		"prologue.upyr_text": "Du weißt nicht, wer noch so ist wie du. Draußen kann dir nichts passieren, und wer mit dir hinter einer Tür landet, erlebt den Morgen nicht. Tagsüber redest du wie ein Mensch.",
		"prologue.human_text": "Nachts draußen stirbst du fast sicher. In einer Unterkunft darfst du nicht allein bleiben: dann erlischt das Bannzeichen. Du brauchst einen Zweiten und weißt nicht, wer von ihnen ein Mensch ist.",
		"prologue.facts": "{p} Bewohner, {u} {u#Werwolf|Werwölfe}. {s} {s#Unterkunft|Unterkünfte} mit je {c} Plätzen. Überlebe bis zum {n}. Morgen.",
		"prologue.go": "Zu den Leuten gehen",
		"prologue.elder": "Du bist der Älteste. Einmal pro Partie kannst du tagsüber auf einen Bewohner tippen und die Zeichnungen lesen: du erfährst, ob er ein Werwolf ist. Nur du.",
		"prologue.healer": "Du bist der Heiler. Einmal pro Partie nimmst du vor der Nacht deine Kräuter: wird jemand neben dir im Haus angegriffen, pflegst du ihn gesund.",
		"prologue.headman": "Du bist der Schultheiß. Bei der Verbannung zählt deine Stimme doppelt.",
		"end.title": "Auswertung",
		"end.people": "Die Menschen haben durchgehalten",
		"end.upyri": "Das Dorf ist leer",
		"end.won": "Deine Seite hat gewonnen.",
		"end.lost": "Deine Seite hat verloren.",
		"end.who": "Wer war wer",
		"end.upyr": "Werwolf",
		"end.human": "Mensch",
		"end.with_role": "{a}, {role}",
		"end.chip": "{who}: {what}",
		"end.how": "Wie es lief",
		"end.again": "Noch eine Partie",
		"end.verdict": "Was die Partie entschieden hat",
		"end.offer_easier": "Leichter machen?",
		"end.offer_harder": "Zwei Siege in Folge. Schwerer versuchen?",
		"end.easier": "Leichter machen",
		"end.harder": "Schwerer versuchen",
		"vote.title": "Verbannung",
		"vote.bell_you": "Notversammlung: du hast die Glocke geläutet.",
		"vote.bell": "Notversammlung: {who} hat die Glocke geläutet.",
		"vote.ask": "Wen jagen wir aus dem Dorf? Wer verbannt wird, geht für immer. Was er war, erfahrt ihr am Ende.",
		"day.diary": "Tagebuch",
		"vote.headman": "Du bist der Schultheiß: deine Stimme zählt doppelt.",
		"vote.dead": "Du bist tot und schaust nur zu.",
		"vote.watch": "Ergebnis ansehen",
		"vote.go": "Verbannen",
		"vote.none": "Niemand wurde verbannt",
		"vote.gone": "{who} ist fort",
		"vote.gone_you": "Du wurdest verbannt",
		"vote.row": "{who}: {n}",
		"vote.night": "Die Nacht bricht an",
		"mo.title": "Morgen",
		"mo.all_alive": "Alle haben überlebt",
		"mo.one_dead": "Einer fehlt",
		"mo.dead_n": "Es fehlen: {n}",
		"mo.why": "Warum du gestorben bist",
		"mo.event": "Heute Nacht: {e}.",
		"mo.street_dead": "{who.cap} {who:wurde|wurde|wurdest} {house.of} abgewiesen. {who:Er lag morgens auf der Straße.|Sie lag morgens auf der Straße.|Du bist draußen gestorben.}",
		"mo.alone_dead": "{who.cap} {who:war|war|warst} allein {house.in}. Das Bannzeichen erlosch.",
		"mo.killed": "{who.cap} {who:starb|starb|starbst} {house.in}. In der Nähe: {others}.",
		"mo.street_ok": "{who.cap} {who:hat|hat|hast} die Nacht draußen verbracht. Und {who:ist|ist|bist} zurückgekommen.",
		"mo.alone_ok": "{who.cap} {who:war|war|warst} allein {house.in} und {who:ist|ist|bist} heil.",
		"mo.clean": "{house.in} schliefen {list}. Alle sind heil.",
		"mo.liar": "{who.cap} {who:sprach|sprach|sprachst} von {said}, {who:schlief|schlief|schliefst} aber {house.in}.",
		"mo.creature": "Das Bannzeichen {house.gen} war gebrochen. Das Ding aus dem Wald holte {who}.",
		"mo.talisman_cracked": "Das Bannzeichen {house.gen} hat einen Riss. Tagsüber kann man es ausbessern.",
		"mo.talisman_broken": "Das Bannzeichen {house.gen} ist zerbrochen. Tagsüber kann man es ausbessern.",
		"mo.saved_upyr": "{house.in.cap} griff jemand aus den eigenen Reihen {who} an, aber {healer} {h:pflegte|pflegte|pflegtest} {who:ihn|sie|dich} gesund.",
		"mo.saved_creature": "{house.in.cap} griff das Ding aus dem Wald {who} an, aber {healer} {h:pflegte|pflegte|pflegtest} {who:ihn|sie|dich} gesund.",
		"mo.saved_mimic": "{house.in.cap} griff der Nachahmer {who} an, aber {healer} {h:pflegte|pflegte|pflegtest} {who:ihn|sie|dich} gesund.",
		"mo.tunnel": "{who.cap} {who:wurde|wurde|wurdest} {from.of} abgewiesen und {who:kroch|kroch|krochst} durch den Tunnel {house.to}.",
		"mo.mimic_kill": "{house.in.cap} ließ man {voice.pos} Stimme herein. Es war nicht {voice}: der Nachahmer holte {who}.",
		"mo.mimic_spared": "{house.in.cap} ließ man {voice.pos} Stimme herein. Es war nicht {voice}, aber alle überlebten bis zum Morgen.",
		"mo.mimic_knock": "Nachts klopfte jemand mit {voice.pos} Stimme an die Tür {house.gen}. Niemand machte auf. Es war der Nachahmer.",
		"mo.mimic_knock_away": "Nachts klopfte jemand mit {voice.pos} Stimme an die Tür {house.gen}. Niemand machte auf. Und {voice} war zu der Zeit {away.in}.",
		"list.sep": ", ",
		"night.dusk": "Es dunkelt. Die Glocke läutet.",
		"night.dead": "Du bist nicht mehr da. Die Nacht geht ohne dich weiter.",
		"night.bell": "Die Glocke läutet! Lauf nach Hause: tippe auf ein Haus.",
		"night.going": "wollen hin: {list}",
		"night.pact": "Abmachung mit {who}",
		"night.tunnel": "Tunnel {house.to}",
		"night.tal_broken": "Bannzeichen gebrochen",
		"night.tal_cracked": "Bannzeichen rissig",
		"night.rule": "Wer zuerst an der Tür ist, ist drinnen und entscheidet, wer hereinkommt. Wählst du beim Läuten kein Haus, läufst du als Letzter dorthin, wo du hinwolltest.",
		"night.heal": "Kräuter nehmen: heute Nacht rette ich einen Nachbarn",
		"night.hint": "Die Glocke läutet nicht lange. Tippe auf ein Haus auf dem Platz oder in der Liste und lauf. Wer zuerst an der Tür ist, entscheidet, wer hereinkommt.",
		"night.heal_on": "Kräuter dabei: wird jemand neben dir angegriffen, pflegst du ihn gesund",
		"night.first": "Du bist als Erster da: du entscheidest, wer hereinkommt.",
		"night.ahead": "Vor dir an der Tür: {list}. Entscheiden wird {who}.",
		"night.run": "Du läufst {house.to}. {rest}",
		"door.title": "An der Tür",
		"door.hint_host": "Lass rein, wem du traust. Machst du niemandem auf, bleibst du allein, und allein überlebt man nicht.",
		"door.hint_guest": "Wähle, was du durch die Tür sagst. Der Wirt weiß noch, ob ihr schon zusammen übernachtet habt.",
		"door.hint_alone": "Allein überlebt man hier nicht. Hol dir nächstes Mal tagsüber jemanden dazu.",
		"door.host": "Du warst als Erster {house.of}. Es klopft.",
		"door.cap": "Reinlassen kannst du: {n}",
		"door.quote": "„{text}\"",
		"door.admit": "Reinlassen",
		"door.admitting": "Lasse rein",
		"door.elsewhere": "An anderen Türen: {list}.",
		"door.upyr_note": "Wen du reinlässt, der erlebt den Morgen nicht.",
		"door.alone_note": "Machst du niemandem auf, bleibst du allein, und das Bannzeichen erlischt.",
		"door.open": "Tür öffnen",
		"door.refuse": "Niemandem öffnen",
		"door.locked": "{house.nom} ist schon von innen verriegelt. Drinnen ist {who}.",
		"door.rivals": "Mit dir an der Tür: {list}. Für alle reicht der Platz nicht.",
		"door.mimic": "Hinter dir im Dunkeln spricht jemand mit {voice.pos} Stimme. Aber {voice} ist nicht hier.",
		"door.say": "Was sagst du durch die Tür?",
		"door.knock": "Du klopfst an die Tür {house.gen}…",
		"door.let_in": "Der Riegel klickt. {who} lässt dich herein.",
		"door.shut": "Schritte entfernen sich von der Tür. Du bleibst draußen.",
		"door.hatch": "Hinter dem Haus ist eine Luke. Der Tunnel führt {house.to}, dort ist Platz. Wer durchkriecht, ist drinnen, aber morgens wissen alle, woher er kam.",
		"door.tunnel": "Durch den Tunnel {house.to}",
		"door.wait": "Auf den Morgen warten",
		"door.alone": "Du warst als Erster {house.of}. Sonst ist niemand gekommen.",
		"door.alone_upyr": "Einem einsamen Werwolf macht die Straße keine Angst.",
		"door.alone_human": "Das Bannzeichen flackert. Allein hältst du es nicht bis zum Morgen.",
		"day.journal": "Protokoll",
		"day.journal_n": "Protokoll ({n})",
		"day.dead": "Du bist nicht mehr da. Du schaust nur zu.",
		"day.skip": "Tag überspringen",
		"day.defend": "Rechtfertigen",
		"day.invite": "Einladen…",
		"day.accuse": "Beschuldigen…",
		"day.say": "Sagen…",
		"day.bell": "Glocke!",
		"day.ready": "Bereit zur Nacht",
		"day.hint": "Tippe auf einen Bewohner: beschuldige ihn, lade ihn ein oder frag, wo er schläft. Tippe auf ein Arbeitssymbol: Vorräte zünden nachts die Lampen an.",
		"day.bell_ask": "Die Glocke läuten? Alle kommen sofort zur Abstimmung. Das geht einmal pro Partie.",
		"day.bell_do": "Glocke läuten",
		"day.preview": "{who}: {text}",
		"day.say_aloud": "Laut sagen",
		"day.person_ev": "{who} · {ev}",
		"day.p_accuse": "Beschuldigen: „Es ist {who}\"",
		"day.p_invite": "Für die Nacht einladen",
		"day.p_ask": "Nach dem Schlafplatz fragen",
		"day.p_elder": "Zeichnungen des Ältesten ansehen: was ist {who:er|sie}?",
		"day.work": "Arbeiten: {job}",
		"day.spoil": "Geschafftes {place} verderben",
		"day.who_accuse": "Wen beschuldigen?",
		"day.who_invite": "Wen einladen?",
		"day.where_with": "Wohin gehst du mit {who}?",
	}
