extends Gram
## English. An English village: Robin and Marian from the greenwood, a detective in a deerstalker,
## Alice in a blue pinafore, old Scrooge in a top hat. Houses: River Cottage, the Barn, the Chapel…
## Names don't decline; {who.pos} gives "Rita's". The player is "you".


func code() -> String:
	return "en"


func name_case(name: String, case: String, _female: bool) -> String:
	if case == "pos":
		return name + ("'" if name.ends_with("s") else "'s")
	return name


func data() -> Dictionary:
	return {
		"and": " and ",
		"you": {"nom": "you", "acc": "you", "gen": "you", "dat": "you", "ins": "you", "pos": "your"},
		"you_name": "You",
		"someone": {"nom": "someone else", "acc": "someone else", "gen": "someone else", "dat": "someone else", "pos": "someone else's"},
		## nom — on the sign and in lists; in — inside a sentence: "sleeping in the Barn".
		"houses": [
			{"nom": "River Cottage", "in": "River Cottage", "of": "River Cottage"},
			{"nom": "Barn", "in": "the Barn", "of": "the Barn"},
			{"nom": "Chapel", "in": "the Chapel", "of": "the Chapel"},
			{"nom": "Cellar", "in": "the Cellar", "of": "the Cellar"},
			{"nom": "Garage", "in": "the Garage", "of": "the Garage"},
		],
		"names": [
			["Marian", true], ["Robin", false], ["Alice", true], ["Bertie", false], ["Jane", true], ["Sherlock", false],
			["John", false], ["Lizzie", true], ["Scrooge", false], ["Nell", true], ["Tuck", false], ["Martha", true],
		],
		"looks": "res://config/looks_en.tres",
		"ph.ANNOUNCE": [
			"I'm in {house.in} tonight.",
			"Going to {house.in}. Who's with me?",
			"Sleeping in {house.in}, if anyone asks.",
			"{house.in.cap}. Decided.",
		],
		"ph.ACCUSE_STRONG": [
			"{who}, explain how you made it to morning.",
			"It's clear to me. {who}.",
			"{who} was right there when it happened. Coincidence?",
			"I'm voting for {who}. No question.",
		],
		"ph.ACCUSE_STREET": [
			"{who} spent the night outside and came back. People can't do that.",
			"{who}, you were out all night. Anything to tell us?",
		],
		"ph.ACCUSE_LIAR": [
			"{who} said {house.in}, then slept somewhere else. Why lie?",
			"{who}, you were headed somewhere else. What changed?",
		],
		"ph.DEFEND": [
			"Yes, I was there. So what?",
			"I'm not a vampire. Check me tonight.",
			"I just picked the wrong room.",
			"Throw me out now, and in the morning you'll be two more short.",
		],
		"ph.UPYR_DEFLECT": [
			"If I were you, I'd watch {who}.",
			"You're arguing, and night is coming.",
			"Let's not rush. Get it wrong and we lose one of our own.",
			"{who}, why are you so quiet all the time?",
			"I kept my head down yesterday and lived. So I did it right.",
		],
		"ph.FILLER": [
			"There are fewer of us every day. Count.",
			"Let's decide faster, it's getting dark.",
			"I don't trust anyone. Anyone.",
			"One of you is lying right now.",
		],
		"ph.REPLY_TO_ACCUSED_HUMAN": [
			"Me? Really? Look at {who} instead.",
			"You've got me mixed up with someone.",
			"Fine. Throw me out. You'll see in the morning.",
		],
		"ph.REPLY_TO_ACCUSED_UPYR": [
			"Funny. Let's talk about you instead.",
			"That's how you sink your own. Convenient.",
			"You're in a hurry to get rid of me. Suspicious.",
		],
		"ph.AGREE_ACCUSE": [
			"Agreed. I don't like {who} either.",
			"Seconded. {who}.",
		],
		"ph.DISAGREE_ACCUSE": [
			"Nah, {who} seems all right. What's with you?",
			"Weak. Where's the proof?",
		],
		"ph.INVITE_YES": [
			"Sure. Meet me at {house.in}.",
			"Fine, I'll go to {house.in} with you.",
			"All right. Just don't let me down.",
		],
		"ph.INVITE_NO": [
			"No, I'm not going with you. Nothing personal.",
			"I don't trust you yet.",
			"I've already got someone.",
		],
		"ph.ASK_ANSWER_HUMAN": [
			"I'm in {house.in}. No secret.",
			"I told you: {house.in}.",
		],
		"ph.ASK_ANSWER_UNSURE": [
			"Haven't decided yet.",
			"I'll see who goes where.",
		],
		"ph.PLAYER_DEFEND_REACTION": [
			"Sure, sure.",
			"We'll see.",
			"That's what they all say.",
			"Fine, I believe you. For now.",
		],
		"ph.GENERIC_REACTION": [
			"And what's that supposed to mean?",
			"Smooth. Too smooth.",
			"Are you telling yourself or us?",
			"I hear you. Not convinced.",
		],
		"ph.AT_PLAYER": [
			"You're the one I have the most questions for.",
			"You're far too calm.",
			"You're hiding something.",
			"Take a look at yourself.",
			"I don't trust you. Not one bit.",
		],
		"ph.PLEA_AFTER_STREET": [
			"They shut me out last night. I won't survive a second time.",
			"I sat outside all night. Open up.",
		],
		"ph.PLEA_SUSPECT": [
			"I know how it looks. But I'm not a vampire.",
			"Trust me once. Throw me out later if you want.",
		],
		"ph.PLEA_NORMAL": [
			"Open up, it's cold out here.",
			"It's me. Let me in.",
			"Two of us can make it till morning.",
			"Hurry, something's moving out here.",
		],
		"ph.PLEA_PACT": [
			"It's me, we had a deal.",
			"Open up, like we agreed.",
		],
		"ph.JOB_FAKE": [
			"{who} was standing {place}, and nothing came of it.",
			"I saw {who} fiddling about {place} and getting nothing done.",
			"Odd. {who} went {place}, but our supplies didn't grow.",
			"{who} only pretends to work. Was {place}: nothing.",
			"What was {who} doing {place}? The buckets are as empty as ever.",
		],
		"ph.JOB_FAKE_AT_PLAYER": [
			"You're wasting time {place}. Supplies haven't grown.",
			"You're pretending to work {place}. I saw.",
			"What good are you {place}? The buckets are still empty.",
		],
		"ph.MIMIC_PLEAS": [
			"Let me in. It's me. It's me, {who}. Let me in.",
			"Open up, please. Please. It's cold. Cold.",
			"You know me. Open the door. Open the door.",
			"I've come home. Let me in, home.",
		],
		"ph.SABOTAGE_SEEN": [
			"{who} was hanging around {place}, and now it's all ruined.",
			"I saw {who} doing something {place}. {who:He|She} did it.",
			"Who's spoiling our supplies? {who} was the last one {place}.",
		],
		"ph.SABOTAGE_SEEN_AT_PLAYER": [
			"What are you doing {place}? I saw: everything's ruined after you.",
			"It's all ruined {place} after you left. I saw.",
		],
		"ph.ELDER_UPYR": [
			"I'm the Elder. I read the drawings: {who} is a vampire.",
			"Listen. I'm the Elder, and in the drawings {who} isn't human.",
		],
		"ph.ELDER_HUMAN": [
			"I'm the Elder. {who} is human, I checked.",
			"The drawings say {who} is clean. I'm the Elder, you can trust me.",
		],
		"ph.MEETING_CALL": [
			"Enough talk. We vote now: {who}.",
			"I'm ringing the bell. {who} is lying, we settle it before dark.",
			"Gather round. I won't sleep anywhere near {who}.",
		],
		"ph.BOX_NOTE": [
			"There's a note in the box: \"{a} or {b}\". One of them is a vampire.",
			"I opened the box. A note inside: \"{a} or {b}. One of the two isn't human.\"",
		],
		"ph.BOX_OIL": [
			"Lamp oil in the box. It'll be brighter tonight.",
			"I opened the box: oil. We'll fill the lamps.",
		],
		"ph.BOX_CHALK": [
			"Chalk in the box. I've redrawn the charm at {house.in}.",
		],
		"plea.shared.label": "We've slept here together before",
		"plea.shared.text": "We spent a night together and nothing happened.",
		"plea.promise.label": "Promise to let them in tomorrow",
		"plea.promise.text": "Let me in. Tomorrow I'll open for you first.",
		"plea.name.label": "Name the vampire",
		"plea.name.text": "I know who it is. Let me in and I'll tell you.",
		"plea.beg.label": "Just beg",
		"plea.beg.text": "Please. Nobody survives out here.",
		"spoil.water": "the buckets are knocked over",
		"spoil.wood": "the firewood is scattered in the mud",
		"spoil.lamp": "the oil is spilled",
		"spoil.fish": "the catch is thrown back in the river",
		"spoil.any": "everything is ruined",
		"quick.house": "I'm sleeping in {house.in}. Who's with me?",
		"quick": ["I'm not a vampire. I swear.", "Whoever came back from outside is the vampire.", "Let's stick together in pairs.", "Whoever lies about where they sleep goes."],
		"intent.accuse": ["vampire", "vamp", "it's him", "it's her", "liar", "lying", "suspic", "don't trust", "kick", "out with", "killer", "guilty"],
		"intent.invite": ["come with", "with me", "together", "join me", "let's go", "go to", "sleep at"],
		"intent.defend": ["not me", "i'm not", "i am not", "human", "swear", "innocent", "trust me"],
		"intent.ask": ["where", "which house", "going to"],
		"intent.houses": ["river", "barn", "chapel", "cellar", "garage"],
		"ev.street": "came back from outside alive",
		"ev.times": " ({n} times)",
		"ev.liar": "lied about where they'd sleep",
		"ev.death": "was nearby when someone died",
		"ev.fake": "worked for nothing",
		"ev.sabotage": "was at a spoiled job",
		"ev.tunnel": "crawled through the tunnel into another house",
		"ev.sep": "; ",
		"sys.sabotage": "Someone made a mess {place}: {what}. Supplies went down.",
		"claim.elder_upyr": "called {me:himself|herself} the Elder: {who} is a vampire",
		"claim.elder_human": "called {me:himself|herself} the Elder: {who} is human",
		"claim.healer": "{role}: healed {who} on night {n}",
		"when.night": "Night {n}",
		"when.day": "Day {n}",
		"chron.line": "{title}: {text}",
		"chron.morning": "Morning: {text}",
		"log.exiled": "the village banished {who}.",
		"log.supplies": "supplies gathered: {p}%.",
		"log.tunnel": "{who.cap} {who:was|was|were} turned away from {from}, and {who:he|she|you} crawled through the tunnel into {house.in}.",
		"log.street_upyr": "{who.cap} {who:was|was|were} turned away from {house}, but {who:he|she|you} lived till morning.",
		"log.street_dead": "{who.cap} {who:was|was|were} turned away from {house}. {who:He was found in the street in the morning.|She was found in the street in the morning.|You died in the street.}",
		"log.street_ok": "{who.cap} spent the night outside and survived.",
		"log.mimic_knock": "someone knocked at {house.in} in {voice.pos} voice. Nobody opened.",
		"log.mimic_spared": "{house.in.cap} let in {voice.pos} voice. It wasn't {voice}, but everyone lived till morning.",
		"log.mimic_kill": "{house.in.cap} let in {voice.pos} voice. It was the Mimic: it took {who}.",
		"log.alone_dead": "{who.cap} {who:was|was|were} alone in {house.in}. The charm went out.",
		"log.killed": "{who.cap} died in {house.in}. Nearby: {others}.",
		"log.clean": "{list} slept in {house.in}. Everyone is fine.",
		"log.creature": "the charm at {house.in} was broken. The thing from the forest took {who}.",
		"log.liar": "{who.cap} said {said}, but slept in {house.in}.",
		"log.talisman_cracked": "the charm at {house.in} cracked.",
		"log.talisman_broken": "the charm at {house.in} broke.",
		"log.saved": "in {house.in}, {who} {who:was|was|were} attacked, but {healer} nursed {who:him|her|you} back.",
		"log.meeting": "{who.cap} rang the bell: emergency meeting.",
		"log.event": "{e}.",
		"sys.dawn1": "Dawn. Everyone comes out to the square.",
		"sys.dawn": "Day {d}. {n} still alive.",
		"job.water.title": "Fetch water",
		"job.water.place": "at the well",
		"job.water.done": "Enough water till morning.",
		"job.wood.title": "Chop wood",
		"job.wood.place": "at the woodpile",
		"job.wood.done": "Firewood for the whole night.",
		"job.lamp.title": "Fill the lamps",
		"job.lamp.place": "by the lamp",
		"job.lamp.done": "Lamps are full.",
		"job.fish.title": "Catch fish",
		"job.fish.place": "by the river",
		"job.fish.done": "Fish for supper.",
		"job.talisman.title": "Fix the charm",
		"job.talisman.place": "by the charm",
		"job.talisman.done": "Charm's as good as new.",
		"job.box.title": "Open the box",
		"job.box.place": "by the box",
		"role.elder": "Elder",
		"role.elder.mid": "the Elder",
		"role.healer": "Healer",
		"role.healer.mid": "the Healer",
		"role.headman": "Headman",
		"role.headman.mid": "the Headman",
		"role.named": "{role} {who}",
		"event.fog.title": "Fog",
		"event.fog.mid": "fog",
		"event.fog.text": "Fog muffles the bell: less time to run, the street is deadlier.",
		"event.moon.title": "Full moon",
		"event.moon.mid": "full moon",
		"event.moon.text": "Full moon: every charm weakens by morning.",
		"event.quiet.title": "Quiet night",
		"event.quiet.mid": "quiet night",
		"event.quiet.text": "Quiet night: the street is safer, the Mimic won't come.",
		"event.rain.title": "Downpour",
		"event.rain.mid": "downpour",
		"event.rain.text": "Rain floods the lamps: stored oil won't help tonight.",
		"recap.street_host": "You were shut out of {house}: {who} was the host there.",
		"recap.street": "You spent the night outside. Almost nobody survives that.",
		"recap.street_p": "Chance of dying outside that night: {p}%.",
		"recap.killer": "{who} killed you. {who:He|She} was a vampire.",
		"recap.you_opened": "You opened the door to {who} yourself.",
		"recap.killer_opened": "{who} opened the door for you {who:himself|herself}.",
		"recap.near": "Nearby: {others}.",
		"recap.alone": "You were alone in {house.in}. One person isn't enough to hold the charm till morning.",
		"recap.alone_p": "Chance of dying alone in that house: {p}%. In the day, ask someone to come with you.",
		"recap.creature": "The charm at {house.in} was broken, and the thing from the forest got in.",
		"recap.creature_tip": "You could have fixed the charm in the day: it's a job on the square.",
		"recap.mimic_you": "You opened the door to {voice.pos} voice. It was the Mimic.",
		"recap.mimic_host": "{who} let in {voice.pos} voice. It was the Mimic.",
		"recap.voice_dead": "{voice} was already dead by then.",
		"recap.voice_away": "And {voice} was in {house.in} at the time.",
		"recap.exiled": "You were banished on day {d}. Against you: {list}.",
		"recap.exiled_many": "You were banished on day {d}. Against you: the majority.",
		"recap.seen": "The village saw: {ev}.",
		"recap.exiled0": "You were banished.",
		"recap.died": "You died on night {n}. {why}",
		"verdict.mimic": "On night {n} you opened the door to the Mimic, in {voice.pos} voice.",
		"verdict.let_upyr": "On night {n} you let in {who}, and {who:he|she} was a vampire.",
		"verdict.vote_upyr": "On day {n} your vote helped banish a vampire: {who}.",
		"verdict.vote_human": "On day {n} you voted against {who}, and {who:he|she} was human.",
		"verdict.clean": "You never opened the door to a vampire and lived to see dawn.",
		"verdict.dead": "You didn't live to see dawn.",
		"verdict.kills": " Your tally: {n}.",
		"verdict.upyr_won": "The village never figured out the vampire was you.",
		"verdict.upyr_lost": "You lived to see dawn, but the village held out.",
		"sys.box": "There's a box at the edge of the square. It wasn't there yesterday.",
		"sys.elder_upyr": "The Elder's drawings: {who} is a vampire. Only you know this.",
		"sys.elder_human": "The Elder's drawings: {who} is human. Only you know this.",
		"sys.bell_you": "You ring the bell. Emergency meeting!",
		"sys.bell": "{who} rings the bell. Emergency meeting!",
		"box.note": "A note in the box: \"{a.cap} or {b}\". One of them is a vampire. Only you can see the note.",
		"box.oil": "Lamp oil in the box: supplies +{n}.",
		"box.chalk": "Chalk in the box: the charm at {house.in} is redrawn.",
		"box.empty": "The box is empty.",
		"say.accuse": "I think it's {who}.",
		"say.invite": "{who}, shall we go to {house.in} together?",
		"say.ask": "{who}, where are you sleeping tonight?",
		"say.defend": ["I'm not a vampire. I swear.", "I'm one of you. Check me tonight.", "Not me. Keep looking."],
		"toast.elder_upyr": "Drawings: {who} is a vampire",
		"toast.elder_human": "Drawings: {who} is human",
		"toast.box_taken": "The box has already been opened",
		"toast.job_done": "\"{job}\": done for today",
		"toast.box": "A box appeared on the square",
		"toast.back_exit": "Press again to exit",
		"quit.ask": "Abandon the game?",
		"quit.stay": "Stay",
		"quit.leave": "Exit to menu",
		"cfg.players": "Players",
		"cfg.monsters": "Vampires",
		"cfg.shelters": "Shelters",
		"cfg.capacity": "Places per shelter",
		"cfg.nights": "Nights until dawn",
		"cfg.day_seconds": "Day, seconds",
		"cfg.door_seconds": "Door decision, seconds",
		"cfg.run_seconds": "Run home, seconds",
		"cfg.outside_death": "Death outside, %",
		"cfg.first_night_outside_death": "Same on the first night, %",
		"cfg.vote_from_day": "Banishing from day",
		"diff.easy": "Easy",
		"diff.normal": "Normal",
		"diff.hard": "Hard",
		"diff.custom": "Custom",
		"diff.cast": "{p} {p#villager|villagers}, {u} {u#vampire|vampires}.",
		"diff.human": " You're always human.",
		"diff.easy_note": " Longer days.",
		"diff.hard_note": " Shorter days, deadlier streets.",
		"diary.exiled": "Banished on day {n}.",
		"diary.died": "Died on night {n}.",
		"diary.night": "{n}: {where}",
		"diary.street": "outside",
		"diary.said": " (said: {house})",
		"diary.nights": "Nights: {list}.",
		"diary.today": "Going tonight: {house}.",
		"diary.evidence": "Evidence: {ev}.",
		"diary.own_claim": "{text}.",
		"diary.claim": "{who.cap} {text}.",
		"diary.seen_upyr": "Your drawings: vampire.",
		"diary.seen_human": "Your drawings: human.",
		"diary.nothing": "Nothing known yet.",
		"diary.head": "Diary: what we know about everyone",
		"diary.gone": "{who} · dead",
		"journal.who": "{who}:",
		"journal.head": "Today's log",
		"ui.close": "Close",
		"ui.cancel": "Cancel",
		"say.placeholder": "Or type your own",
		"say.send": "Say",
		"chip.exiled": " · banished",
		"supplies": "Supplies {a} of {b}",
		"howto.art_accuse": "You're the vampire!",
		"howto.art_street": "‹ outside",
		"howto.art_door": "Let in?",
		"game.title": "Let Me In",
		"menu.tale": "At night, no one survives outside.\nThere are fewer shelters than people.\n\nSomeone stands at the door and begs to be let in. Someone inside decides.",
		"menu.hint": "Vampires walk among you. They don't even know each other.",
		"menu.howto": "How to play",
		"menu.play": "Play",
		"lang.pick": "Language",
		"diff.note": "{d}: {text}",
		"diff.note_custom": "Custom difficulty: {text}",
		"settings.title": "Settings",
		"settings.lang": "Language",
		"settings.sound": "Sound",
		"settings.music": "Music",
		"settings.sfx": "Effects",
		"settings.ambience": "Ambience",
		"settings.haptics_on": "Vibration: on",
		"settings.haptics_off": "Vibration: off",
		"settings.difficulty": "Difficulty",
		"settings.hints": "Show hints again",
		"settings.hints_reset": "Hints will show again",
		"settings.note": "Each level was tested over 1,500 games. The number of shelters and nights moves the balance most.",
		"settings.start": "Start with these settings",
		"ui.back": "Back",
		"howto.day.title": "Day",
		"howto.day.text": "People live in the village, and vampires live among them. Vampires look like everyone else. You are a villager with a lantern.\n\nBy day everyone is on the square. Tap a villager: accuse them, invite them to spend the night together or ask where they're sleeping. A red eye over a head means the village suspects them.\n\nTap a job icon: water, firewood, lamps. The more supplies, the brighter the night. Vampires pretend to work or even spoil what's done. Sometimes a box appears on the square: whoever opens it first gets what's inside.",
		"howto.night.title": "Night",
		"howto.night.text": "In the evening the bell rings and everyone runs home. While it rings, tap a house. There are fewer shelters than people: whoever stays outside will hardly see the morning.\n\nBeing alone in a house is risky too. In the day, agree on who you'll sleep with and fix a cracked charm: the thing from the forest comes into a house with a broken one.",
		"howto.door.title": "The door",
		"howto.door.text": "Whoever reaches a house first decides who gets in.\n\nLet in a vampire and you won't see the morning. Let in nobody and you're alone. In the morning, check who slept where and who lied.\n\nSometimes the knocking comes in the voice of someone who is in another house or already dead. That's the Mimic: don't open.\n\nSome people have roles: Elder, Healer, Headman. Once a game you can ring the bell in the day and vote right away. Everything known about each villager is in the Diary.",
		"howto.title": "How to play · {a} of {b}",
		"howto.got_it": "Got it",
		"ui.next": "Next",
		"ui.skip": "Skip",
		"crash.title": "Report",
		"crash.head": "The last session closed unexpectedly",
		"crash.text": "This is a bug in the game, not your fault. Tap \"Copy report\" and send it to us: it shows the step where everything stopped.",
		"crash.steps": "Last steps:",
		"crash.copy": "Copy report",
		"crash.copied": "Copied: paste it into the chat",
		"ui.continue": "Continue",
		"prologue.title": "Before the first night",
		"prologue.pre": "Your role…",
		"prologue.upyr": "You are a vampire",
		"prologue.human": "You are human",
		"prologue.upyr_text": "You don't know who else is like you. The street can't hurt you, and whoever ends up behind one door with you won't live till morning. By day, talk like a human.",
		"prologue.human_text": "At night outside you'll almost certainly die. You can't stay alone in a shelter: the charm goes out. You need a second person, and you don't know which of them is human.",
		"prologue.facts": "{p} villagers, {u} {u#vampire|vampires}. {s} {s#shelter|shelters} for {c} each. Survive until dawn number {n}.",
		"prologue.go": "Go out to the people",
		"prologue.elder": "You're the Elder. Once a game, by day, tap a villager and read the drawings: you'll learn whether they're a vampire. Only you will know.",
		"prologue.healer": "You're the Healer. Once a game, before night, take your herbs: if someone near you in the house is attacked, you'll nurse them back.",
		"prologue.headman": "You're the Headman. At banishing, your vote counts twice.",
		"end.title": "Debrief",
		"end.people": "The people held out",
		"end.upyri": "The village is empty",
		"end.won": "Your side won.",
		"end.lost": "Your side lost.",
		"end.who": "Who was who",
		"end.upyr": "vampire",
		"end.human": "human",
		"end.with_role": "{a}, {role}",
		"end.chip": "{who}: {what}",
		"end.how": "How it went",
		"end.again": "Play again",
		"end.verdict": "What decided the game",
		"end.offer_easier": "Make it easier?",
		"end.offer_harder": "Two wins in a row. Try harder?",
		"end.easier": "Make it easier",
		"end.harder": "Try harder",
		"vote.title": "Banishing",
		"vote.bell_you": "Emergency meeting: you rang the bell.",
		"vote.bell": "Emergency meeting: {who} rang the bell.",
		"vote.ask": "Who do we drive out of the village? The banished leave for good. What they were, you'll learn at the end.",
		"day.diary": "Diary",
		"vote.headman": "You're the Headman: your vote counts twice.",
		"vote.dead": "You're dead and can only watch.",
		"vote.watch": "See the result",
		"vote.go": "Banish",
		"vote.none": "Nobody was banished",
		"vote.gone": "{who} is gone",
		"vote.gone_you": "You were banished",
		"vote.row": "{who}: {n}",
		"vote.night": "Night falls",
		"mo.title": "Morning",
		"mo.all_alive": "Everyone made it",
		"mo.one_dead": "One is missing",
		"mo.dead_n": "Missing: {n}",
		"mo.why": "Why you died",
		"mo.event": "Tonight: {e}.",
		"mo.street_dead": "{who.cap} {who:was|was|were} turned away from {house}. {who:Found dead in the street.|Found dead in the street.|You died in the street.}",
		"mo.alone_dead": "{who.cap} {who:was|was|were} alone in {house.in}. The charm went out.",
		"mo.killed": "{who.cap} died in {house.in}. Nearby: {others}.",
		"mo.street_ok": "{who.cap} spent the night outside. And came back.",
		"mo.alone_ok": "{who.cap} {who:was|was|were} alone in {house.in} and {who:is|is|are} unharmed.",
		"mo.clean": "{list} slept in {house.in}. Everyone is fine.",
		"mo.liar": "{who.cap} said {said}, but slept in {house.in}.",
		"mo.creature": "The charm at {house.in} was broken. The thing from the forest took {who}.",
		"mo.talisman_cracked": "The charm at {house.in} cracked. You can fix it in the day.",
		"mo.talisman_broken": "The charm at {house.in} broke. You can fix it in the day.",
		"mo.saved_upyr": "In {house.in}, one of our own attacked {who}, but {healer} nursed {who:him|her|you} back.",
		"mo.saved_creature": "In {house.in}, the thing from the forest attacked {who}, but {healer} nursed {who:him|her|you} back.",
		"mo.saved_mimic": "In {house.in}, the Mimic attacked {who}, but {healer} nursed {who:him|her|you} back.",
		"mo.tunnel": "{who.cap} {who:was|was|were} turned away from {from} and crawled through the tunnel into {house.in}.",
		"mo.mimic_kill": "{house.in.cap} let in {voice.pos} voice. It wasn't {voice}: the Mimic took {who}.",
		"mo.mimic_spared": "{house.in.cap} let in {voice.pos} voice. It wasn't {voice}, but everyone lived till morning.",
		"mo.mimic_knock": "At night someone knocked at {house.in} in {voice.pos} voice. Nobody opened. It was the Mimic.",
		"mo.mimic_knock_away": "At night someone knocked at {house.in} in {voice.pos} voice. Nobody opened. And {voice} was in {away.in} at the time.",
		"list.sep": ", ",
		"night.dusk": "Dusk. The bell is ringing.",
		"night.dead": "You're gone. The night goes on without you.",
		"night.bell": "The bell is ringing! Run home: tap a house.",
		"night.going": "going: {list}",
		"night.pact": "deal with {who}",
		"night.tunnel": "tunnel to {house.in}",
		"night.tal_broken": "charm broken",
		"night.tal_cracked": "charm cracked",
		"night.rule": "Whoever reaches the door first is inside and decides who gets in. Don't pick a house while the bell rings, and you'll run where you said you'd go, last.",
		"night.heal": "Take herbs: I'll save a neighbour tonight",
		"night.hint": "The bell doesn't ring for long. Tap a house on the square or in the list and run. Whoever is first at the door decides who gets in.",
		"night.heal_on": "Herbs ready: if someone near you is attacked, you'll nurse them back",
		"night.first": "You'll be first: you decide who gets in.",
		"night.ahead": "At the door before you: {list}. {who} will decide.",
		"night.run": "Running to {house.in}. {rest}",
		"door.title": "At the door",
		"door.hint_host": "Let in someone you trust. Open for nobody and you're alone, and alone you won't survive.",
		"door.hint_guest": "Choose what to say through the door. The host remembers whether you've slept together before.",
		"door.hint_alone": "You can't survive here alone. Next time, ask someone to come with you in the day.",
		"door.host": "You reached {house.in} first. Someone is knocking.",
		"door.cap": "You can let in: {n}",
		"door.quote": "\"{text}\"",
		"door.admit": "Let in",
		"door.admitting": "Letting in",
		"door.elsewhere": "At other doors: {list}.",
		"door.upyr_note": "Whoever you let in won't live till morning.",
		"door.alone_note": "Open for nobody and you're alone, and the charm will go out.",
		"door.open": "Open the door",
		"door.refuse": "Don't open for anyone",
		"door.locked": "{house.in.cap} is already locked from inside. {who} is in there.",
		"door.rivals": "At the door with you: {list}. There's not enough room for everyone.",
		"door.mimic": "In the dark behind you, someone speaks in {voice.pos} voice. But {voice} isn't here.",
		"door.say": "What will you say through the door?",
		"door.knock": "You knock on the door of {house.in}…",
		"door.let_in": "The bolt clicks. {who} lets you in.",
		"door.shut": "Footsteps move away from the door. You stay outside.",
		"door.hatch": "There's a hatch behind the house. The tunnel leads to {house.in}, and there's room. Whoever crawls through is inside, but in the morning everyone will know where they came from.",
		"door.tunnel": "Crawl through to {house.in}",
		"door.wait": "Wait for dawn",
		"door.alone": "You reached {house.in} first. Nobody else came.",
		"door.alone_upyr": "A lone vampire has nothing to fear outside.",
		"door.alone_human": "The charm flickers. Alone, you can't hold it till morning.",
		"day.journal": "Log",
		"day.journal_n": "Log ({n})",
		"day.dead": "You're gone. You can only watch.",
		"day.skip": "Skip the day",
		"day.defend": "Defend yourself",
		"day.invite": "Invite…",
		"day.accuse": "Accuse…",
		"day.say": "Say…",
		"day.bell": "Meeting!",
		"day.ready": "Ready for night",
		"day.hint": "Tap a villager: accuse them, invite them along or ask where they're sleeping. Tap a job icon: supplies light the lamps at night.",
		"day.bell_ask": "Ring the bell? Everyone gathers to vote right away. You can do this once a game.",
		"day.bell_do": "Ring the bell",
		"day.preview": "{who}: {text}",
		"day.say_aloud": "Say out loud",
		"day.person_ev": "{who} · {ev}",
		"day.p_accuse": "Accuse: \"It's {who}\"",
		"day.p_invite": "Invite for the night",
		"day.p_ask": "Ask where they're sleeping",
		"day.p_elder": "Read the Elder's drawings: what is {who:he|she}?",
		"day.work": "Work: {job.low}",
		"day.spoil": "Spoil what's done {place}",
		"day.who_accuse": "Accuse whom?",
		"day.who_invite": "Invite whom?",
		"day.where_with": "Where are you going with {who}?",
	}
