extends Gram
## Español (México y Latinoamérica). Un pueblo de leyendas: don Alonso con su lanza y Sancho,
## la Catrina de sombrero con flores, la Adelita con trenzas, un luchador enmascarado y el jaguar Balam.
## El monstruo es el vampiro. {who.a} da «a Rosa» (a personal).


func code() -> String:
	return "es"


func name_case(name: String, case: String, _female: bool) -> String:
	if case == "a":
		return "a " + name
	return name


func data() -> Dictionary:
	return {
		"and": " y ",
		"you": {"nom": "tú", "acc": "ti", "gen": "ti", "dat": "ti", "ins": "ti", "a": "a ti"},
		"you_name": "Tú",
		"someone": {"nom": "alguien más", "acc": "alguien más", "gen": "alguien más", "dat": "alguien más", "a": "a alguien más"},
		## nom — letrero y listas; in — «en el granero»; to — «al granero»; of — «del granero»; the — «el granero».
		"houses": [
			{"nom": "Casa del río", "f": true, "in": "en la Casa del río", "to": "a la Casa del río", "of": "de la Casa del río", "the": "la Casa del río"},
			{"nom": "Granero", "in": "en el granero", "to": "al granero", "of": "del granero", "the": "el granero"},
			{"nom": "Capilla", "f": true, "in": "en la capilla", "to": "a la capilla", "of": "de la capilla", "the": "la capilla"},
			{"nom": "Sótano", "in": "en el sótano", "to": "al sótano", "of": "del sótano", "the": "el sótano"},
			{"nom": "Garaje", "in": "en el garaje", "to": "al garaje", "of": "del garaje", "the": "el garaje"},
		],
		"names": [
			["Catrina", true], ["Alonso", false], ["Adelita", true], ["Sancho", false], ["Dulcinea", true], ["Pancho", false],
			["Diego", false], ["Lupita", true], ["Rayo", false], ["Rosa", true], ["Balam", false], ["Carmen", true],
		],
		"looks": "res://config/looks_es.tres",
		"ph.ANNOUNCE": [
			"Hoy duermo {house.in}.",
			"Voy {house.to}. ¿Quién viene conmigo?",
			"Me quedo {house.in}, por si acaso.",
			"{house.nom}. Decidido.",
		],
		"ph.ACCUSE_STRONG": [
			"{who}, explica cómo llegaste viv{who:o|a} a la mañana.",
			"Para mí está clarísimo. {who}.",
			"{who} estaba justo ahí cuando pasó todo. ¿Coincidencia?",
			"Voto por {who}. Sin dudar.",
		],
		"ph.ACCUSE_STREET": [
			"{who} pasó la noche afuera y regresó. La gente no puede hacer eso.",
			"{who}, estuviste afuera toda la noche. ¿No tienes nada que decir?",
		],
		"ph.ACCUSE_LIAR": [
			"{who} dijo que iba {house.to} y durmió en otro lado. ¿Para qué mentir?",
			"{who}, ibas a otro lado. ¿Qué cambió?",
		],
		"ph.DEFEND": [
			"Sí, estuve ahí. ¿Y qué?",
			"No soy vampiro. Compruébenlo esta noche.",
			"Nomás me tocó el cuarto equivocado.",
			"Si me corren ahorita, mañana van a faltar dos más.",
		],
		"ph.UPYR_DEFLECT": [
			"Yo en su lugar vigilaría a {who}.",
			"Ustedes discuten y ya viene la noche.",
			"No nos apresuremos. Si nos equivocamos, perdemos a uno de los nuestros.",
			"{who}, ¿por qué siempre te quedas callad{who:o|a}?",
			"Ayer me quedé quiet[o|a] y sobreviví. O sea que lo hice bien.",
		],
		"ph.FILLER": [
			"Cada vez somos menos. Cuenten.",
			"Decidamos rápido, ya está oscureciendo.",
			"No confío en nadie. En nadie.",
			"Alguien aquí está mintiendo ahorita.",
		],
		"ph.REPLY_TO_ACCUSED_HUMAN": [
			"¿Yo? ¿En serio? Mejor mira a {who}.",
			"Me estás confundiendo con alguien.",
			"Está bien. Córranme. Mañana van a entender.",
		],
		"ph.REPLY_TO_ACCUSED_UPYR": [
			"Qué gracioso. Mejor hablemos de ti.",
			"Así se hunde a los propios. Qué conveniente.",
			"Tienes mucha prisa por correrme. Sospechoso.",
		],
		"ph.AGREE_ACCUSE": [
			"De acuerdo. {who} tampoco me late.",
			"Apoyo. {who}.",
		],
		"ph.DISAGREE_ACCUSE": [
			"No, {who} se ve buena gente. ¿Qué te pasa?",
			"Muy flojo. ¿Dónde están las pruebas?",
		],
		"ph.INVITE_YES": [
			"Va. Nos vemos {house.in}.",
			"Bueno, voy contigo {house.to}.",
			"Está bien. Nomás no me falles.",
		],
		"ph.INVITE_NO": [
			"No, contigo no voy. Sin ofender.",
			"Todavía no confío en ti.",
			"Ya tengo con quién.",
		],
		"ph.ASK_ANSWER_HUMAN": [
			"Estoy {house.in}. No es secreto.",
			"Ya lo dije: {house.the}.",
		],
		"ph.ASK_ANSWER_UNSURE": [
			"Todavía no decido.",
			"A ver quién va a dónde.",
		],
		"ph.PLAYER_DEFEND_REACTION": [
			"Ajá.",
			"Ya veremos.",
			"Eso dicen todos.",
			"Bueno, te creo. Por ahora.",
		],
		"ph.GENERIC_REACTION": [
			"¿Y eso qué quiere decir?",
			"Muy bonito. Demasiado bonito.",
			"¿Te lo cuentas a ti o a nosotros?",
			"Te oigo. No me convence.",
		],
		"ph.AT_PLAYER": [
			"A ti es a quien tengo más preguntas.",
			"Estás demasiado tranquilo.",
			"Algo escondes.",
			"Mejor mírate a ti.",
			"No confío en ti. Para nada.",
		],
		"ph.PLEA_AFTER_STREET": [
			"Ayer ya no me dejaron entrar. Una segunda vez no la aguanto.",
			"Pasé toda la noche afuera. Ábreme.",
		],
		"ph.PLEA_SUSPECT": [
			"Sé cómo se ve. Pero no soy vampiro.",
			"Créeme una vez. Luego me corres si quieres.",
		],
		"ph.PLEA_NORMAL": [
			"Ábreme, hace frío.",
			"Soy yo. Déjame entrar.",
			"Entre los dos llegamos a la mañana.",
			"Apúrate, algo anda allá afuera.",
		],
		"ph.PLEA_PACT": [
			"Soy yo, teníamos un trato.",
			"Ábreme, como quedamos.",
		],
		"ph.JOB_FAKE": [
			"{who} estuvo parad{who:o|a} {place} y nada.",
			"Yo vi a {who} dando vueltas {place} sin hacer nada.",
			"Qué raro. {who} anduvo {place}, pero las provisiones no subieron.",
			"{who} nomás hace como que trabaja. Estuvo {place}: nada.",
			"¿Qué hacía {who} {place}? Las cubetas siguen vacías.",
		],
		"ph.JOB_FAKE_AT_PLAYER": [
			"Estás perdiendo el tiempo {place}. Las provisiones no subieron.",
			"Haces como que trabajas {place}. Te vi.",
			"¿De qué sirves {place}? Las cubetas siguen vacías.",
		],
		"ph.MIMIC_PLEAS": [
			"Déjame entrar. Soy yo. Soy yo, {who}. Déjame entrar.",
			"Ábreme, por favor. Por favor. Hace frío. Frío.",
			"Tú me conoces. Abre la puerta. Abre la puerta.",
			"Ya llegué a casa. Déjame entrar a casa.",
		],
		"ph.SABOTAGE_SEEN": [
			"{who} andaba rondando {place}, y ahora todo está echado a perder.",
			"Vi a {who} haciendo algo {place}. Fue {who:él|ella}.",
			"¿Quién arruina las provisiones? {who} fue {who:el último|la última} {place}.",
		],
		"ph.SABOTAGE_SEEN_AT_PLAYER": [
			"¿Qué haces {place}? Te vi: después de ti todo quedó arruinado.",
			"Después de ti, todo quedó arruinado {place}. Yo lo vi.",
		],
		"ph.ELDER_UPYR": [
			"Soy [el Anciano|la Anciana]. Vi los dibujos: {who} es vampiro.",
			"Escuchen. Soy [el Anciano|la Anciana], y en los dibujos {who} no es human{who:o|a}.",
		],
		"ph.ELDER_HUMAN": [
			"Soy [el Anciano|la Anciana]. {who} es human{who:o|a}, lo comprobé.",
			"Según los dibujos, {who} está limpi{who:o|a}. Soy [el Anciano|la Anciana], créanme.",
		],
		"ph.MEETING_CALL": [
			"Basta de plática. Votamos ya: {who}.",
			"Toco la campana. {who} miente, decidimos antes de que oscurezca.",
			"Júntense. No voy a dormir junto a {who}.",
		],
		"ph.BOX_NOTE": [
			"En la caja hay una nota: «{a} o {b}». Uno de los dos es vampiro.",
			"Abrí la caja. Adentro una nota: «{a} o {b}. Uno de los dos no es humano».",
		],
		"ph.BOX_OIL": [
			"En la caja hay aceite para faroles. Esta noche habrá más luz.",
			"Abrí la caja: aceite. Llenamos los faroles.",
		],
		"ph.BOX_CHALK": [
			"En la caja hay gis. Volví a pintar el amuleto {house.of}.",
		],
		"plea.shared.label": "Ya dormimos juntos antes",
		"plea.shared.text": "Ya pasamos una noche juntos y no pasó nada.",
		"plea.promise.label": "Prometer abrir mañana",
		"plea.promise.text": "Déjame entrar. Mañana yo te abro primero.",
		"plea.name.label": "Nombrar al vampiro",
		"plea.name.text": "Sé quién es. Déjame entrar y te digo.",
		"plea.beg.label": "Rogar",
		"plea.beg.text": "Por favor. Aquí afuera no se sobrevive.",
		"spoil.water": "las cubetas están volteadas",
		"spoil.wood": "la leña está tirada en el lodo",
		"spoil.lamp": "el aceite está derramado",
		"spoil.fish": "la pesca fue devuelta al río",
		"spoil.any": "todo está arruinado",
		"quick.house": "Duermo {house.in}. ¿Quién viene conmigo?",
		"quick": ["No soy vampiro. Lo juro.", "El que regresó de afuera es el vampiro.", "Quedémonos en parejas.", "El que mienta sobre dónde duerme, fuera."],
		"intent.accuse": ["vampir", "fue él", "fue ella", "es él", "es ella", "miente", "mentir", "sospech", "no confío", "fuera", "asesin", "culpable"],
		"intent.invite": ["vamos", "conmigo", "juntos", "juntas", "vente", "ven a"],
		"intent.defend": ["no soy", "yo no", "humano", "lo juro", "inocente", "créanme"],
		"intent.ask": ["dónde", "donde", "adónde", "qué casa"],
		"intent.houses": ["río", "granero", "capilla", "sótano", "garaje"],
		"ev.street": "regresó viv{who:o|a|o} de afuera",
		"ev.times": " ({n} veces)",
		"ev.liar": "mintió sobre dónde dormía",
		"ev.death": "estaba cerca cuando alguien murió",
		"ev.fake": "trabajó para nada",
		"ev.sabotage": "estaba junto a un trabajo arruinado",
		"ev.tunnel": "se metió por el túnel a otra casa",
		"ev.sep": "; ",
		"sys.sabotage": "Alguien hizo destrozos {place}: {what}. Las provisiones bajaron.",
		"claim.elder_upyr": "dijo ser {me:el Anciano|la Anciana}: {who} es vampiro",
		"claim.elder_human": "dijo ser {me:el Anciano|la Anciana}: {who} es human{who:o|a|o}",
		"claim.healer": "{role}: curó a {who} la noche {n}",
		"when.night": "Noche {n}",
		"when.day": "Día {n}",
		"chron.line": "{title}: {text}",
		"chron.morning": "En la mañana: {text}",
		"log.exiled": "el pueblo desterró {who.a}.",
		"log.supplies": "provisiones juntadas: {p}%.",
		"log.tunnel": "{who.cap} {who:se quedó|se quedó|te quedaste} afuera {from.of} y {who:se metió|se metió|te metiste} por el túnel {house.to}.",
		"log.street_upyr": "{who.cap} {who:se quedó|se quedó|te quedaste} afuera {house.of}, pero {who:sobrevivió|sobrevivió|sobreviviste} hasta la mañana.",
		"log.street_dead": "{who.cap} {who:se quedó|se quedó|te quedaste} afuera {house.of}. {who:En la mañana lo encontraron en la calle.|En la mañana la encontraron en la calle.|Moriste en la calle.}",
		"log.street_ok": "{who.cap} {who:pasó|pasó|pasaste} la noche afuera y {who:sobrevivió|sobrevivió|sobreviviste}.",
		"log.mimic_knock": "tocaron a la puerta {house.of} con la voz de {voice}. Nadie abrió.",
		"log.mimic_spared": "{house.in} dejaron entrar la voz de {voice}. No era {voice}, pero todos llegaron a la mañana.",
		"log.mimic_kill": "{house.in} dejaron entrar la voz de {voice}. Era el Imitador: se llevó {who.a}.",
		"log.alone_dead": "{who.cap} {who:se quedó solo|se quedó sola|te quedaste solo} {house.in}. El amuleto se apagó.",
		"log.killed": "{who.cap} {who:murió|murió|moriste} {house.in}. Cerca: {others}.",
		"log.clean": "{house.in} durmieron {list}. Todos bien.",
		"log.creature": "el amuleto {house.of} estaba roto. La cosa del monte se llevó {who.a}.",
		"log.liar": "{who.cap} {who:dijo|dijo|dijiste} que iba {said.to}, pero {who:durmió|durmió|dormiste} {house.in}.",
		"log.talisman_cracked": "el amuleto {house.of} se agrietó.",
		"log.talisman_broken": "el amuleto {house.of} se rompió.",
		"log.saved": "{house.in} atacaron {who.a}, pero {healer} {h:lo curó|lo curó|lo curaste}.",
		"log.meeting": "{who.cap} {who:tocó|tocó|tocaste} la campana: junta de emergencia.",
		"log.event": "{e}.",
		"sys.dawn1": "Amanece. Todos salen a la plaza.",
		"sys.dawn": "Día {d}. Siguen vivos: {n}.",
		"job.water.title": "Acarrear agua",
		"job.water.place": "en el pozo",
		"job.water.done": "Agua hasta la mañana.",
		"job.wood.title": "Partir leña",
		"job.wood.place": "en la leñera",
		"job.wood.done": "Leña para toda la noche.",
		"job.lamp.title": "Llenar los faroles",
		"job.lamp.place": "junto al farol",
		"job.lamp.done": "Los faroles están llenos.",
		"job.fish.title": "Pescar",
		"job.fish.place": "en el río",
		"job.fish.done": "Hay pescado para la cena.",
		"job.talisman.title": "Arreglar el amuleto",
		"job.talisman.place": "junto al amuleto",
		"job.talisman.done": "El amuleto quedó como nuevo.",
		"job.box.title": "Abrir la caja",
		"job.box.place": "junto a la caja",
		"role.elder": "{who:Anciano|Anciana|Anciano}",
		"role.elder.mid": "{who:el anciano|la anciana|el anciano}",
		"role.healer": "{who:Curandero|Curandera|Curandero}",
		"role.healer.mid": "{who:el curandero|la curandera|el curandero}",
		"role.headman": "{who:Alcalde|Alcaldesa|Alcalde}",
		"role.headman.mid": "{who:el alcalde|la alcaldesa|el alcalde}",
		"role.named": "{role} {who}",
		"event.fog.title": "Neblina",
		"event.fog.mid": "neblina",
		"event.fog.text": "La neblina apaga la campana: menos tiempo para correr, la calle es más peligrosa.",
		"event.moon.title": "Luna llena",
		"event.moon.mid": "luna llena",
		"event.moon.text": "Luna llena: para la mañana todos los amuletos se debilitan.",
		"event.quiet.title": "Noche tranquila",
		"event.quiet.mid": "noche tranquila",
		"event.quiet.text": "Noche tranquila: la calle es más segura, el Imitador no vendrá.",
		"event.rain.title": "Aguacero",
		"event.rain.mid": "aguacero",
		"event.rain.text": "El aguacero ahoga los faroles: el aceite guardado no sirve esta noche.",
		"recap.street_host": "No te dejaron entrar {house.to}: {who} cuidaba la puerta.",
		"recap.street": "Pasaste la noche afuera. Ahí casi nadie sobrevive.",
		"recap.street_p": "Probabilidad de morir afuera esa noche: {p}%.",
		"recap.killer": "Te mató {who}. Era vampir{who:o|a}.",
		"recap.you_opened": "Tú mismo le abriste la puerta {who.a}.",
		"recap.killer_opened": "{who} te abrió la puerta {who:él mismo|ella misma}.",
		"recap.near": "Cerca: {others}.",
		"recap.alone": "Te quedaste solo {house.in}. Una sola persona no sostiene el amuleto hasta la mañana.",
		"recap.alone_p": "Probabilidad de morir solo en esa casa: {p}%. De día, pídele a alguien que vaya contigo.",
		"recap.creature": "El amuleto {house.of} estaba roto, y la cosa del monte entró.",
		"recap.creature_tip": "De día se podía arreglar el amuleto: es un trabajo de la plaza.",
		"recap.mimic_you": "Le abriste la puerta a la voz de {voice}. Era el Imitador.",
		"recap.mimic_host": "{who} dejó entrar la voz de {voice}. Era el Imitador.",
		"recap.voice_dead": "Para entonces {voice} ya había muerto.",
		"recap.voice_away": "Y {voice} estaba {house.in} a esa hora.",
		"recap.exiled": "Te desterraron el día {d}. En tu contra: {list}.",
		"recap.exiled_many": "Te desterraron el día {d}. En tu contra: la mayoría.",
		"recap.seen": "El pueblo vio: {ev}.",
		"recap.exiled0": "Te desterraron.",
		"recap.died": "Moriste la noche {n}. {why}",
		"verdict.mimic": "La noche {n} le abriste al Imitador, con la voz de {voice}.",
		"verdict.let_upyr": "La noche {n} dejaste entrar {who.a}, y era vampir{who:o|a}.",
		"verdict.vote_upyr": "El día {n} tu voto ayudó a desterrar a un vampiro: {who}.",
		"verdict.vote_human": "El día {n} votaste contra {who}, y era human{who:o|a}.",
		"verdict.clean": "Nunca le abriste la puerta a un vampiro y llegaste al amanecer.",
		"verdict.dead": "No llegaste al amanecer.",
		"verdict.kills": " En tu cuenta: {n}.",
		"verdict.upyr_won": "El pueblo nunca se dio cuenta de que el vampiro eras tú.",
		"verdict.upyr_lost": "Llegaste al amanecer, pero el pueblo aguantó.",
		"sys.box": "En la orilla de la plaza hay una caja. Ayer no estaba.",
		"sys.elder_upyr": "Los dibujos del Anciano: {who} es vampiro. Solo tú lo sabes.",
		"sys.elder_human": "Los dibujos del Anciano: {who} es human{who:o|a}. Solo tú lo sabes.",
		"sys.bell_you": "Tocas la campana. ¡Junta de emergencia!",
		"sys.bell": "{who} toca la campana. ¡Junta de emergencia!",
		"box.note": "En la caja hay una nota: «{a.cap} o {b}». Uno de los dos es vampiro. Solo tú ves la nota.",
		"box.oil": "En la caja hay aceite para faroles: provisiones +{n}.",
		"box.chalk": "En la caja hay gis: el amuleto {house.of} quedó repintado.",
		"box.empty": "La caja está vacía.",
		"say.accuse": "Creo que es {who}.",
		"say.invite": "{who}, ¿vamos juntos {house.to}?",
		"say.ask": "{who}, ¿dónde duermes hoy?",
		"say.defend": ["No soy vampiro. Lo juro.", "Soy de los suyos. Compruébenlo esta noche.", "No fui yo. Sigan buscando."],
		"toast.elder_upyr": "Dibujos: {who} es vampiro",
		"toast.elder_human": "Dibujos: {who} es human{who:o|a}",
		"toast.box_taken": "La caja ya la abrieron",
		"toast.job_done": "«{job}»: listo por hoy",
		"toast.box": "Apareció una caja en la plaza",
		"toast.back_exit": "Presiona otra vez para salir",
		"quit.ask": "¿Abandonar la partida?",
		"quit.stay": "Quedarme",
		"quit.leave": "Salir al menú",
		"cfg.players": "Jugadores",
		"cfg.monsters": "Vampiros",
		"cfg.shelters": "Refugios",
		"cfg.capacity": "Lugares por refugio",
		"cfg.nights": "Noches hasta el amanecer",
		"cfg.day_seconds": "Día, segundos",
		"cfg.door_seconds": "Decisión en la puerta, segundos",
		"cfg.run_seconds": "Carrera a casa, segundos",
		"cfg.outside_death": "Muerte afuera, %",
		"cfg.first_night_outside_death": "Lo mismo la primera noche, %",
		"cfg.vote_from_day": "Destierro desde el día",
		"diff.easy": "Fácil",
		"diff.normal": "Normal",
		"diff.hard": "Difícil",
		"diff.custom": "Propia",
		"diff.cast": "{p} {p#habitante|habitantes}, {u} {u#vampiro|vampiros}.",
		"diff.human": " Siempre eres humano.",
		"diff.easy_note": " Día más largo.",
		"diff.hard_note": " Día más corto, calle más peligrosa.",
		"diary.exiled": "{who:Desterrado|Desterrada|Desterrado} el día {n}.",
		"diary.died": "{who:Muerto|Muerta|Muerto} la noche {n}.",
		"diary.night": "{n}: {where}",
		"diary.street": "afuera",
		"diary.said": " (dijo: {house})",
		"diary.nights": "Noches: {list}.",
		"diary.today": "Hoy va a: {house}.",
		"diary.evidence": "Pistas: {ev}.",
		"diary.own_claim": "{text}.",
		"diary.claim": "{who.cap} {text}.",
		"diary.seen_upyr": "Tus dibujos: vampiro.",
		"diary.seen_human": "Tus dibujos: humano.",
		"diary.nothing": "Todavía no se sabe nada.",
		"diary.head": "Diario: lo que se sabe de cada quien",
		"diary.gone": "{who} · muert{who:o|a|o}",
		"journal.who": "{who}:",
		"journal.head": "Registro del día",
		"ui.close": "Cerrar",
		"ui.cancel": "Cancelar",
		"say.placeholder": "O escribe lo tuyo",
		"say.send": "Decir",
		"chip.exiled": " · desterrado",
		"supplies": "Provisiones {a} de {b}",
		"howto.art_accuse": "¡Tú eres el vampiro!",
		"howto.art_street": "‹ afuera",
		"howto.art_door": "¿Abrir?",
		"game.title": "Déjame entrar",
		"menu.tale": "De noche nadie sobrevive en la calle.\nHay menos refugios que gente.\n\nAlguien está en la puerta y ruega que lo dejen entrar. Alguien adentro decide.",
		"menu.hint": "Los vampiros están entre ustedes. Ni siquiera se conocen entre ellos.",
		"menu.howto": "Cómo jugar",
		"menu.play": "Jugar",
		"lang.pick": "Idioma",
		"diff.note": "{d}: {text}",
		"diff.note_custom": "Dificultad propia: {text}",
		"settings.title": "Ajustes",
		"settings.lang": "Idioma",
		"settings.sound": "Sonido",
		"settings.music": "Música",
		"settings.sfx": "Efectos",
		"settings.ambience": "Ambiente",
		"settings.haptics_on": "Vibración: activada",
		"settings.haptics_off": "Vibración: desactivada",
		"settings.difficulty": "Dificultad",
		"settings.hints": "Volver a mostrar consejos",
		"settings.hints_reset": "Los consejos volverán a salir",
		"settings.note": "Cada nivel se probó en 1500 partidas. Lo que más mueve el equilibrio es el número de refugios y de noches.",
		"settings.start": "Empezar con estos ajustes",
		"ui.back": "Atrás",
		"howto.day.title": "El día",
		"howto.day.text": "En el pueblo vive gente, y entre ella hay vampiros. Los vampiros se ven como todos. Tú eres un habitante con un farol.\n\nDe día todos están en la plaza. Toca a un habitante: acúsalo, invítalo a pasar la noche juntos o pregúntale dónde duerme. Un ojo rojo sobre la cabeza significa que el pueblo sospecha de él.\n\nToca el ícono de un trabajo: agua, leña, faroles. Mientras más provisiones, más luz de noche. Los vampiros fingen trabajar o hasta arruinan lo hecho. A veces aparece una caja en la plaza: quien la abre primero se queda con lo que hay dentro.",
		"howto.night.title": "La noche",
		"howto.night.text": "En la tarde suena la campana y todos corren a casa. Mientras suena, toca una casa. Hay menos refugios que gente: quien se quede afuera casi seguro no ve la mañana.\n\nQuedarse solo en una casa también es arriesgado. De día ponte de acuerdo con quién vas a pasar la noche y arregla el amuleto agrietado: a una casa con el amuleto roto entra la cosa del monte.",
		"howto.door.title": "La puerta",
		"howto.door.text": "El primero que llega a una casa decide quién entra.\n\nSi dejas entrar a un vampiro, no verás la mañana. Si no dejas entrar a nadie, te quedas solo. En la mañana revisa quién durmió dónde y quién mintió.\n\nA veces tocan con la voz de alguien que está en otra casa o que ya murió. Es el Imitador: no abras.\n\nAlgunos tienen un papel: Anciano, Curandero, Alcalde. Una vez por partida puedes tocar la campana de día y votar de inmediato. Todo lo que se sabe de cada quien está en el Diario.",
		"howto.title": "Cómo jugar · {a} de {b}",
		"howto.got_it": "Entendido",
		"ui.next": "Siguiente",
		"ui.skip": "Saltar",
		"crash.title": "Reporte",
		"crash.head": "La sesión anterior se cerró de golpe",
		"crash.text": "Es un error del juego, no tuyo. Toca «Copiar reporte» y mándanoslo: ahí se ve en qué paso se cortó todo.",
		"crash.steps": "Últimos pasos:",
		"crash.copy": "Copiar reporte",
		"crash.copied": "Copiado: pégalo en el chat",
		"ui.continue": "Continuar",
		"prologue.title": "Antes de la primera noche",
		"prologue.pre": "Tu papel…",
		"prologue.upyr": "Eres vampiro",
		"prologue.human": "Eres humano",
		"prologue.upyr_text": "No sabes quién más es como tú. La calle no te asusta, y quien quede contigo tras una misma puerta no verá la mañana. De día, habla como humano.",
		"prologue.human_text": "De noche en la calle casi seguro mueres. En un refugio no puedes quedarte solo: el amuleto se apaga. Necesitas a alguien, y no sabes quién de ellos es humano.",
		"prologue.facts": "{p} habitantes, {u} {u#vampiro|vampiros}. {s} {s#refugio|refugios} de {c} lugares. Hay que llegar al amanecer número {n}.",
		"prologue.go": "Salir con la gente",
		"prologue.elder": "Eres el Anciano. Una vez por partida, de día, toca a un habitante y mira los dibujos: sabrás si es vampiro. Solo tú lo sabrás.",
		"prologue.healer": "Eres el Curandero. Una vez por partida, antes de la noche, toma tus hierbas: si atacan a alguien cerca de ti en la casa, lo curarás.",
		"prologue.headman": "Eres el Alcalde. En el destierro, tu voto vale doble.",
		"end.title": "Resumen",
		"end.people": "La gente resistió",
		"end.upyri": "El pueblo quedó vacío",
		"end.won": "Tu bando ganó.",
		"end.lost": "Tu bando perdió.",
		"end.who": "Quién era quién",
		"end.upyr": "vampiro",
		"end.human": "humano",
		"end.with_role": "{a}, {role}",
		"end.chip": "{who}: {what}",
		"end.how": "Cómo fue",
		"end.again": "Otra partida",
		"end.verdict": "Qué decidió la partida",
		"end.offer_easier": "¿Hacerlo más fácil?",
		"end.offer_harder": "Dos victorias seguidas. ¿Probar más difícil?",
		"end.easier": "Más fácil",
		"end.harder": "Más difícil",
		"vote.title": "Destierro",
		"vote.bell_you": "Junta de emergencia: tocaste la campana.",
		"vote.bell": "Junta de emergencia: {who} tocó la campana.",
		"vote.ask": "¿A quién corremos del pueblo? El desterrado se va para siempre. Lo que era, lo sabrán al final.",
		"day.diary": "Diario",
		"vote.headman": "Eres el Alcalde: tu voto vale doble.",
		"vote.dead": "Estás muerto y solo miras.",
		"vote.watch": "Ver el resultado",
		"vote.go": "Desterrar",
		"vote.none": "No desterraron a nadie",
		"vote.gone": "Se fue {who}",
		"vote.gone_you": "Te desterraron",
		"vote.row": "{who}: {n}",
		"vote.night": "Cae la noche",
		"mo.title": "Mañana",
		"mo.all_alive": "Todos sobrevivieron",
		"mo.one_dead": "Falta uno",
		"mo.dead_n": "Faltan: {n}",
		"mo.why": "Por qué moriste",
		"mo.event": "Esta noche: {e}.",
		"mo.street_dead": "{who.cap} {who:se quedó|se quedó|te quedaste} afuera {house.of}. {who:Lo encontraron en la calle.|La encontraron en la calle.|Moriste en la calle.}",
		"mo.alone_dead": "{who.cap} {who:se quedó solo|se quedó sola|te quedaste solo} {house.in}. El amuleto se apagó.",
		"mo.killed": "{who.cap} {who:murió|murió|moriste} {house.in}. Cerca: {others}.",
		"mo.street_ok": "{who.cap} {who:pasó|pasó|pasaste} la noche afuera. Y {who:regresó|regresó|regresaste}.",
		"mo.alone_ok": "{who.cap} {who:estuvo solo|estuvo sola|estuviste solo} {house.in} y {who:está bien|está bien|estás bien}.",
		"mo.clean": "{house.in.cap} durmieron {list}. Todos bien.",
		"mo.liar": "{who.cap} {who:dijo|dijo|dijiste} que iba {said.to}, pero {who:durmió|durmió|dormiste} {house.in}.",
		"mo.creature": "El amuleto {house.of} estaba roto. La cosa del monte se llevó {who.a}.",
		"mo.talisman_cracked": "El amuleto {house.of} se agrietó. De día se puede arreglar.",
		"mo.talisman_broken": "El amuleto {house.of} se rompió. De día se puede arreglar.",
		"mo.saved_upyr": "{house.in.cap} uno de los nuestros atacó {who.a}, pero {healer} {h:lo curó|lo curó|lo curaste}.",
		"mo.saved_creature": "{house.in.cap} la cosa del monte atacó {who.a}, pero {healer} {h:lo curó|lo curó|lo curaste}.",
		"mo.saved_mimic": "{house.in.cap} el Imitador atacó {who.a}, pero {healer} {h:lo curó|lo curó|lo curaste}.",
		"mo.tunnel": "{who.cap} {who:se quedó|se quedó|te quedaste} afuera {from.of} y {who:se metió|se metió|te metiste} por el túnel {house.to}.",
		"mo.mimic_kill": "{house.in.cap} dejaron entrar la voz de {voice}. No era {voice}: el Imitador se llevó {who.a}.",
		"mo.mimic_spared": "{house.in.cap} dejaron entrar la voz de {voice}. No era {voice}, pero todos llegaron a la mañana.",
		"mo.mimic_knock": "En la noche tocaron a la puerta {house.of} con la voz de {voice}. Nadie abrió. Era el Imitador.",
		"mo.mimic_knock_away": "En la noche tocaron a la puerta {house.of} con la voz de {voice}. Nadie abrió. Y {voice} estaba {away.in} a esa hora.",
		"list.sep": ", ",
		"night.dusk": "Oscurece. Suena la campana.",
		"night.dead": "Ya no estás. La noche sigue sin ti.",
		"night.bell": "¡Suena la campana! Corre a una casa: tócala.",
		"night.going": "iban: {list}",
		"night.pact": "trato con {who}",
		"night.tunnel": "túnel {house.to}",
		"night.tal_broken": "amuleto roto",
		"night.tal_cracked": "amuleto agrietado",
		"night.rule": "El primero en llegar a la puerta queda adentro y decide quién entra. Si no eliges casa mientras suena, correrás al último a donde dijiste.",
		"night.heal": "Tomar hierbas: esta noche salvo a un vecino",
		"night.hint": "La campana suena poco. Toca una casa en la plaza o en la lista y corre. El primero en la puerta decide quién entra.",
		"night.heal_on": "Hierbas listas: si atacan a alguien cerca de ti, lo curas",
		"night.first": "Llegarás primero: tú decides quién entra.",
		"night.ahead": "Antes que tú en la puerta: {list}. Decidirá {who}.",
		"night.run": "Corres {house.to}. {rest}",
		"door.title": "En la puerta",
		"door.hint_host": "Deja entrar a quien le tengas confianza. Si no le abres a nadie, te quedas solo, y solo no se sobrevive.",
		"door.hint_guest": "Elige qué decir a través de la puerta. El de adentro recuerda si ya durmieron juntos.",
		"door.hint_alone": "Aquí solo no se sobrevive. La próxima vez, de día, pídele a alguien que venga contigo.",
		"door.host": "Llegaste primero {house.to}. Tocan a la puerta.",
		"door.cap": "Puedes dejar entrar a: {n}",
		"door.quote": "«{text}»",
		"door.admit": "Dejar entrar",
		"door.admitting": "Entra",
		"door.elsewhere": "En otras puertas: {list}.",
		"door.upyr_note": "A quien dejes entrar no verá la mañana.",
		"door.alone_note": "Si no le abres a nadie, te quedas solo y el amuleto se apagará.",
		"door.open": "Abrir la puerta",
		"door.refuse": "No abrirle a nadie",
		"door.locked": "{house.the.cap} ya está cerrad{house:o|a} por dentro. Adentro está {who}.",
		"door.rivals": "En la puerta contigo: {list}. No hay lugar para todos.",
		"door.mimic": "En la oscuridad, detrás de ti, alguien habla con la voz de {voice}. Pero {voice} no está aquí.",
		"door.say": "¿Qué dices a través de la puerta?",
		"door.knock": "Tocas a la puerta {house.of}…",
		"door.let_in": "Suena el cerrojo. {who} te deja entrar.",
		"door.shut": "Los pasos se alejan de la puerta. Te quedas afuera.",
		"door.hatch": "Detrás de la casa hay una trampilla. El túnel lleva {house.to}, y hay lugar. Quien pase queda adentro, pero en la mañana todos sabrán de dónde salió.",
		"door.tunnel": "Meterse por el túnel {house.to}",
		"door.wait": "Esperar el amanecer",
		"door.alone": "Llegaste primero {house.to}. Nadie más vino.",
		"door.alone_upyr": "A un vampiro solo la calle no le da miedo.",
		"door.alone_human": "El amuleto parpadea. Solo no lo vas a sostener hasta la mañana.",
		"day.journal": "Registro",
		"day.journal_n": "Registro ({n})",
		"day.dead": "Ya no estás. Solo miras.",
		"day.skip": "Saltar el día",
		"day.defend": "Defenderse",
		"day.invite": "Invitar…",
		"day.accuse": "Acusar…",
		"day.say": "Decir…",
		"day.bell": "¡Junta!",
		"day.ready": "Listo para la noche",
		"day.hint": "Toca a un habitante: acúsalo, invítalo o pregúntale dónde duerme. Toca el ícono de un trabajo: las provisiones prenden los faroles de noche.",
		"day.bell_ask": "¿Tocar la campana? Todos se juntan a votar de inmediato. Solo una vez por partida.",
		"day.bell_do": "Tocar la campana",
		"day.preview": "{who}: {text}",
		"day.say_aloud": "Decir en voz alta",
		"day.person_ev": "{who} · {ev}",
		"day.p_accuse": "Acusar: «Es {who}»",
		"day.p_invite": "Invitar para la noche",
		"day.p_ask": "Preguntar dónde duerme",
		"day.p_elder": "Ver los dibujos del Anciano: ¿qué es {who:él|ella}?",
		"day.work": "Trabajar: {job.low}",
		"day.spoil": "Arruinar lo hecho {place}",
		"day.who_accuse": "¿A quién acusar?",
		"day.who_invite": "¿A quién invitar?",
		"day.where_with": "¿A dónde vas con {who}?",
	}
