extends Gram
## Français. Un village de romans et de contes : Aramis le mousquetaire, Cyrano et son nez,
## Gavroche, Cosette, Marianne au bonnet rouge, le coq Coco et le chat Mistigri en bottes.
## Le monstre s'appelle ici loup-garou. {who.de} donne « de Cosette » ou « d'Aramis ».


func code() -> String:
	return "fr"


func _vowel(name: String) -> bool:
	return "aeiouyhàâéèêëîïôûAEIOUYHÀÂÉÈÊÎÔÛ".contains(name.left(1))


func name_case(name: String, case: String, _female: bool) -> String:
	match case:
		"de":
			return ("d'" if _vowel(name) else "de ") + name
		"a":
			return "à " + name
	return name


func plural_index(n: int) -> int:
	return 0 if absi(n) <= 1 else 1


func data() -> Dictionary:
	return {
		"and": " et ",
		"you": {"nom": "toi", "acc": "toi", "gen": "toi", "dat": "toi", "ins": "toi", "de": "de toi", "a": "à toi"},
		"you_name": "Toi",
		"someone": {"nom": "quelqu'un d'autre", "acc": "quelqu'un d'autre", "gen": "quelqu'un d'autre", "dat": "quelqu'un d'autre", "de": "de quelqu'un d'autre", "a": "à quelqu'un d'autre"},
		## nom — panneau et listes ; in — « dans la grange » ; to — « à la grange » ; of — « de la grange ».
		"houses": [
			{"nom": "Maison de la rivière", "f": true, "in": "dans la maison de la rivière", "to": "à la maison de la rivière", "of": "de la maison de la rivière", "the": "la maison de la rivière"},
			{"nom": "Grange", "f": true, "in": "dans la grange", "to": "à la grange", "of": "de la grange", "the": "la grange"},
			{"nom": "Chapelle", "f": true, "in": "dans la chapelle", "to": "à la chapelle", "of": "de la chapelle", "the": "la chapelle"},
			{"nom": "Cave", "f": true, "in": "dans la cave", "to": "à la cave", "of": "de la cave", "the": "la cave"},
			{"nom": "Garage", "in": "dans le garage", "to": "au garage", "of": "du garage", "the": "le garage"},
		],
		"names": [
			["Marianne", true], ["Aramis", false], ["Cosette", true], ["Gavroche", false], ["Colette", true], ["Cyrano", false],
			["Jean", false], ["Louise", true], ["Coco", false], ["Margot", true], ["Mistigri", false], ["Josette", true],
		],
		"looks": "res://config/looks_fr.tres",
		"ph.ANNOUNCE": [
			"Ce soir, je suis {house.in}.",
			"Je vais {house.to}. Qui vient avec moi ?",
			"Je dors {house.in}, au cas où.",
			"{house.nom}. C'est décidé.",
		],
		"ph.ACCUSE_STRONG": [
			"{who}, explique comment tu as survécu jusqu'au matin.",
			"Pour moi, c'est clair. {who}.",
			"{who} était juste à côté quand c'est arrivé. Une coïncidence ?",
			"Je vote contre {who}. Sans hésiter.",
		],
		"ph.ACCUSE_STREET": [
			"{who} a passé la nuit dehors et {who:il|elle} est revenu{|e}. Un humain n'en est pas capable.",
			"{who}, tu as passé toute la nuit dehors. Tu n'as rien à nous dire ?",
		],
		"ph.ACCUSE_LIAR": [
			"{who} parlait {house.of}, mais {who:il|elle} a dormi ailleurs. Pourquoi mentir ?",
			"{who}, tu devais aller ailleurs. Qu'est-ce qui a changé ?",
		],
		"ph.DEFEND": [
			"Oui, j'y étais. Et alors ?",
			"Je ne suis pas un loup-garou. Vérifiez cette nuit.",
			"J'ai juste choisi la mauvaise pièce.",
			"Chassez-moi maintenant, et demain il en manquera deux de plus.",
		],
		"ph.UPYR_DEFLECT": [
			"À votre place, je surveillerais {who}.",
			"Vous vous disputez, et la nuit approche.",
			"Ne nous précipitons pas. Si on se trompe, on perd l'un des nôtres.",
			"{who}, pourquoi tu ne dis jamais rien ?",
			"Hier, je me suis fait[|e] discret[|e] et j'ai survécu. Donc j'ai bien fait.",
		],
		"ph.FILLER": [
			"On est de moins en moins nombreux. Comptez.",
			"Décidons plus vite, il fait nuit.",
			"Je ne fais confiance à personne. À personne.",
			"L'un de vous ment en ce moment même.",
		],
		"ph.REPLY_TO_ACCUSED_HUMAN": [
			"Moi ? Sérieusement ? Regarde plutôt {who}.",
			"Tu me confonds avec quelqu'un.",
			"D'accord. Chassez-moi. Demain vous comprendrez.",
		],
		"ph.REPLY_TO_ACCUSED_UPYR": [
			"Amusant. Parlons plutôt de toi.",
			"C'est comme ça qu'on coule les siens. Pratique.",
			"Tu es bien pressé de me chasser. C'est louche.",
		],
		"ph.AGREE_ACCUSE": [
			"D'accord. {who} ne me plaît pas non plus.",
			"Je suis. {who}.",
		],
		"ph.DISAGREE_ACCUSE": [
			"Non, {who} a l'air correct{|e}. Qu'est-ce qui te prend ?",
			"Faible. Où sont les preuves ?",
		],
		"ph.INVITE_YES": [
			"D'accord. Rendez-vous {house.to}.",
			"Bon, je vais {house.to} avec toi.",
			"Entendu. Mais ne me laisse pas tomber.",
		],
		"ph.INVITE_NO": [
			"Non, je ne viens pas avec toi. Sans rancune.",
			"Je ne te fais pas encore confiance.",
			"J'ai déjà quelqu'un.",
		],
		"ph.ASK_ANSWER_HUMAN": [
			"Je suis {house.in}. Pas de secret.",
			"Je l'ai dit : {house.the}.",
		],
		"ph.ASK_ANSWER_UNSURE": [
			"Pas encore décidé.",
			"Je vais voir qui va où.",
		],
		"ph.PLAYER_DEFEND_REACTION": [
			"Mouais.",
			"On verra.",
			"Ils disent tous ça.",
			"Bon, je te crois. Pour l'instant.",
		],
		"ph.GENERIC_REACTION": [
			"Et tu veux dire quoi par là ?",
			"Bien tourné. Trop bien tourné.",
			"Tu racontes ça pour toi ou pour nous ?",
			"J'entends. Ça ne me convainc pas.",
		],
		"ph.AT_PLAYER": [
			"C'est à toi que j'ai le plus de questions.",
			"Tu es bien trop calme.",
			"Tu caches quelque chose.",
			"Regarde-toi plutôt.",
			"Je ne te fais pas confiance. Pas du tout.",
		],
		"ph.PLEA_AFTER_STREET": [
			"Hier déjà on ne m'a pas ouvert. Je ne survivrai pas une deuxième fois.",
			"J'ai passé toute la nuit dehors. Ouvre.",
		],
		"ph.PLEA_SUSPECT": [
			"Je sais de quoi ça a l'air. Mais je ne suis pas un loup-garou.",
			"Crois-moi une fois. Tu me chasseras après.",
		],
		"ph.PLEA_NORMAL": [
			"Ouvre, il fait froid.",
			"C'est moi. Laisse-moi entrer.",
			"À deux, on tiendra jusqu'au matin.",
			"Vite, quelque chose rôde dehors.",
		],
		"ph.PLEA_PACT": [
			"C'est moi, on avait un accord.",
			"Ouvre, comme convenu.",
		],
		"ph.JOB_FAKE": [
			"{who} traînait {place}, et rien n'en est sorti.",
			"J'ai vu {who} bricoler {place} sans rien faire.",
			"Bizarre. {who} est allé{|e} {place}, mais les provisions n'ont pas augmenté.",
			"{who} fait semblant de travailler. {who:Il|Elle} était {place} : rien.",
			"Qu'est-ce que {who} faisait {place} ? Les seaux sont toujours vides.",
		],
		"ph.JOB_FAKE_AT_PLAYER": [
			"Tu perds ton temps {place}. Les provisions n'ont pas augmenté.",
			"Tu fais semblant de travailler {place}. Je l'ai vu.",
			"À quoi tu sers {place} ? Les seaux sont toujours vides.",
		],
		"ph.MIMIC_PLEAS": [
			"Laisse-moi entrer. C'est moi. C'est moi, {who}. Laisse-moi entrer.",
			"Ouvre, s'il te plaît. S'il te plaît. Il fait froid. Froid.",
			"Tu me connais. Ouvre la porte. Ouvre la porte.",
			"Je suis rentré[|e] à la maison. Laisse-moi rentrer.",
		],
		"ph.SABOTAGE_SEEN": [
			"{who} rôdait {place}, et maintenant tout est gâché.",
			"J'ai vu {who} faire quelque chose {place}. C'est {who:lui|elle}.",
			"Qui gâche les provisions ? {who} était {place} en dernier.",
		],
		"ph.SABOTAGE_SEEN_AT_PLAYER": [
			"Qu'est-ce que tu fais {place} ? Je l'ai vu : après toi, tout est gâché.",
			"Après ton passage {place}, tout est gâché. Je l'ai vu.",
		],
		"ph.ELDER_UPYR": [
			"Je suis [l'Ancien|l'Ancienne]. J'ai lu les dessins : {who} est un loup-garou.",
			"Écoutez. Je suis [l'Ancien|l'Ancienne], et sur les dessins {who} n'est pas humain{|e}.",
		],
		"ph.ELDER_HUMAN": [
			"Je suis [l'Ancien|l'Ancienne]. {who} est humain{|e}, j'ai vérifié.",
			"D'après les dessins, {who} est innocent{|e}. Je suis [l'Ancien|l'Ancienne], on peut me croire.",
		],
		"ph.MEETING_CALL": [
			"Assez parlé. On vote maintenant : {who}.",
			"Je sonne la cloche. {who} ment, on tranche avant la nuit.",
			"Rassemblement. Je ne dormirai pas à côté {who.de}.",
		],
		"ph.BOX_NOTE": [
			"Dans la caisse, un billet : « {a} ou {b} ». L'un des deux est un loup-garou.",
			"J'ai ouvert la caisse. Un billet dedans : « {a} ou {b}. L'un des deux n'est pas humain. »",
		],
		"ph.BOX_OIL": [
			"De l'huile pour les lanternes dans la caisse. La nuit sera plus claire.",
			"J'ai ouvert la caisse : de l'huile. On remplira les lanternes.",
		],
		"ph.BOX_CHALK": [
			"De la craie dans la caisse. J'ai retracé le talisman {house.of}.",
		],
		"plea.shared.label": "On a déjà dormi ensemble",
		"plea.shared.text": "On a déjà passé une nuit ensemble, et il ne s'est rien passé.",
		"plea.promise.label": "Promettre d'ouvrir demain",
		"plea.promise.text": "Laisse-moi entrer. Demain, je t'ouvrirai en premier.",
		"plea.name.label": "Nommer le loup-garou",
		"plea.name.text": "Je sais qui c'est. Laisse-moi entrer, je te dirai.",
		"plea.beg.label": "Supplier",
		"plea.beg.text": "S'il te plaît. Dehors, on ne survit pas.",
		"spoil.water": "les seaux sont renversés",
		"spoil.wood": "le bois est éparpillé dans la boue",
		"spoil.lamp": "l'huile est répandue",
		"spoil.fish": "la pêche est rejetée à la rivière",
		"spoil.any": "tout est gâché",
		"quick.house": "Je dors {house.in}. Qui vient avec moi ?",
		"quick": ["Je ne suis pas un loup-garou. Je le jure.", "Celui qui revient de dehors, c'est le loup-garou.", "Restons par deux.", "Qui ment sur l'endroit où il dort, dehors."],
		"intent.accuse": ["loup", "garou", "c'est lui", "c'est elle", "ment", "menteur", "louche", "suspect", "confiance", "dehors", "coupable", "assassin"],
		"intent.invite": ["viens", "avec moi", "ensemble", "allons", "on va"],
		"intent.defend": ["pas moi", "je ne suis pas", "humain", "je le jure", "innocent", "croyez-moi"],
		"intent.ask": ["où ", "quelle maison", "tu dors"],
		"intent.houses": ["rivière", "grange", "chapelle", "cave", "garage"],
		"ev.street": "est revenu{|e} vivant{|e} de dehors",
		"ev.times": " ({n} fois)",
		"ev.liar": "a menti sur l'endroit où {who:il|elle|tu} dort",
		"ev.death": "était là quand quelqu'un est mort",
		"ev.fake": "a travaillé pour rien",
		"ev.sabotage": "était près d'un travail gâché",
		"ev.tunnel": "s'est glissé{|e} par le tunnel dans une autre maison",
		"ev.sep": " ; ",
		"sys.sabotage": "Quelqu'un a fait des dégâts {place} : {what}. Les provisions ont baissé.",
		"claim.elder_upyr": "s'est dit{me:|e} {me:l'Ancien|l'Ancienne} : {who} est un loup-garou",
		"claim.elder_human": "s'est dit{me:|e} {me:l'Ancien|l'Ancienne} : {who} est humain{who:|e|}",
		"claim.healer": "{role} : a soigné {who} la nuit {n}",
		"when.night": "Nuit {n}",
		"when.day": "Jour {n}",
		"chron.line": "{title} : {text}",
		"chron.morning": "Au matin : {text}",
		"log.exiled": "le village a banni {who}.",
		"log.supplies": "provisions réunies : {p} %.",
		"log.tunnel": "{who.cap} {who:a été refoulé|a été refoulée|as été refoulé} {from.of} et {who:s'est glissé|s'est glissée|t'es glissé} par le tunnel {house.in}.",
		"log.street_upyr": "{who.cap} {who:a été refoulé|a été refoulée|as été refoulé} {house.of}, mais {who:il a|elle a|tu as} tenu jusqu'au matin.",
		"log.street_dead": "{who.cap} {who:a été refoulé|a été refoulée|as été refoulé} {house.of}. {who:Au matin, on l'a trouvé dans la rue.|Au matin, on l'a trouvée dans la rue.|Tu es mort dehors.}",
		"log.street_ok": "{who.cap} {who:a passé|a passé|as passé} la nuit dehors et {who:a survécu|a survécu|as survécu}.",
		"log.mimic_knock": "on a frappé à la porte {house.of} avec la voix {voice.de}. Personne n'a ouvert.",
		"log.mimic_spared": "{house.in} on a laissé entrer la voix {voice.de}. Ce n'était pas {voice}, mais tout le monde a tenu jusqu'au matin.",
		"log.mimic_kill": "{house.in} on a laissé entrer la voix {voice.de}. C'était l'Imitateur : il a emporté {who}.",
		"log.alone_dead": "{who.cap} {who:était seul|était seule|étais seul} {house.in}. Le talisman s'est éteint.",
		"log.killed": "{who.cap} {who:est mort|est morte|es mort} {house.in}. À côté : {others}.",
		"log.clean": "{house.in}, {list} ont dormi. Tout le monde va bien.",
		"log.creature": "le talisman {house.of} était brisé. La chose de la forêt a emporté {who}.",
		"log.liar": "{who.cap} {who:parlait|parlait|parlais} {said.of}, mais {who:a dormi|a dormi|as dormi} {house.in}.",
		"log.talisman_cracked": "le talisman {house.of} s'est fêlé.",
		"log.talisman_broken": "le talisman {house.of} s'est brisé.",
		"log.saved": "{house.in}, on a attaqué {who}, mais {healer} {h:l'a soigné|l'a soigné|l'as soigné}{who:|e|}.",
		"log.meeting": "{who.cap} {who:a sonné|a sonné|as sonné} la cloche : réunion d'urgence.",
		"log.event": "{e}.",
		"sys.dawn1": "L'aube. Tout le monde sort sur la place.",
		"sys.dawn": "Jour {d}. Encore en vie : {n}.",
		"job.water.title": "Puiser de l'eau",
		"job.water.place": "au puits",
		"job.water.done": "Assez d'eau jusqu'au matin.",
		"job.wood.title": "Fendre du bois",
		"job.wood.place": "au tas de bois",
		"job.wood.done": "Du bois pour toute la nuit.",
		"job.lamp.title": "Remplir les lanternes",
		"job.lamp.place": "près de la lanterne",
		"job.lamp.done": "Les lanternes sont pleines.",
		"job.fish.title": "Pêcher",
		"job.fish.place": "à la rivière",
		"job.fish.done": "Du poisson pour le souper.",
		"job.talisman.title": "Réparer le talisman",
		"job.talisman.place": "près du talisman",
		"job.talisman.done": "Le talisman est comme neuf.",
		"job.box.title": "Ouvrir la caisse",
		"job.box.place": "près de la caisse",
		"role.elder": "{who:Ancien|Ancienne|Ancien}",
		"role.elder.mid": "{who:l'Ancien|l'Ancienne|l'Ancien}",
		"role.healer": "{who:Guérisseur|Guérisseuse|Guérisseur}",
		"role.healer.mid": "{who:le guérisseur|la guérisseuse|le guérisseur}",
		"role.headman": "Maire",
		"role.headman.mid": "{who:le maire|la maire|le maire}",
		"role.named": "{role} {who}",
		"event.fog.title": "Brouillard",
		"event.fog.mid": "brouillard",
		"event.fog.text": "Le brouillard étouffe la cloche : moins de temps pour courir, la rue est plus dangereuse.",
		"event.moon.title": "Pleine lune",
		"event.moon.mid": "pleine lune",
		"event.moon.text": "Pleine lune : d'ici le matin, tous les talismans faibliront.",
		"event.quiet.title": "Nuit calme",
		"event.quiet.mid": "nuit calme",
		"event.quiet.text": "Nuit calme : la rue est plus sûre, l'Imitateur ne viendra pas.",
		"event.rain.title": "Averse",
		"event.rain.mid": "averse",
		"event.rain.text": "L'averse noie les lanternes : l'huile des provisions ne servira à rien cette nuit.",
		"recap.street_host": "On ne t'a pas ouvert {house.of} : c'est {who} qui gardait la porte.",
		"recap.street": "Tu as passé la nuit dehors. Presque personne n'y survit.",
		"recap.street_p": "Risque de mourir dehors cette nuit-là : {p} %.",
		"recap.killer": "{who} t'a tué. {who:Il|Elle} était un loup-garou.",
		"recap.you_opened": "Tu as toi-même ouvert la porte {who.a}.",
		"recap.killer_opened": "C'est {who} {who:lui-même|elle-même} qui t'a ouvert.",
		"recap.near": "À côté : {others}.",
		"recap.alone": "Tu étais seul {house.in}. Seul, le talisman ne tient pas jusqu'au matin.",
		"recap.alone_p": "Risque de mourir seul dans cette maison : {p} %. Le jour, demande à quelqu'un de venir avec toi.",
		"recap.creature": "Le talisman {house.of} était brisé, et la chose de la forêt est entrée.",
		"recap.creature_tip": "On pouvait réparer le talisman dans la journée : c'est un travail sur la place.",
		"recap.mimic_you": "Tu as ouvert la porte à la voix {voice.de}. C'était l'Imitateur.",
		"recap.mimic_host": "{who} a laissé entrer la voix {voice.de}. C'était l'Imitateur.",
		"recap.voice_dead": "{voice} était déjà mort{voice:|e} à ce moment-là.",
		"recap.voice_away": "Et {voice} était {house.in} à ce moment-là.",
		"recap.exiled": "On t'a banni le jour {d}. Contre toi : {list}.",
		"recap.exiled_many": "On t'a banni le jour {d}. Contre toi : la majorité.",
		"recap.seen": "Le village a vu : {ev}.",
		"recap.exiled0": "On t'a banni.",
		"recap.died": "Tu es mort la nuit {n}. {why}",
		"verdict.mimic": "La nuit {n}, tu as ouvert la porte à l'Imitateur, à la voix {voice.de}.",
		"verdict.let_upyr": "La nuit {n}, tu as laissé entrer {who}, et c'était un loup-garou.",
		"verdict.vote_upyr": "Le jour {n}, ta voix a aidé à bannir un loup-garou : {who}.",
		"verdict.vote_human": "Le jour {n}, tu as voté contre {who}, et {who:il|elle} était humain{who:|e}.",
		"verdict.clean": "Tu n'as jamais ouvert à un loup-garou et tu as vu l'aube.",
		"verdict.dead": "Tu n'as pas vu l'aube.",
		"verdict.kills": " À ton actif : {n}.",
		"verdict.upyr_won": "Le village n'a jamais compris que le loup-garou, c'était toi.",
		"verdict.upyr_lost": "Tu as vu l'aube, mais le village a tenu bon.",
		"sys.box": "Une caisse est posée au bord de la place. Elle n'était pas là hier.",
		"sys.elder_upyr": "Les dessins de l'Ancien : {who} est un loup-garou. Toi seul le sais.",
		"sys.elder_human": "Les dessins de l'Ancien : {who} est humain{who:|e}. Toi seul le sais.",
		"sys.bell_you": "Tu sonnes la cloche. Réunion d'urgence !",
		"sys.bell": "{who} sonne la cloche. Réunion d'urgence !",
		"box.note": "Dans la caisse, un billet : « {a.cap} ou {b} ». L'un des deux est un loup-garou. Toi seul vois le billet.",
		"box.oil": "De l'huile pour les lanternes dans la caisse : provisions +{n}.",
		"box.chalk": "De la craie dans la caisse : le talisman {house.of} est retracé.",
		"box.empty": "La caisse est vide.",
		"say.accuse": "Je pense que c'est {who}.",
		"say.invite": "{who}, on va {house.to} ensemble ?",
		"say.ask": "{who}, tu dors où ce soir ?",
		"say.defend": ["Je ne suis pas un loup-garou. Je le jure.", "Je suis des vôtres. Vérifiez cette nuit.", "Pas moi. Cherchez encore."],
		"toast.elder_upyr": "Dessins : {who} est un loup-garou",
		"toast.elder_human": "Dessins : {who} est humain{who:|e}",
		"toast.box_taken": "La caisse a déjà été ouverte",
		"toast.job_done": "« {job} » : fait pour aujourd'hui",
		"toast.box": "Une caisse est apparue sur la place",
		"toast.back_exit": "Appuie encore pour quitter",
		"quit.ask": "Abandonner la partie ?",
		"quit.stay": "Rester",
		"quit.leave": "Retour au menu",
		"cfg.players": "Joueurs",
		"cfg.monsters": "Loups-garous",
		"cfg.shelters": "Abris",
		"cfg.capacity": "Places par abri",
		"cfg.nights": "Nuits jusqu'à l'aube",
		"cfg.day_seconds": "Jour, secondes",
		"cfg.door_seconds": "Décision à la porte, secondes",
		"cfg.run_seconds": "Course jusqu'à la maison, secondes",
		"cfg.outside_death": "Mort dehors, %",
		"cfg.first_night_outside_death": "Idem la première nuit, %",
		"cfg.vote_from_day": "Bannissement à partir du jour",
		"diff.easy": "Facile",
		"diff.normal": "Normale",
		"diff.hard": "Difficile",
		"diff.custom": "Perso",
		"diff.cast": "{p} villageois, {u} {u#loup-garou|loups-garous}.",
		"diff.human": " Tu es toujours humain.",
		"diff.easy_note": " Journée plus longue.",
		"diff.hard_note": " Journée plus courte, rue plus dangereuse.",
		"diary.exiled": "{who:Banni|Bannie|Banni} le jour {n}.",
		"diary.died": "{who:Mort|Morte|Mort} la nuit {n}.",
		"diary.night": "{n} : {where}",
		"diary.street": "dehors",
		"diary.said": " (avait dit : {house})",
		"diary.nights": "Nuits : {list}.",
		"diary.today": "Va ce soir : {house}.",
		"diary.evidence": "Indices : {ev}.",
		"diary.own_claim": "{text}.",
		"diary.claim": "{who.cap} {text}.",
		"diary.seen_upyr": "Tes dessins : loup-garou.",
		"diary.seen_human": "Tes dessins : humain.",
		"diary.nothing": "Rien de connu pour l'instant.",
		"diary.head": "Journal : ce qu'on sait de chacun",
		"diary.gone": "{who} · {who:mort|morte|mort}",
		"journal.who": "{who} :",
		"journal.head": "Registre du jour",
		"ui.close": "Fermer",
		"ui.cancel": "Annuler",
		"say.placeholder": "Ou écris toi-même",
		"say.send": "Dire",
		"chip.exiled": " · banni",
		"supplies": "Provisions {a} sur {b}",
		"howto.art_accuse": "C'est toi, le loup-garou !",
		"howto.art_street": "‹ dehors",
		"howto.art_door": "Ouvrir ?",
		"game.title": "Laissez-moi entrer",
		"menu.tale": "La nuit, personne ne survit dehors.\nIl y a moins d'abris que de gens.\n\nQuelqu'un est à la porte et supplie qu'on lui ouvre. Quelqu'un à l'intérieur décide.",
		"menu.hint": "Les loups-garous sont parmi vous. Ils ne se connaissent même pas entre eux.",
		"menu.howto": "Comment jouer",
		"menu.play": "Jouer",
		"lang.pick": "Langue",
		"diff.note": "{d} : {text}",
		"diff.note_custom": "Difficulté perso : {text}",
		"settings.title": "Réglages",
		"settings.lang": "Langue",
		"settings.sound": "Son",
		"settings.music": "Musique",
		"settings.sfx": "Effets",
		"settings.ambience": "Ambiance",
		"settings.haptics_on": "Vibration : activée",
		"settings.haptics_off": "Vibration : désactivée",
		"settings.difficulty": "Difficulté",
		"settings.hints": "Revoir les astuces",
		"settings.hints_reset": "Les astuces vont réapparaître",
		"settings.note": "Chaque niveau a été testé sur 1 500 parties. Le nombre d'abris et de nuits pèse le plus sur l'équilibre.",
		"settings.start": "Lancer avec ces réglages",
		"ui.back": "Retour",
		"howto.day.title": "Le jour",
		"howto.day.text": "Des gens vivent au village, et parmi eux des loups-garous. Les loups-garous ressemblent à tout le monde. Tu es un villageois avec une lanterne.\n\nLe jour, tout le monde est sur la place. Touche un villageois : accuse-le, propose-lui de passer la nuit ensemble ou demande-lui où il dort. Un œil rouge au-dessus de la tête : le village le soupçonne.\n\nTouche l'icône d'un travail : eau, bois, lanternes. Plus il y a de provisions, plus la nuit est claire. Les loups-garous font semblant de travailler, voire gâchent ce qui est fait. Parfois une caisse apparaît sur la place : celui qui l'ouvre en premier garde la trouvaille.",
		"howto.night.title": "La nuit",
		"howto.night.text": "Le soir, la cloche sonne et tout le monde court chez soi. Tant qu'elle sonne, touche une maison. Il y a moins d'abris que de gens : qui reste dehors ne verra sans doute pas le matin.\n\nSeul dans une maison, c'est risqué aussi. Le jour, mets-toi d'accord avec quelqu'un pour la nuit et répare un talisman fêlé : dans une maison au talisman brisé entre la chose de la forêt.",
		"howto.door.title": "La porte",
		"howto.door.text": "Le premier arrivé à une maison décide qui entre.\n\nSi tu ouvres à un loup-garou, tu ne verras pas le matin. Si tu n'ouvres à personne, tu restes seul. Le matin, regarde qui a dormi où et qui a menti.\n\nParfois on frappe avec la voix de quelqu'un qui est dans une autre maison ou déjà mort. C'est l'Imitateur : n'ouvre pas.\n\nCertains ont un rôle : l'Ancien, le guérisseur, le maire. Une fois par partie, tu peux sonner la cloche en journée et passer tout de suite au vote. Tout ce qu'on sait de chacun est dans le Journal.",
		"howto.title": "Comment jouer · {a} sur {b}",
		"howto.got_it": "Compris",
		"ui.next": "Suite",
		"ui.skip": "Passer",
		"crash.title": "Rapport",
		"crash.head": "La dernière session s'est fermée brutalement",
		"crash.text": "C'est une erreur du jeu, pas la tienne. Touche « Copier le rapport » et envoie-le-nous : on y voit à quelle étape tout s'est arrêté.",
		"crash.steps": "Dernières étapes :",
		"crash.copy": "Copier le rapport",
		"crash.copied": "Copié : colle-le dans le chat",
		"ui.continue": "Continuer",
		"prologue.title": "Avant la première nuit",
		"prologue.pre": "Ton rôle…",
		"prologue.upyr": "Tu es un loup-garou",
		"prologue.human": "Tu es humain",
		"prologue.upyr_text": "Tu ne sais pas qui d'autre est comme toi. La rue ne te fait pas peur, et celui qui se retrouve derrière la même porte que toi ne verra pas le matin. Le jour, parle comme un humain.",
		"prologue.human_text": "La nuit dehors, tu mourras presque à coup sûr. Dans un abri, on ne peut pas rester seul : le talisman s'éteint. Il te faut quelqu'un, et tu ne sais pas qui est humain.",
		"prologue.facts": "{p} villageois, {u} {u#loup-garou|loups-garous}. {s} {s#abri|abris} de {c} places. Tiens jusqu'à la {n}e aube.",
		"prologue.go": "Rejoindre les autres",
		"prologue.elder": "Tu es l'Ancien. Une fois par partie, le jour, touche un villageois et lis les dessins : tu sauras si c'est un loup-garou. Toi seul le sauras.",
		"prologue.healer": "Tu es le guérisseur. Une fois par partie, avant la nuit, prends tes herbes : si quelqu'un est attaqué près de toi dans la maison, tu le soigneras.",
		"prologue.headman": "Tu es le maire. Au bannissement, ta voix compte double.",
		"end.title": "Bilan",
		"end.people": "Les humains ont tenu",
		"end.upyri": "Le village est vide",
		"end.won": "Ton camp a gagné.",
		"end.lost": "Ton camp a perdu.",
		"end.who": "Qui était qui",
		"end.upyr": "loup-garou",
		"end.human": "humain",
		"end.with_role": "{a}, {role}",
		"end.chip": "{who} : {what}",
		"end.how": "Comment ça s'est passé",
		"end.again": "Rejouer",
		"end.verdict": "Ce qui a décidé la partie",
		"end.offer_easier": "Rendre plus facile ?",
		"end.offer_harder": "Deux victoires d'affilée. Essayer plus dur ?",
		"end.easier": "Plus facile",
		"end.harder": "Plus difficile",
		"vote.title": "Bannissement",
		"vote.bell_you": "Réunion d'urgence : c'est toi qui as sonné la cloche.",
		"vote.bell": "Réunion d'urgence : {who} a sonné la cloche.",
		"vote.ask": "Qui chasser du village ? Le banni part pour toujours. Ce qu'il était, vous le saurez à la fin.",
		"day.diary": "Journal",
		"vote.headman": "Tu es le maire : ta voix compte double.",
		"vote.dead": "Tu es mort et tu ne fais que regarder.",
		"vote.watch": "Voir le résultat",
		"vote.go": "Bannir",
		"vote.none": "Personne n'a été banni",
		"vote.gone": "{who} est {who:parti|partie}",
		"vote.gone_you": "Tu as été banni",
		"vote.row": "{who} : {n}",
		"vote.night": "La nuit tombe",
		"mo.title": "Matin",
		"mo.all_alive": "Tout le monde a survécu",
		"mo.one_dead": "Il en manque un",
		"mo.dead_n": "Manquent : {n}",
		"mo.why": "Pourquoi tu es mort",
		"mo.event": "Cette nuit : {e}.",
		"mo.street_dead": "{who.cap} {who:a été refoulé|a été refoulée|as été refoulé} {house.of}. {who:Retrouvé dans la rue.|Retrouvée dans la rue.|Tu es mort dehors.}",
		"mo.alone_dead": "{who.cap} {who:était seul|était seule|étais seul} {house.in}. Le talisman s'est éteint.",
		"mo.killed": "{who.cap} {who:est mort|est morte|es mort} {house.in}. À côté : {others}.",
		"mo.street_ok": "{who.cap} {who:a passé|a passé|as passé} la nuit dehors. Et {who:est revenu|est revenue|es revenu}.",
		"mo.alone_ok": "{who.cap} {who:était seul|était seule|étais seul} {house.in}, et {who:il va bien|elle va bien|tu vas bien}.",
		"mo.clean": "{house.in.cap}, {list} ont dormi. Tout le monde va bien.",
		"mo.liar": "{who.cap} {who:parlait|parlait|parlais} {said.of}, mais {who:a dormi|a dormi|as dormi} {house.in}.",
		"mo.creature": "Le talisman {house.of} était brisé. La chose de la forêt a emporté {who}.",
		"mo.talisman_cracked": "Le talisman {house.of} s'est fêlé. On peut le réparer dans la journée.",
		"mo.talisman_broken": "Le talisman {house.of} s'est brisé. On peut le réparer dans la journée.",
		"mo.saved_upyr": "{house.in.cap}, l'un des nôtres a attaqué {who}, mais {healer} {h:l'a soigné|l'a soigné|l'as soigné}{who:|e|}.",
		"mo.saved_creature": "{house.in.cap}, la chose de la forêt a attaqué {who}, mais {healer} {h:l'a soigné|l'a soigné|l'as soigné}{who:|e|}.",
		"mo.saved_mimic": "{house.in.cap}, l'Imitateur a attaqué {who}, mais {healer} {h:l'a soigné|l'a soigné|l'as soigné}{who:|e|}.",
		"mo.tunnel": "{who.cap} {who:a été refoulé|a été refoulée|as été refoulé} {from.of} et {who:s'est glissé|s'est glissée|t'es glissé} par le tunnel {house.in}.",
		"mo.mimic_kill": "{house.in.cap}, on a laissé entrer la voix {voice.de}. Ce n'était pas {voice} : l'Imitateur a emporté {who}.",
		"mo.mimic_spared": "{house.in.cap}, on a laissé entrer la voix {voice.de}. Ce n'était pas {voice}, mais tout le monde a tenu jusqu'au matin.",
		"mo.mimic_knock": "Cette nuit, on a frappé à la porte {house.of} avec la voix {voice.de}. Personne n'a ouvert. C'était l'Imitateur.",
		"mo.mimic_knock_away": "Cette nuit, on a frappé à la porte {house.of} avec la voix {voice.de}. Personne n'a ouvert. Et {voice} était {away.in} à ce moment-là.",
		"list.sep": ", ",
		"night.dusk": "La nuit tombe. La cloche sonne.",
		"night.dead": "Tu n'es plus là. La nuit continue sans toi.",
		"night.bell": "La cloche sonne ! Cours à une maison : touche-la.",
		"night.going": "y vont : {list}",
		"night.pact": "accord avec {who}",
		"night.tunnel": "tunnel vers {house.the}",
		"night.tal_broken": "talisman brisé",
		"night.tal_cracked": "talisman fêlé",
		"night.rule": "Le premier à la porte est à l'intérieur et décide qui entre. Si tu ne choisis pas de maison pendant que la cloche sonne, tu courras en dernier là où tu avais dit.",
		"night.heal": "Prendre les herbes : je sauverai un voisin cette nuit",
		"night.hint": "La cloche ne sonne pas longtemps. Touche une maison sur la place ou dans la liste et cours. Le premier à la porte décide qui entre.",
		"night.heal_on": "Herbes prêtes : si quelqu'un est attaqué près de toi, tu le soigneras",
		"night.first": "Tu arriveras le premier : c'est toi qui décideras qui entre.",
		"night.ahead": "Avant toi à la porte : {list}. C'est {who} qui décidera.",
		"night.run": "Tu cours {house.to}. {rest}",
		"door.title": "À la porte",
		"door.hint_host": "Fais entrer quelqu'un en qui tu as confiance. Si tu n'ouvres à personne, tu restes seul, et seul on ne survit pas.",
		"door.hint_guest": "Choisis quoi dire à travers la porte. L'hôte se souvient si vous avez déjà dormi ensemble.",
		"door.hint_alone": "Seul, on ne survit pas ici. La prochaine fois, demande à quelqu'un de venir avec toi.",
		"door.host": "Tu es arrivé le premier {house.to}. On frappe à la porte.",
		"door.cap": "Tu peux faire entrer : {n}",
		"door.quote": "« {text} »",
		"door.admit": "Faire entrer",
		"door.admitting": "J'ouvre",
		"door.elsewhere": "À d'autres portes : {list}.",
		"door.upyr_note": "Celui que tu fais entrer ne verra pas le matin.",
		"door.alone_note": "Si tu n'ouvres à personne, tu restes seul et le talisman s'éteindra.",
		"door.open": "Ouvrir la porte",
		"door.refuse": "N'ouvrir à personne",
		"door.locked": "{house.the.cap} est déjà verrouillé{house:|e} de l'intérieur. Dedans : {who}.",
		"door.rivals": "À la porte avec toi : {list}. Il n'y aura pas de place pour tous.",
		"door.mimic": "Dans le noir derrière toi, quelqu'un parle avec la voix {voice.de}. Mais {voice} n'est pas là.",
		"door.say": "Que dis-tu à travers la porte ?",
		"door.knock": "Tu frappes à la porte {house.of}…",
		"door.let_in": "Le verrou claque. {who} te fait entrer.",
		"door.shut": "Des pas s'éloignent de la porte. Tu restes dehors.",
		"door.hatch": "Derrière la maison, une trappe. Le tunnel mène {house.to}, il y a de la place. Qui s'y glisse est à l'intérieur, mais au matin tout le monde saura d'où il vient.",
		"door.tunnel": "Passer par le tunnel {house.to}",
		"door.wait": "Attendre l'aube",
		"door.alone": "Tu es arrivé le premier {house.to}. Personne d'autre n'est venu.",
		"door.alone_upyr": "Un loup-garou seul ne craint pas la rue.",
		"door.alone_human": "Le talisman vacille. Seul, tu ne le tiendras pas jusqu'au matin.",
		"day.journal": "Registre",
		"day.journal_n": "Registre ({n})",
		"day.dead": "Tu n'es plus là. Tu ne fais que regarder.",
		"day.skip": "Passer la journée",
		"day.defend": "Se justifier",
		"day.invite": "Inviter…",
		"day.accuse": "Accuser…",
		"day.say": "Dire…",
		"day.bell": "Réunion !",
		"day.ready": "Prêt pour la nuit",
		"day.hint": "Touche un villageois : accuse-le, invite-le ou demande-lui où il dort. Touche l'icône d'un travail : les provisions allument les lanternes la nuit.",
		"day.bell_ask": "Sonner la cloche ? Tout le monde se réunit pour voter tout de suite. Possible une fois par partie.",
		"day.bell_do": "Sonner la cloche",
		"day.preview": "{who} : {text}",
		"day.say_aloud": "Dire tout haut",
		"day.person_ev": "{who} · {ev}",
		"day.p_accuse": "Accuser : « C'est {who} »",
		"day.p_invite": "Inviter pour la nuit",
		"day.p_ask": "Demander où dormir",
		"day.p_elder": "Lire les dessins de l'Ancien : qui est-{who:il|elle} ?",
		"day.work": "Travailler : {job.low}",
		"day.spoil": "Gâcher le travail {place}",
		"day.who_accuse": "Accuser qui ?",
		"day.who_invite": "Inviter qui ?",
		"day.where_with": "Où vas-tu avec {who} ?",
	}
