extends Gram
## Português (Brasil). Uma vila de lendas: o Saci de gorro vermelho, a Iara do rio, o Boto de chapéu branco,
## a baiana de turbante, um cangaceiro de chapéu de couro e a arara Juca.
## O monstro é o lobisomem. O jogador é «você»: verbos na terceira pessoa.


func code() -> String:
	return "pt"


func plural_index(n: int) -> int:
	return 0 if absi(n) <= 1 else 1


func data() -> Dictionary:
	return {
		"and": " e ",
		"you": {"nom": "você", "acc": "você", "gen": "você", "dat": "você", "ins": "você"},
		"you_name": "Você",
		"someone": {"nom": "outra pessoa", "acc": "outra pessoa", "gen": "outra pessoa", "dat": "outra pessoa", "f": true},
		## nom — placa e listas; in — «no celeiro»; to — «para o celeiro»; of — «do celeiro»; the — «o celeiro».
		"houses": [
			{"nom": "Casa do rio", "f": true, "in": "na Casa do rio", "to": "para a Casa do rio", "of": "da Casa do rio", "the": "a Casa do rio"},
			{"nom": "Celeiro", "in": "no celeiro", "to": "para o celeiro", "of": "do celeiro", "the": "o celeiro"},
			{"nom": "Capela", "f": true, "in": "na capela", "to": "para a capela", "of": "da capela", "the": "a capela"},
			{"nom": "Porão", "in": "no porão", "to": "para o porão", "of": "do porão", "the": "o porão"},
			{"nom": "Garagem", "f": true, "in": "na garagem", "to": "para a garagem", "of": "da garagem", "the": "a garagem"},
		],
		"names": [
			["Iara", true], ["Saci", false], ["Bia", true], ["Zé", false], ["Rosa", true], ["Boto", false],
			["Tião", false], ["Ana", true], ["Chico", false], ["Lia", true], ["Juca", false], ["Cida", true],
		],
		"looks": "res://config/looks_pt.tres",
		"ph.ANNOUNCE": [
			"Hoje eu durmo {house.in}.",
			"Vou {house.to}. Quem vem comigo?",
			"Fico {house.in}, só pra avisar.",
			"{house.nom}. Tá decidido.",
		],
		"ph.ACCUSE_STRONG": [
			"{who}, explica como você chegou viv{who:o|a} até de manhã.",
			"Pra mim tá na cara. {who}.",
			"{who} tava bem do lado quando tudo aconteceu. Coincidência?",
			"Eu voto em {who}. Sem dúvida.",
		],
		"ph.ACCUSE_STREET": [
			"{who} passou a noite lá fora e voltou. Gente não consegue isso.",
			"{who}, você ficou a noite toda lá fora. Não tem nada pra dizer?",
		],
		"ph.ACCUSE_LIAR": [
			"{who} disse que ia {house.to} e dormiu em outro lugar. Por que mentir?",
			"{who}, você ia pra outro lugar. O que mudou?",
		],
		"ph.DEFEND": [
			"Sim, eu tava lá. E daí?",
			"Eu não sou lobisomem. Me testem hoje à noite.",
			"Só dei azar com o quarto.",
			"Se me expulsarem agora, de manhã vão faltar mais dois.",
		],
		"ph.UPYR_DEFLECT": [
			"Se eu fosse vocês, ficava de olho em {who}.",
			"Vocês discutindo e a noite chegando.",
			"Calma. Se a gente errar, perde um dos nossos.",
			"{who}, por que você fica calad{who:o|a} o tempo todo?",
			"Ontem fiquei quiet[o|a] e sobrevivi. Então fiz tudo certo.",
		],
		"ph.FILLER": [
			"A gente tá cada vez menos. Contem aí.",
			"Vamos decidir logo, tá escurecendo.",
			"Não confio em ninguém. Ninguém.",
			"Alguém aqui tá mentindo agora mesmo.",
		],
		"ph.REPLY_TO_ACCUSED_HUMAN": [
			"Eu? Sério? Olha pra {who}.",
			"Você tá me confundindo com alguém.",
			"Tá bom. Me expulsem. De manhã vocês vão entender.",
		],
		"ph.REPLY_TO_ACCUSED_UPYR": [
			"Engraçado. Vamos falar de você.",
			"É assim que se afunda um dos nossos. Que conveniente.",
			"Você tá com muita pressa de me expulsar. Suspeito.",
		],
		"ph.AGREE_ACCUSE": [
			"Concordo. Também não vou com a cara de {who}.",
			"Apoiado. {who}.",
		],
		"ph.DISAGREE_ACCUSE": [
			"Não, {who} parece gente boa. Qual é a sua?",
			"Fraco. Cadê a prova?",
		],
		"ph.INVITE_YES": [
			"Fechado. A gente se encontra {house.in}.",
			"Tá, eu vou com você {house.to}.",
			"Combinado. Só não me deixa na mão.",
		],
		"ph.INVITE_NO": [
			"Não, com você eu não vou. Sem ofensa.",
			"Ainda não confio em você.",
			"Já tenho com quem ir.",
		],
		"ph.ASK_ANSWER_HUMAN": [
			"Tô {house.in}. Não é segredo.",
			"Já falei: {house.the}.",
		],
		"ph.ASK_ANSWER_UNSURE": [
			"Ainda não decidi.",
			"Vou ver quem vai pra onde.",
		],
		"ph.PLAYER_DEFEND_REACTION": [
			"Sei.",
			"Vamos ver.",
			"Todo mundo diz isso.",
			"Tá, eu acredito. Por enquanto.",
		],
		"ph.GENERIC_REACTION": [
			"E o que você quer dizer com isso?",
			"Bonito. Bonito demais.",
			"Você tá contando isso pra você ou pra gente?",
			"Ouvi. Não me convenceu.",
		],
		"ph.AT_PLAYER": [
			"É com você que eu tenho mais perguntas.",
			"Você tá calmo demais.",
			"Você tá escondendo alguma coisa.",
			"Olha pra você mesmo.",
			"Não confio em você. Nem um pouco.",
		],
		"ph.PLEA_AFTER_STREET": [
			"Ontem já não me deixaram entrar. Uma segunda vez eu não aguento.",
			"Passei a noite inteira lá fora. Abre.",
		],
		"ph.PLEA_SUSPECT": [
			"Eu sei como parece. Mas eu não sou lobisomem.",
			"Confia em mim uma vez. Depois pode me expulsar.",
		],
		"ph.PLEA_NORMAL": [
			"Abre, tá frio aqui.",
			"Sou eu. Me deixa entrar.",
			"Nós dois aguentamos até de manhã.",
			"Rápido, tem alguma coisa andando aqui fora.",
		],
		"ph.PLEA_PACT": [
			"Sou eu, a gente combinou.",
			"Abre, como a gente combinou.",
		],
		"ph.JOB_FAKE": [
			"{who} ficou parad{who:o|a} {place}, e nada.",
			"Eu vi {who} enrolando {place} sem fazer nada.",
			"Estranho. {who} foi {place}, mas as provisões não aumentaram.",
			"{who} só finge que trabalha. Tava {place}: nada.",
			"O que {who} tava fazendo {place}? Os baldes continuam vazios.",
		],
		"ph.JOB_FAKE_AT_PLAYER": [
			"Você só perde tempo {place}. As provisões não aumentaram.",
			"Você finge que trabalha {place}. Eu vi.",
			"Pra que você serve {place}? Os baldes continuam vazios.",
		],
		"ph.MIMIC_PLEAS": [
			"Me deixa entrar. Sou eu. Sou eu, {who}. Me deixa entrar.",
			"Abre, por favor. Por favor. Tá frio. Frio.",
			"Você me conhece. Abre a porta. Abre a porta.",
			"Cheguei em casa. Me deixa entrar em casa.",
		],
		"ph.SABOTAGE_SEEN": [
			"{who} tava rondando {place}, e agora tá tudo estragado.",
			"Eu vi {who} fazendo alguma coisa {place}. Foi {who:ele|ela}.",
			"Quem tá estragando as provisões? {who} foi {who:o último|a última} {place}.",
		],
		"ph.SABOTAGE_SEEN_AT_PLAYER": [
			"O que você tá fazendo {place}? Eu vi: depois de você tá tudo estragado.",
			"Depois de você, ficou tudo estragado {place}. Eu vi.",
		],
		"ph.ELDER_UPYR": [
			"Sou [o Ancião|a Anciã]. Vi os desenhos: {who} é lobisomem.",
			"Escutem. Sou [o Ancião|a Anciã], e nos desenhos {who} não é gente.",
		],
		"ph.ELDER_HUMAN": [
			"Sou [o Ancião|a Anciã]. {who} é gente, eu conferi.",
			"Pelos desenhos, {who} tá limp{who:o|a}. Sou [o Ancião|a Anciã], podem confiar.",
		],
		"ph.MEETING_CALL": [
			"Chega de conversa. Vamos votar agora: {who}.",
			"Vou tocar o sino. {who} tá mentindo, a gente decide antes de escurecer.",
			"Reunião. Eu não durmo perto de {who}.",
		],
		"ph.BOX_NOTE": [
			"Tem um bilhete na caixa: “{a} ou {b}”. Um dos dois é lobisomem.",
			"Abri a caixa. Tinha um bilhete: “{a} ou {b}. Um dos dois não é gente”.",
		],
		"ph.BOX_OIL": [
			"Tem óleo de lampião na caixa. A noite vai ser mais clara.",
			"Abri a caixa: óleo. Vamos encher os lampiões.",
		],
		"ph.BOX_CHALK": [
			"Tem giz na caixa. Redesenhei o amuleto {house.of}.",
		],
		"plea.shared.label": "Já dormimos juntos antes",
		"plea.shared.text": "A gente já passou uma noite juntos e não aconteceu nada.",
		"plea.promise.label": "Prometer abrir amanhã",
		"plea.promise.text": "Me deixa entrar. Amanhã eu abro pra você primeiro.",
		"plea.name.label": "Dizer quem é o lobisomem",
		"plea.name.text": "Eu sei quem é. Me deixa entrar que eu conto.",
		"plea.beg.label": "Implorar",
		"plea.beg.text": "Por favor. Aqui fora ninguém sobrevive.",
		"spoil.water": "os baldes foram derrubados",
		"spoil.wood": "a lenha foi espalhada na lama",
		"spoil.lamp": "o óleo foi derramado",
		"spoil.fish": "os peixes foram jogados de volta no rio",
		"spoil.any": "tá tudo estragado",
		"quick.house": "Eu durmo {house.in}. Quem vem comigo?",
		"quick": ["Eu não sou lobisomem. Juro.", "Quem voltou lá de fora é o lobisomem.", "Vamos ficar em duplas.", "Quem mente sobre onde dorme, rua."],
		"intent.accuse": ["lobisom", "foi ele", "foi ela", "é ele", "é ela", "mente", "mentir", "suspeit", "não confio", "fora", "assassin", "culpad"],
		"intent.invite": ["vamos", "comigo", "juntos", "juntas", "vem pra", "vem com"],
		"intent.defend": ["não sou", "não fui", "sou gente", "juro", "inocente", "confiem"],
		"intent.ask": ["onde", "pra onde", "qual casa"],
		"intent.houses": ["rio", "celeiro", "capela", "porão", "garagem"],
		"ev.street": "voltou viv{who:o|a|o} lá de fora",
		"ev.times": " ({n} vezes)",
		"ev.liar": "mentiu sobre onde ia dormir",
		"ev.death": "tava perto quando alguém morreu",
		"ev.fake": "trabalhou à toa",
		"ev.sabotage": "tava junto de um trabalho estragado",
		"ev.tunnel": "passou pelo túnel pra outra casa",
		"ev.sep": "; ",
		"sys.sabotage": "Alguém aprontou {place}: {what}. As provisões diminuíram.",
		"claim.elder_upyr": "disse ser {me:o Ancião|a Anciã}: {who} é lobisomem",
		"claim.elder_human": "disse ser {me:o Ancião|a Anciã}: {who} é gente",
		"claim.healer": "{role}: curou {who} na noite {n}",
		"when.night": "Noite {n}",
		"when.day": "Dia {n}",
		"chron.line": "{title}: {text}",
		"chron.morning": "De manhã: {text}",
		"log.exiled": "a vila expulsou {who}.",
		"log.supplies": "provisões juntadas: {p}%.",
		"log.tunnel": "{who.cap} ficou do lado de fora {from.of} e passou pelo túnel {house.to}.",
		"log.street_upyr": "{who.cap} ficou do lado de fora {house.of}, mas sobreviveu até de manhã.",
		"log.street_dead": "{who.cap} ficou do lado de fora {house.of}. {who:De manhã acharam ele na rua.|De manhã acharam ela na rua.|Você morreu na rua.}",
		"log.street_ok": "{who.cap} passou a noite lá fora e sobreviveu.",
		"log.mimic_knock": "bateram na porta {house.of} com a voz de {voice}. Ninguém abriu.",
		"log.mimic_spared": "{house.in} deixaram entrar a voz de {voice}. Não era {voice}, mas todo mundo chegou vivo de manhã.",
		"log.mimic_kill": "{house.in} deixaram entrar a voz de {voice}. Era o Imitador: ele levou {who}.",
		"log.alone_dead": "{who.cap} ficou sozinh{who:o|a|o} {house.in}. O amuleto apagou.",
		"log.killed": "{who.cap} morreu {house.in}. Perto: {others}.",
		"log.clean": "{house.in} dormiram {list}. Todo mundo bem.",
		"log.creature": "o amuleto {house.of} estava quebrado. A coisa da mata levou {who}.",
		"log.liar": "{who.cap} disse que ia {said.to}, mas dormiu {house.in}.",
		"log.talisman_cracked": "o amuleto {house.of} rachou.",
		"log.talisman_broken": "o amuleto {house.of} quebrou.",
		"log.saved": "{house.in} atacaram {who}, mas {healer} cuidou {who:dele|dela|de você}.",
		"log.meeting": "{who.cap} tocou o sino: reunião de emergência.",
		"log.event": "{e}.",
		"sys.dawn1": "Amanhece. Todo mundo sai pra praça.",
		"sys.dawn": "Dia {d}. Ainda vivos: {n}.",
		"job.water.title": "Buscar água",
		"job.water.place": "no poço",
		"job.water.done": "Água até de manhã.",
		"job.wood.title": "Rachar lenha",
		"job.wood.place": "na pilha de lenha",
		"job.wood.done": "Lenha pra noite toda.",
		"job.lamp.title": "Encher os lampiões",
		"job.lamp.place": "perto do lampião",
		"job.lamp.done": "Lampiões cheios.",
		"job.fish.title": "Pescar",
		"job.fish.place": "no rio",
		"job.fish.done": "Tem peixe pro jantar.",
		"job.talisman.title": "Consertar o amuleto",
		"job.talisman.place": "perto do amuleto",
		"job.talisman.done": "O amuleto tá novinho.",
		"job.box.title": "Abrir a caixa",
		"job.box.place": "perto da caixa",
		"role.elder": "{who:Ancião|Anciã|Ancião}",
		"role.elder.mid": "{who:o ancião|a anciã|o ancião}",
		"role.healer": "{who:Curandeiro|Curandeira|Curandeiro}",
		"role.healer.mid": "{who:o curandeiro|a curandeira|o curandeiro}",
		"role.headman": "{who:Prefeito|Prefeita|Prefeito}",
		"role.headman.mid": "{who:o prefeito|a prefeita|o prefeito}",
		"role.named": "{role} {who}",
		"event.fog.title": "Neblina",
		"event.fog.mid": "neblina",
		"event.fog.text": "A neblina abafa o sino: menos tempo pra correr, a rua fica mais perigosa.",
		"event.moon.title": "Lua cheia",
		"event.moon.mid": "lua cheia",
		"event.moon.text": "Lua cheia: até de manhã todos os amuletos enfraquecem.",
		"event.quiet.title": "Noite calma",
		"event.quiet.mid": "noite calma",
		"event.quiet.text": "Noite calma: a rua fica mais segura, o Imitador não vem.",
		"event.rain.title": "Temporal",
		"event.rain.mid": "temporal",
		"event.rain.text": "O temporal afoga os lampiões: o óleo guardado não ajuda esta noite.",
		"recap.street_host": "Não deixaram você entrar {house.in}: quem cuidava da porta era {who}.",
		"recap.street": "Você passou a noite lá fora. Quase ninguém sobrevive lá.",
		"recap.street_p": "Chance de morrer lá fora naquela noite: {p}%.",
		"recap.killer": "{who} te matou. {who:Ele|Ela} era lobisomem.",
		"recap.you_opened": "Foi você mesmo quem abriu a porta pra {who}.",
		"recap.killer_opened": "{who} {who:mesmo|mesma} abriu a porta pra você.",
		"recap.near": "Perto: {others}.",
		"recap.alone": "Você ficou sozinho {house.in}. Sozinho, o amuleto não aguenta até de manhã.",
		"recap.alone_p": "Chance de morrer sozinho nessa casa: {p}%. De dia, chame alguém pra ir com você.",
		"recap.creature": "O amuleto {house.of} estava quebrado, e a coisa da mata entrou.",
		"recap.creature_tip": "De dia dava pra consertar o amuleto: é um trabalho da praça.",
		"recap.mimic_you": "Você abriu a porta pra voz de {voice}. Era o Imitador.",
		"recap.mimic_host": "{who} deixou entrar a voz de {voice}. Era o Imitador.",
		"recap.voice_dead": "Nessa hora {voice} já tinha morrido.",
		"recap.voice_away": "E {voice} estava {house.in} nessa hora.",
		"recap.exiled": "Te expulsaram no dia {d}. Contra você: {list}.",
		"recap.exiled_many": "Te expulsaram no dia {d}. Contra você: a maioria.",
		"recap.seen": "A vila viu: {ev}.",
		"recap.exiled0": "Te expulsaram.",
		"recap.died": "Você morreu na noite {n}. {why}",
		"verdict.mimic": "Na noite {n}, você abriu a porta pro Imitador, com a voz de {voice}.",
		"verdict.let_upyr": "Na noite {n}, você deixou {who} entrar, e {who:ele|ela} era lobisomem.",
		"verdict.vote_upyr": "No dia {n}, seu voto ajudou a expulsar um lobisomem: {who}.",
		"verdict.vote_human": "No dia {n}, você votou contra {who}, e {who:ele|ela} era gente.",
		"verdict.clean": "Você nunca abriu a porta pra um lobisomem e viu o amanhecer.",
		"verdict.dead": "Você não chegou ao amanhecer.",
		"verdict.kills": " Na sua conta: {n}.",
		"verdict.upyr_won": "A vila nunca percebeu que o lobisomem era você.",
		"verdict.upyr_lost": "Você viu o amanhecer, mas a vila resistiu.",
		"sys.box": "Tem uma caixa na beira da praça. Ontem ela não estava lá.",
		"sys.elder_upyr": "Os desenhos do Ancião: {who} é lobisomem. Só você sabe disso.",
		"sys.elder_human": "Os desenhos do Ancião: {who} é gente. Só você sabe disso.",
		"sys.bell_you": "Você toca o sino. Reunião de emergência!",
		"sys.bell": "{who} toca o sino. Reunião de emergência!",
		"box.note": "Tem um bilhete na caixa: “{a.cap} ou {b}”. Um dos dois é lobisomem. Só você vê o bilhete.",
		"box.oil": "Tem óleo de lampião na caixa: provisões +{n}.",
		"box.chalk": "Tem giz na caixa: o amuleto {house.of} foi redesenhado.",
		"box.empty": "A caixa está vazia.",
		"say.accuse": "Acho que é {who}.",
		"say.invite": "{who}, vamos juntos {house.to}?",
		"say.ask": "{who}, onde você vai dormir hoje?",
		"say.defend": ["Eu não sou lobisomem. Juro.", "Sou um de vocês. Me testem hoje à noite.", "Não fui eu. Continuem procurando."],
		"toast.elder_upyr": "Desenhos: {who} é lobisomem",
		"toast.elder_human": "Desenhos: {who} é gente",
		"toast.box_taken": "A caixa já foi aberta",
		"toast.job_done": "“{job}”: feito por hoje",
		"toast.box": "Apareceu uma caixa na praça",
		"toast.back_exit": "Toque de novo para sair",
		"quit.ask": "Abandonar a partida?",
		"quit.stay": "Ficar",
		"quit.leave": "Sair para o menu",
		"cfg.players": "Jogadores",
		"cfg.monsters": "Lobisomens",
		"cfg.shelters": "Abrigos",
		"cfg.capacity": "Vagas por abrigo",
		"cfg.nights": "Noites até o amanhecer",
		"cfg.day_seconds": "Dia, segundos",
		"cfg.door_seconds": "Decisão na porta, segundos",
		"cfg.run_seconds": "Corrida até a casa, segundos",
		"cfg.outside_death": "Morte lá fora, %",
		"cfg.first_night_outside_death": "O mesmo na primeira noite, %",
		"cfg.vote_from_day": "Expulsão a partir do dia",
		"diff.easy": "Fácil",
		"diff.normal": "Normal",
		"diff.hard": "Difícil",
		"diff.custom": "Própria",
		"diff.cast": "{p} {p#morador|moradores}, {u} {u#lobisomem|lobisomens}.",
		"diff.human": " Você é sempre gente.",
		"diff.easy_note": " Dia mais longo.",
		"diff.hard_note": " Dia mais curto, rua mais perigosa.",
		"diary.exiled": "{who:Expulso|Expulsa|Expulso} no dia {n}.",
		"diary.died": "{who:Morto|Morta|Morto} na noite {n}.",
		"diary.night": "{n}: {where}",
		"diary.street": "lá fora",
		"diary.said": " (disse: {house})",
		"diary.nights": "Noites: {list}.",
		"diary.today": "Hoje vai: {house}.",
		"diary.evidence": "Pistas: {ev}.",
		"diary.own_claim": "{text}.",
		"diary.claim": "{who.cap} {text}.",
		"diary.seen_upyr": "Seus desenhos: lobisomem.",
		"diary.seen_human": "Seus desenhos: gente.",
		"diary.nothing": "Ainda não se sabe nada.",
		"diary.head": "Diário: o que se sabe de cada um",
		"diary.gone": "{who} · {who:morto|morta|morto}",
		"journal.who": "{who}:",
		"journal.head": "Registro do dia",
		"ui.close": "Fechar",
		"ui.cancel": "Cancelar",
		"say.placeholder": "Ou escreva o seu",
		"say.send": "Dizer",
		"chip.exiled": " · expulso",
		"supplies": "Provisões {a} de {b}",
		"howto.art_accuse": "Você é o lobisomem!",
		"howto.art_street": "‹ lá fora",
		"howto.art_door": "Abrir?",
		"game.title": "Me deixa entrar",
		"menu.tale": "De noite, ninguém sobrevive na rua.\nTem menos abrigos do que gente.\n\nAlguém está na porta pedindo pra entrar. Alguém lá dentro decide.",
		"menu.hint": "Os lobisomens estão entre vocês. Nem eles se conhecem.",
		"menu.howto": "Como jogar",
		"menu.play": "Jogar",
		"lang.pick": "Idioma",
		"diff.note": "{d}: {text}",
		"diff.note_custom": "Dificuldade própria: {text}",
		"settings.title": "Configurações",
		"settings.lang": "Idioma",
		"settings.sound": "Som",
		"settings.music": "Música",
		"settings.sfx": "Efeitos",
		"settings.ambience": "Ambiente",
		"settings.haptics_on": "Vibração: ligada",
		"settings.haptics_off": "Vibração: desligada",
		"settings.difficulty": "Dificuldade",
		"settings.hints": "Mostrar dicas de novo",
		"settings.hints_reset": "As dicas vão aparecer de novo",
		"settings.note": "Cada nível foi testado em 1.500 partidas. O número de abrigos e de noites é o que mais mexe no equilíbrio.",
		"settings.start": "Começar com essas configurações",
		"ui.back": "Voltar",
		"howto.day.title": "Dia",
		"howto.day.text": "Na vila mora gente, e no meio dela tem lobisomens. Lobisomens parecem todo mundo. Você é um morador com um lampião.\n\nDe dia todo mundo está na praça. Toque num morador: acuse, chame pra passar a noite junto ou pergunte onde vai dormir. Um olho vermelho sobre a cabeça quer dizer que a vila desconfia dele.\n\nToque no ícone de um trabalho: água, lenha, lampiões. Quanto mais provisões, mais clara a noite. Os lobisomens fingem que trabalham ou até estragam o que já foi feito. Às vezes aparece uma caixa na praça: quem abrir primeiro fica com o achado.",
		"howto.night.title": "Noite",
		"howto.night.text": "À tarde o sino toca e todo mundo corre pra casa. Enquanto toca, toque numa casa. Tem menos abrigos do que gente: quem fica na rua dificilmente vê a manhã.\n\nFicar sozinho numa casa também é arriscado. De dia combine com quem vai passar a noite e conserte o amuleto rachado: na casa com amuleto quebrado entra a coisa da mata.",
		"howto.door.title": "A porta",
		"howto.door.text": "Quem chega primeiro numa casa decide quem entra.\n\nDeixou entrar um lobisomem, não vê a manhã. Não deixou ninguém entrar, fica sozinho. De manhã, veja quem dormiu onde e quem mentiu.\n\nÀs vezes batem com a voz de alguém que está em outra casa ou que já morreu. É o Imitador: não abra.\n\nAlgumas pessoas têm papéis: Ancião, Curandeiro, Prefeito. Uma vez por partida dá pra tocar o sino de dia e votar na hora. Tudo o que se sabe de cada um fica no Diário.",
		"howto.title": "Como jogar · {a} de {b}",
		"howto.got_it": "Entendi",
		"ui.next": "Próximo",
		"ui.skip": "Pular",
		"crash.title": "Relatório",
		"crash.head": "A última sessão fechou de repente",
		"crash.text": "É um erro do jogo, não seu. Toque em “Copiar relatório” e mande pra gente: nele dá pra ver em que passo tudo parou.",
		"crash.steps": "Últimos passos:",
		"crash.copy": "Copiar relatório",
		"crash.copied": "Copiado: cole no chat",
		"ui.continue": "Continuar",
		"prologue.title": "Antes da primeira noite",
		"prologue.pre": "Seu papel…",
		"prologue.upyr": "Você é um lobisomem",
		"prologue.human": "Você é gente",
		"prologue.upyr_text": "Você não sabe quem mais é como você. A rua não te assusta, e quem ficar com você atrás da mesma porta não vê a manhã. De dia, fale como gente.",
		"prologue.human_text": "De noite, na rua, você quase com certeza morre. No abrigo não dá pra ficar sozinho: o amuleto apaga. Você precisa de mais alguém, e não sabe quem é gente.",
		"prologue.facts": "{p} moradores, {u} {u#lobisomem|lobisomens}. {s} {s#abrigo|abrigos} com {c} vagas cada. Sobreviva até o {n}º amanhecer.",
		"prologue.go": "Sair pra rua",
		"prologue.elder": "Você é o Ancião. Uma vez por partida, de dia, toque num morador e veja os desenhos: vai saber se é lobisomem. Só você vai saber.",
		"prologue.healer": "Você é o Curandeiro. Uma vez por partida, antes da noite, pegue suas ervas: se atacarem alguém perto de você na casa, você cuida dele.",
		"prologue.headman": "Você é o Prefeito. Na expulsão, seu voto vale dois.",
		"end.title": "Resumo",
		"end.people": "A gente resistiu",
		"end.upyri": "A vila ficou vazia",
		"end.won": "Seu lado ganhou.",
		"end.lost": "Seu lado perdeu.",
		"end.who": "Quem era quem",
		"end.upyr": "lobisomem",
		"end.human": "gente",
		"end.with_role": "{a}, {role}",
		"end.chip": "{who}: {what}",
		"end.how": "Como foi",
		"end.again": "Jogar de novo",
		"end.verdict": "O que decidiu a partida",
		"end.offer_easier": "Deixar mais fácil?",
		"end.offer_harder": "Duas vitórias seguidas. Tentar mais difícil?",
		"end.easier": "Mais fácil",
		"end.harder": "Mais difícil",
		"vote.title": "Expulsão",
		"vote.bell_you": "Reunião de emergência: você tocou o sino.",
		"vote.bell": "Reunião de emergência: {who} tocou o sino.",
		"vote.ask": "Quem a gente expulsa da vila? O expulso vai embora pra sempre. O que ele era, vocês descobrem no fim.",
		"day.diary": "Diário",
		"vote.headman": "Você é o Prefeito: seu voto vale dois.",
		"vote.dead": "Você morreu e só pode assistir.",
		"vote.watch": "Ver o resultado",
		"vote.go": "Expulsar",
		"vote.none": "Ninguém foi expulso",
		"vote.gone": "{who} foi {who:embora|embora}",
		"vote.gone_you": "Você foi expulso",
		"vote.row": "{who}: {n}",
		"vote.night": "A noite cai",
		"mo.title": "Manhã",
		"mo.all_alive": "Todo mundo sobreviveu",
		"mo.one_dead": "Falta um",
		"mo.dead_n": "Faltam: {n}",
		"mo.why": "Por que você morreu",
		"mo.event": "Esta noite: {e}.",
		"mo.street_dead": "{who.cap} ficou do lado de fora {house.of}. {who:Acharam ele na rua.|Acharam ela na rua.|Você morreu na rua.}",
		"mo.alone_dead": "{who.cap} ficou sozinh{who:o|a|o} {house.in}. O amuleto apagou.",
		"mo.killed": "{who.cap} morreu {house.in}. Perto: {others}.",
		"mo.street_ok": "{who.cap} passou a noite lá fora. E voltou.",
		"mo.alone_ok": "{who.cap} ficou sozinh{who:o|a|o} {house.in} e está bem.",
		"mo.clean": "{house.in.cap} dormiram {list}. Todo mundo bem.",
		"mo.liar": "{who.cap} disse que ia {said.to}, mas dormiu {house.in}.",
		"mo.creature": "O amuleto {house.of} estava quebrado. A coisa da mata levou {who}.",
		"mo.talisman_cracked": "O amuleto {house.of} rachou. De dia dá pra consertar.",
		"mo.talisman_broken": "O amuleto {house.of} quebrou. De dia dá pra consertar.",
		"mo.saved_upyr": "{house.in.cap}, um dos nossos atacou {who}, mas {healer} cuidou {who:dele|dela|de você}.",
		"mo.saved_creature": "{house.in.cap}, a coisa da mata atacou {who}, mas {healer} cuidou {who:dele|dela|de você}.",
		"mo.saved_mimic": "{house.in.cap}, o Imitador atacou {who}, mas {healer} cuidou {who:dele|dela|de você}.",
		"mo.tunnel": "{who.cap} ficou do lado de fora {from.of} e passou pelo túnel {house.to}.",
		"mo.mimic_kill": "{house.in.cap} deixaram entrar a voz de {voice}. Não era {voice}: o Imitador levou {who}.",
		"mo.mimic_spared": "{house.in.cap} deixaram entrar a voz de {voice}. Não era {voice}, mas todo mundo chegou vivo de manhã.",
		"mo.mimic_knock": "De noite bateram na porta {house.of} com a voz de {voice}. Ninguém abriu. Era o Imitador.",
		"mo.mimic_knock_away": "De noite bateram na porta {house.of} com a voz de {voice}. Ninguém abriu. E {voice} estava {away.in} nessa hora.",
		"list.sep": ", ",
		"night.dusk": "Escurece. O sino toca.",
		"night.dead": "Você não está mais aqui. A noite segue sem você.",
		"night.bell": "O sino tá tocando! Corra pra uma casa: toque nela.",
		"night.going": "iam: {list}",
		"night.pact": "trato com {who}",
		"night.tunnel": "túnel {house.to}",
		"night.tal_broken": "amuleto quebrado",
		"night.tal_cracked": "amuleto rachado",
		"night.rule": "Quem chega primeiro na porta fica dentro e decide quem entra. Se não escolher a casa enquanto o sino toca, você corre por último pra onde tinha dito.",
		"night.heal": "Pegar ervas: esta noite salvo um vizinho",
		"night.hint": "O sino toca pouco. Toque numa casa na praça ou na lista e corra. Quem chega primeiro na porta decide quem entra.",
		"night.heal_on": "Ervas na mão: se atacarem alguém perto de você, você cuida",
		"night.first": "Você chega primeiro: você decide quem entra.",
		"night.ahead": "Na porta antes de você: {list}. Quem decide é {who}.",
		"night.run": "Correndo {house.to}. {rest}",
		"door.title": "Na porta",
		"door.hint_host": "Deixe entrar quem você confia. Se não abrir pra ninguém, fica sozinho, e sozinho não se sobrevive.",
		"door.hint_guest": "Escolha o que dizer pela porta. Quem está dentro lembra se vocês já dormiram juntos.",
		"door.hint_alone": "Sozinho aqui não se sobrevive. Da próxima vez, de dia, chame alguém pra vir com você.",
		"door.host": "Você chegou primeiro {house.in}. Estão batendo na porta.",
		"door.cap": "Dá pra deixar entrar: {n}",
		"door.quote": "“{text}”",
		"door.admit": "Deixar entrar",
		"door.admitting": "Entra",
		"door.elsewhere": "Em outras portas: {list}.",
		"door.upyr_note": "Quem você deixar entrar não vê a manhã.",
		"door.alone_note": "Se não abrir pra ninguém, fica sozinho e o amuleto apaga.",
		"door.open": "Abrir a porta",
		"door.refuse": "Não abrir pra ninguém",
		"door.locked": "{house.the.cap} já está trancad{house:o|a} por dentro. Lá dentro está {who}.",
		"door.rivals": "Na porta com você: {list}. Não tem lugar pra todo mundo.",
		"door.mimic": "No escuro, atrás de você, alguém fala com a voz de {voice}. Mas {voice} não está aqui.",
		"door.say": "O que você diz pela porta?",
		"door.knock": "Você bate na porta {house.of}…",
		"door.let_in": "O trinco estala. {who} deixa você entrar.",
		"door.shut": "Os passos se afastam da porta. Você fica do lado de fora.",
		"door.hatch": "Atrás da casa tem um alçapão. O túnel leva {house.to}, e lá tem lugar. Quem passar fica dentro, mas de manhã todo mundo vai saber de onde veio.",
		"door.tunnel": "Passar pelo túnel {house.to}",
		"door.wait": "Esperar o amanhecer",
		"door.alone": "Você chegou primeiro {house.in}. Ninguém mais veio.",
		"door.alone_upyr": "Um lobisomem sozinho não tem medo da rua.",
		"door.alone_human": "O amuleto pisca. Sozinho, você não segura até de manhã.",
		"day.journal": "Registro",
		"day.journal_n": "Registro ({n})",
		"day.dead": "Você não está mais aqui. Só pode assistir.",
		"day.skip": "Pular o dia",
		"day.defend": "Se defender",
		"day.invite": "Chamar…",
		"day.accuse": "Acusar…",
		"day.say": "Dizer…",
		"day.bell": "Reunião!",
		"day.ready": "Pronto pra noite",
		"day.hint": "Toque num morador: acuse, chame pra ir junto ou pergunte onde vai dormir. Toque no ícone de um trabalho: as provisões acendem os lampiões à noite.",
		"day.bell_ask": "Tocar o sino? Todo mundo se reúne pra votar na hora. Só uma vez por partida.",
		"day.bell_do": "Tocar o sino",
		"day.preview": "{who}: {text}",
		"day.say_aloud": "Dizer em voz alta",
		"day.person_ev": "{who} · {ev}",
		"day.p_accuse": "Acusar: “É {who}”",
		"day.p_invite": "Chamar pra passar a noite",
		"day.p_ask": "Perguntar onde vai dormir",
		"day.p_elder": "Ver os desenhos do Ancião: o que {who:ele|ela} é?",
		"day.work": "Trabalhar: {job.low}",
		"day.spoil": "Estragar o que foi feito {place}",
		"day.who_accuse": "Acusar quem?",
		"day.who_invite": "Chamar quem?",
		"day.where_with": "Pra onde você vai com {who}?",
	}
