extends Gram
## Türkçe. Masallardan bir köy: kavuklu Nasreddin Hoca, kel Keloğlan, gölge oyunundan Karagöz ile Hacivat,
## fesli Mehmet ve sokak kedisi Pamuk. Canavar burada hortlak. Kadın-erkek ayrımı yok;
## özel isimlere ek kesme işaretiyle gelir: Ayşe'yi, Mehmet'in, Pamuk'a.


func code() -> String:
	return "tr"


const _BACK := "aıou"
const _VOWELS := "aıoueiöü"
const _HARD := "fstkçşhp"


func _last_vowel(w: String) -> String:
	var low := w.to_lower()
	for i in range(low.length() - 1, -1, -1):
		var c := low.substr(i, 1)
		if _VOWELS.contains(c):
			return c
	return "e"


## İki yollu: a / e.
func _h2(w: String) -> String:
	return "a" if _BACK.contains(_last_vowel(w)) else "e"


## Dört yollu: ı / i / u / ü.
func _h4(w: String) -> String:
	match _last_vowel(w):
		"a", "ı": return "ı"
		"e", "i": return "i"
		"o", "u": return "u"
	return "ü"


func name_case(name: String, case: String, _female: bool) -> String:
	if name.is_empty():
		return name
	var last := name.right(1).to_lower()
	var vow := _VOWELS.contains(last)
	var d := "t" if _HARD.contains(last) else "d"
	match case:
		"acc": return name + "'" + ("y" if vow else "") + _h4(name)
		"gen": return name + "'" + ("n" if vow else "") + _h4(name) + "n"
		"dat": return name + "'" + ("y" if vow else "") + _h2(name)
		"loc": return name + "'" + d + _h2(name)
		"abl": return name + "'" + d + _h2(name) + "n"
		"ins": return name + "'" + ("y" if vow else "") + "l" + _h2(name)
	return name


func plural_index(_n: int) -> int:
	return 0


func data() -> Dictionary:
	return {
		"and": " ve ",
		"you": {"nom": "sen", "acc": "seni", "gen": "senin", "dat": "sana", "loc": "sende", "abl": "senden", "ins": "seninle"},
		"you_name": "Sen",
		"someone": {"nom": "başka biri", "acc": "başka birini", "gen": "başka birinin", "dat": "başka birine", "loc": "başka birinde", "abl": "başka birinden", "ins": "başka biriyle"},
		## nom — tabela ve liste; in — «ahırda»; to — «ahıra»; of — «ahırın»; from — «ahırdan».
		"houses": [
			{"nom": "Dere Evi", "in": "dere evinde", "to": "dere evine", "of": "dere evinin", "from": "dere evinden"},
			{"nom": "Ahır", "in": "ahırda", "to": "ahıra", "of": "ahırın", "from": "ahırdan"},
			{"nom": "Çan Kulesi", "in": "çan kulesinde", "to": "çan kulesine", "of": "çan kulesinin", "from": "çan kulesinden"},
			{"nom": "Mahzen", "in": "mahzende", "to": "mahzene", "of": "mahzenin", "from": "mahzenden"},
			{"nom": "Garaj", "in": "garajda", "to": "garaja", "of": "garajın", "from": "garajdan"},
		],
		"names": [
			["Leyla", true], ["Hoca", false], ["Ayşe", true], ["Keloğlan", false], ["Zeynep", true], ["Karagöz", false],
			["Hacivat", false], ["Elif", true], ["Mehmet", false], ["Emine", true], ["Pamuk", false], ["Fatma", true],
		],
		"looks": "res://config/looks_tr.tres",
		"ph.ANNOUNCE": [
			"Bu gece {house.in} kalıyorum.",
			"{house.to.cap} gidiyorum. Benimle gelen var mı?",
			"Bilin diye söylüyorum, {house.in} yatacağım.",
			"{house.nom}. Karar verdim.",
		],
		"ph.ACCUSE_STRONG": [
			"{who}, sabaha nasıl sağ çıktığını anlat bakalım.",
			"Bence her şey belli. {who}.",
			"Her şey olduğunda {who} tam oradaydı. Tesadüf mü?",
			"Ben {who.acc} çıkarmaktan yanayım. Başka yolu yok.",
		],
		"ph.ACCUSE_STREET": [
			"{who} geceyi dışarıda geçirdi ve geri döndü. İnsan bunu yapamaz.",
			"{who}, bütün gece dışarıdaydın. Söyleyecek bir şeyin yok mu?",
		],
		"ph.ACCUSE_LIAR": [
			"{who} {house.to} gideceğini söyledi, ama başka yerde yattı. Neden yalan?",
			"{who}, sen başka yere gidiyordun. Ne değişti?",
		],
		"ph.DEFEND": [
			"Evet, oradaydım. Ne olmuş?",
			"Ben hortlak değilim. Bu gece beni deneyin.",
			"Sadece yanlış odaya düştüm.",
			"Beni şimdi kovarsanız, sabah iki kişi daha eksik olur.",
		],
		"ph.UPYR_DEFLECT": [
			"Yerinizde olsam {who.acc} izlerdim.",
			"Siz tartışıyorsunuz, gece geliyor.",
			"Acele etmeyelim. Yanılırsak kendimizden birini kaybederiz.",
			"{who}, neden hep susuyorsun?",
			"Dün sessiz durdum ve hayatta kaldım. Demek ki doğru yaptım.",
		],
		"ph.FILLER": [
			"Gittikçe azalıyoruz. Sayın bakın.",
			"Hızlı karar verelim, hava kararıyor.",
			"Kimseye güvenmiyorum. Hiç kimseye.",
			"Şu an biriniz yalan söylüyor.",
		],
		"ph.REPLY_TO_ACCUSED_HUMAN": [
			"Ben mi? Ciddi misin? Sen asıl {who.acc} bir izle.",
			"Beni biriyle karıştırıyorsun.",
			"Peki. Kovun beni. Sabah anlarsınız.",
		],
		"ph.REPLY_TO_ACCUSED_UPYR": [
			"Komik. Asıl senden bahsedelim.",
			"Kendi adamını böyle batırırlar. Ne kadar kolay.",
			"Beni kovmak için çok acele ediyorsun. Şüpheli.",
		],
		"ph.AGREE_ACCUSE": [
			"Katılıyorum. {who} benim de hoşuma gitmiyor.",
			"Destekliyorum. {who}.",
		],
		"ph.DISAGREE_ACCUSE": [
			"Yok, {who} iyi birine benziyor. Senin derdin ne?",
			"Zayıf. Kanıt nerede?",
		],
		"ph.INVITE_YES": [
			"Olur. {house.in} buluşalım.",
			"Tamam, seninle {house.to} geliyorum.",
			"Anlaştık. Yeter ki beni yarı yolda bırakma.",
		],
		"ph.INVITE_NO": [
			"Yok, seninle gelmem. Alınma.",
			"Sana henüz güvenmiyorum.",
			"Benim zaten biri var.",
		],
		"ph.ASK_ANSWER_HUMAN": [
			"{house.in.cap} kalıyorum. Saklamıyorum.",
			"Söyledim ya: {house.nom}.",
		],
		"ph.ASK_ANSWER_UNSURE": [
			"Daha karar vermedim.",
			"Bakalım kim nereye gidiyor.",
		],
		"ph.PLAYER_DEFEND_REACTION": [
			"Hıh.",
			"Göreceğiz.",
			"Herkes böyle der.",
			"Peki, inanıyorum. Şimdilik.",
		],
		"ph.GENERIC_REACTION": [
			"Bununla ne demek istiyorsun?",
			"Güzel konuşuyorsun. Fazla güzel.",
			"Bunu kendine mi anlatıyorsun, bize mi?",
			"Duydum. İkna olmadım.",
		],
		"ph.AT_PLAYER": [
			"En çok soru sorduğum kişi sensin.",
			"Fazla sakinsin.",
			"Bir şey saklıyorsun.",
			"Sen önce kendine bak.",
			"Sana güvenmiyorum. Hiç.",
		],
		"ph.PLEA_AFTER_STREET": [
			"Dün de beni içeri almadılar. İkinci kez dayanamam.",
			"Bütün gece dışarıda oturdum. Aç kapıyı.",
		],
		"ph.PLEA_SUSPECT": [
			"Nasıl göründüğünü biliyorum. Ama ben hortlak değilim.",
			"Bir kere inan. Sonra istersen kov.",
		],
		"ph.PLEA_NORMAL": [
			"Aç, burası soğuk.",
			"Benim. Al beni içeri.",
			"İkimiz sabaha kadar dayanırız.",
			"Çabuk ol, dışarıda bir şey dolaşıyor.",
		],
		"ph.PLEA_PACT": [
			"Benim, anlaşmıştık.",
			"Aç, sözleştiğimiz gibi.",
		],
		"ph.JOB_FAKE": [
			"{who} {place} durup duruyordu, ortada bir şey yok.",
			"Gördüm: {who} {place} oyalandı, hiçbir şey yapmadı.",
			"Tuhaf. {who} {place} dolaştı, ama erzak artmadı.",
			"{who} sadece çalışıyormuş gibi yapıyor. {place.cap} idi: boş.",
			"{who} {place} ne yapıyordu? Kovalar hâlâ bomboş.",
		],
		"ph.JOB_FAKE_AT_PLAYER": [
			"Sen {place} sadece vakit kaybediyorsun. Erzak artmadı.",
			"Sen {place} çalışıyormuş gibi yapıyorsun. Gördüm.",
			"Senin {place} ne faydan var? Kovalar hâlâ boş.",
		],
		"ph.MIMIC_PLEAS": [
			"Al beni içeri. Benim. Benim, {who}. Al beni içeri.",
			"Aç, lütfen. Lütfen. Soğuk. Soğuk.",
			"Beni tanıyorsun. Aç kapıyı. Aç kapıyı.",
			"Eve geldim. Eve al beni.",
		],
		"ph.SABOTAGE_SEEN": [
			"{who} {place} dolanıyordu, şimdi her şey berbat.",
			"{who.acc} {place} bir şey yaparken gördüm. O yaptı.",
			"Erzakı kim bozuyor? {place} en son {who} vardı.",
		],
		"ph.SABOTAGE_SEEN_AT_PLAYER": [
			"Sen {place} ne yapıyorsun? Gördüm: senden sonra her şey berbat.",
			"{place.cap} senden sonra her şey bozuldu. Gördüm.",
		],
		"ph.ELDER_UPYR": [
			"Ben köyün yaşlısıyım. Resimlere baktım: {who} bir hortlak.",
			"Dinleyin. Ben köyün yaşlısıyım ve resimlerde {who} insan değil.",
		],
		"ph.ELDER_HUMAN": [
			"Ben köyün yaşlısıyım. {who} insan, kontrol ettim.",
			"Resimlere göre {who} temiz. Ben köyün yaşlısıyım, bana güvenebilirsiniz.",
		],
		"ph.MEETING_CALL": [
			"Yeter bu laf. Şimdi oylayalım: {who}.",
			"Çanı çalıyorum. {who} yalan söylüyor, hava kararmadan karar verelim.",
			"Toplanın. {who.ins} yan yana yatmam.",
		],
		"ph.BOX_NOTE": [
			"Sandıkta bir not var: “{a} ya da {b}”. İkisinden biri hortlak.",
			"Sandığı açtım. İçinde not: “{a} ya da {b}. İkisinden biri insan değil”.",
		],
		"ph.BOX_OIL": [
			"Sandıkta fener yağı var. Bu gece daha aydınlık olacak.",
			"Sandığı açtım: yağ. Fenerleri dolduralım.",
		],
		"ph.BOX_CHALK": [
			"Sandıkta tebeşir var. {house.of.cap} muskasını yeniden çizdim.",
		],
		"plea.shared.label": "Daha önce birlikte kaldık",
		"plea.shared.text": "Bir gece birlikte kaldık ve hiçbir şey olmadı.",
		"plea.promise.label": "Yarın açacağına söz ver",
		"plea.promise.text": "Al beni içeri. Yarın kapıyı ilk sana açarım.",
		"plea.name.label": "Hortlağı söyle",
		"plea.name.text": "Kim olduğunu biliyorum. Al beni içeri, anlatayım.",
		"plea.beg.label": "Yalvar",
		"plea.beg.text": "Lütfen. Dışarıda kimse sağ kalmaz.",
		"spoil.water": "kovalar devrilmiş",
		"spoil.wood": "odunlar çamura saçılmış",
		"spoil.lamp": "yağ dökülmüş",
		"spoil.fish": "balıklar nehre geri atılmış",
		"spoil.any": "her şey bozulmuş",
		"quick.house": "{house.in.cap} kalıyorum. Benimle gelen var mı?",
		"quick": ["Ben hortlak değilim. Yemin ederim.", "Dışarıdan dönen hortlaktır.", "İkişer ikişer duralım.", "Nerede yattığı hakkında yalan söyleyen gitsin."],
		"intent.accuse": ["hortlak", "o yaptı", "yalan", "yalancı", "şüphe", "güvenmiyorum", "kov", "katil", "suçlu"],
		"intent.invite": ["gel", "benimle", "birlikte", "beraber", "gidelim"],
		"intent.defend": ["ben değilim", "değilim", "insanım", "yemin", "masum", "güvenin"],
		"intent.ask": ["nerede", "nereye", "hangi ev"],
		"intent.houses": ["dere", "ahır", "kule", "mahzen", "garaj"],
		"ev.street": "dışarıdan sağ döndü",
		"ev.times": " ({n} kez)",
		"ev.liar": "nerede yatacağı hakkında yalan söyledi",
		"ev.death": "biri öldüğünde yakındaydı",
		"ev.fake": "boşuna çalıştı",
		"ev.sabotage": "bozulan bir işin başındaydı",
		"ev.tunnel": "tünelden başka bir eve girdi",
		"ev.sep": "; ",
		"sys.sabotage": "Biri {place} yaramazlık yaptı: {what}. Erzak azaldı.",
		"claim.elder_upyr": "kendini köyün yaşlısı ilan etti: {who} hortlak",
		"claim.elder_human": "kendini köyün yaşlısı ilan etti: {who} insan",
		"claim.healer": "{role}: {n}. gece {who.acc} iyileştirdi",
		"when.night": "{n}. gece",
		"when.day": "{n}. gün",
		"chron.line": "{title}: {text}",
		"chron.morning": "Sabah: {text}",
		"log.exiled": "köy {who.acc} sürdü.",
		"log.supplies": "toplanan erzak: %{p}.",
		"log.tunnel": "{who.cap} {from.to} alınmadı ve tünelden {house.to} {who:geçti|geçti|geçtin}.",
		"log.street_upyr": "{who.cap} {house.to} alınmadı, ama sabaha kadar {who:dayandı|dayandı|dayandın}.",
		"log.street_dead": "{who.cap} {house.to} alınmadı. {who:Sabah sokakta bulundu.|Sabah sokakta bulundu.|Sokakta öldün.}",
		"log.street_ok": "{who.cap} geceyi dışarıda {who:geçirdi ve hayatta kaldı|geçirdi ve hayatta kaldı|geçirdin ve hayatta kaldın}.",
		"log.mimic_knock": "{house.of} kapısını {voice.gen} sesiyle çaldılar. Kimse açmadı.",
		"log.mimic_spared": "{house.in} {voice.gen} sesini içeri aldılar. O değildi, ama sabaha herkes sağ çıktı.",
		"log.mimic_kill": "{house.in} {voice.gen} sesini içeri aldılar. Taklitçiydi: {who.acc} alıp götürdü.",
		"log.alone_dead": "{who.cap} {house.in} yalnız {who:kaldı|kaldı|kaldın}. Muska söndü.",
		"log.killed": "{who.cap} {house.in} {who:öldü|öldü|öldün}. Yanında: {others}.",
		"log.clean": "{house.in} {list} kaldı. Herkes sağ.",
		"log.creature": "{house.of} muskası kırıktı. Ormandaki yaratık {who.acc} götürdü.",
		"log.liar": "{who.cap} {said.to} gideceğini söyledi, ama {house.in} {who:yattı|yattı|yattın}.",
		"log.talisman_cracked": "{house.of} muskası çatladı.",
		"log.talisman_broken": "{house.of} muskası kırıldı.",
		"log.saved": "{house.in} {who.dat} saldırdılar, ama {healer} {who.acc} {h:iyileştirdi|iyileştirdi|iyileştirdin}.",
		"log.meeting": "{who.cap} çanı {who:çaldı|çaldı|çaldın}: acil toplantı.",
		"log.event": "{e}.",
		"sys.dawn1": "Şafak söküyor. Herkes meydana çıkıyor.",
		"sys.dawn": "{d}. gün. Hayatta kalan: {n}.",
		"job.water.title": "Su taşı",
		"job.water.place": "kuyu başında",
		"job.water.done": "Sabaha kadar su var.",
		"job.wood.title": "Odun kır",
		"job.wood.place": "odun yığınının yanında",
		"job.wood.done": "Bütün gece yetecek odun var.",
		"job.lamp.title": "Fenerleri doldur",
		"job.lamp.place": "fenerin yanında",
		"job.lamp.done": "Fenerler dolu.",
		"job.fish.title": "Balık tut",
		"job.fish.place": "nehir kıyısında",
		"job.fish.done": "Akşam yemeğine balık var.",
		"job.talisman.title": "Muskayı onar",
		"job.talisman.place": "muskanın yanında",
		"job.talisman.done": "Muska yepyeni oldu.",
		"job.box.title": "Sandığı aç",
		"job.box.place": "sandığın yanında",
		"role.elder": "Köyün Yaşlısı",
		"role.elder.mid": "köyün yaşlısı",
		"role.healer": "Şifacı",
		"role.healer.mid": "şifacı",
		"role.headman": "Muhtar",
		"role.headman.mid": "muhtar",
		"role.named": "{role} {who}",
		"event.fog.title": "Sis",
		"event.fog.mid": "sis",
		"event.fog.text": "Sis çanın sesini boğuyor: koşmaya daha az vakit var, sokak daha tehlikeli.",
		"event.moon.title": "Dolunay",
		"event.moon.mid": "dolunay",
		"event.moon.text": "Dolunay: sabaha kadar bütün muskalar zayıflayacak.",
		"event.quiet.title": "Sakin gece",
		"event.quiet.mid": "sakin gece",
		"event.quiet.text": "Sakin gece: sokak daha güvenli, Taklitçi gelmeyecek.",
		"event.rain.title": "Sağanak",
		"event.rain.mid": "sağanak",
		"event.rain.text": "Sağanak fenerleri boğuyor: erzaktaki yağ bu gece işe yaramaz.",
		"recap.street_host": "Seni {house.to} almadılar: kapıda {who} vardı.",
		"recap.street": "Geceyi dışarıda geçirdin. Orada neredeyse herkes ölür.",
		"recap.street_p": "O gece dışarıda ölme ihtimali: %{p}.",
		"recap.killer": "Seni {who} öldürdü. O bir hortlaktı.",
		"recap.you_opened": "Kapıyı {who.dat} sen kendin açtın.",
		"recap.killer_opened": "Kapıyı sana bizzat {who} açtı.",
		"recap.near": "Yanında: {others}.",
		"recap.alone": "{house.in.cap} yalnız kaldın. Tek kişi muskayı sabaha kadar tutamaz.",
		"recap.alone_p": "O evde yalnız ölme ihtimali: %{p}. Gündüz birini yanına çağır.",
		"recap.creature": "{house.of.cap} muskası kırıktı ve ormandaki yaratık içeri girdi.",
		"recap.creature_tip": "Muska gündüz onarılabilirdi: meydandaki işlerden biri.",
		"recap.mimic_you": "Kapıyı {voice.gen} sesine açtın. Taklitçiydi.",
		"recap.mimic_host": "{who} {voice.gen} sesini içeri aldı. Taklitçiydi.",
		"recap.voice_dead": "{voice} o sırada çoktan ölmüştü.",
		"recap.voice_away": "{voice} ise o sırada {house.in} idi.",
		"recap.exiled": "{d}. gün sürüldün. Aleyhine oy verenler: {list}.",
		"recap.exiled_many": "{d}. gün sürüldün. Aleyhine: çoğunluk.",
		"recap.seen": "Köy şunu gördü: {ev}.",
		"recap.exiled0": "Sürüldün.",
		"recap.died": "{n}. gece öldün. {why}",
		"verdict.mimic": "{n}. gece kapıyı Taklitçiye, {voice.gen} sesine açtın.",
		"verdict.let_upyr": "{n}. gece {who.acc} içeri aldın ve o bir hortlaktı.",
		"verdict.vote_upyr": "{n}. gün oyun bir hortlağın sürülmesine yardım etti: {who}.",
		"verdict.vote_human": "{n}. gün {who} aleyhine oy verdin ve o bir insandı.",
		"verdict.clean": "Kapıyı hiç hortlağa açmadın ve şafağı gördün.",
		"verdict.dead": "Şafağı göremedin.",
		"verdict.kills": " Hesabında: {n}.",
		"verdict.upyr_won": "Köy hortlağın sen olduğunu hiç anlamadı.",
		"verdict.upyr_lost": "Şafağı gördün, ama köy dayandı.",
		"sys.box": "Meydanın kenarında bir sandık duruyor. Dün yoktu.",
		"sys.elder_upyr": "Köyün yaşlısının resimleri: {who} hortlak. Bunu yalnızca sen biliyorsun.",
		"sys.elder_human": "Köyün yaşlısının resimleri: {who} insan. Bunu yalnızca sen biliyorsun.",
		"sys.bell_you": "Çanı çalıyorsun. Acil toplantı!",
		"sys.bell": "{who} çanı çalıyor. Acil toplantı!",
		"box.note": "Sandıkta bir not: “{a.cap} ya da {b}”. İkisinden biri hortlak. Notu yalnızca sen görüyorsun.",
		"box.oil": "Sandıkta fener yağı var: erzak +{n}.",
		"box.chalk": "Sandıkta tebeşir var: {house.of} muskası yeniden çizildi.",
		"box.empty": "Sandık boş.",
		"say.accuse": "Bence bu {who}.",
		"say.invite": "{who}, birlikte {house.to} gidelim mi?",
		"say.ask": "{who}, bu gece nerede kalıyorsun?",
		"say.defend": ["Ben hortlak değilim. Yemin ederim.", "Ben sizdenim. Bu gece beni deneyin.", "Ben değilim. Aramaya devam edin."],
		"toast.elder_upyr": "Resimler: {who} hortlak",
		"toast.elder_human": "Resimler: {who} insan",
		"toast.box_taken": "Sandığı biri zaten açtı",
		"toast.job_done": "“{job}”: bugünlük bitti",
		"toast.box": "Meydanda bir sandık belirdi",
		"toast.back_exit": "Çıkmak için tekrar bas",
		"quit.ask": "Oyunu bırakmak mı?",
		"quit.stay": "Kal",
		"quit.leave": "Menüye dön",
		"cfg.players": "Oyuncu",
		"cfg.monsters": "Hortlak",
		"cfg.shelters": "Sığınak",
		"cfg.capacity": "Sığınak başına yer",
		"cfg.nights": "Şafağa kadar gece",
		"cfg.day_seconds": "Gündüz, saniye",
		"cfg.door_seconds": "Kapıda karar, saniye",
		"cfg.run_seconds": "Eve koşu, saniye",
		"cfg.outside_death": "Dışarıda ölüm, %",
		"cfg.first_night_outside_death": "İlk gece aynısı, %",
		"cfg.vote_from_day": "Sürgün hangi günden",
		"diff.easy": "Kolay",
		"diff.normal": "Normal",
		"diff.hard": "Zor",
		"diff.custom": "Özel",
		"diff.cast": "{p} köylü, {u} hortlak.",
		"diff.human": " Sen hep insansın.",
		"diff.easy_note": " Gündüz daha uzun.",
		"diff.hard_note": " Gündüz daha kısa, sokak daha tehlikeli.",
		"diary.exiled": "{n}. gün sürüldü.",
		"diary.died": "{n}. gece öldü.",
		"diary.night": "{n}: {where}",
		"diary.street": "dışarıda",
		"diary.said": " (dediği: {house})",
		"diary.nights": "Geceler: {list}.",
		"diary.today": "Bu gece gideceği yer: {house}.",
		"diary.evidence": "İpuçları: {ev}.",
		"diary.own_claim": "{text}.",
		"diary.claim": "{who.cap} {text}.",
		"diary.seen_upyr": "Senin resimlerin: hortlak.",
		"diary.seen_human": "Senin resimlerin: insan.",
		"diary.nothing": "Henüz bir şey bilinmiyor.",
		"diary.head": "Günlük: herkes hakkında bilinenler",
		"diary.gone": "{who} · öldü",
		"journal.who": "{who}:",
		"journal.head": "Günün kaydı",
		"ui.close": "Kapat",
		"ui.cancel": "Vazgeç",
		"say.placeholder": "Ya da kendin yaz",
		"say.send": "Söyle",
		"chip.exiled": " · sürgün",
		"supplies": "Erzak {a}/{b}",
		"howto.art_accuse": "Hortlak sensin!",
		"howto.art_street": "‹ dışarıda",
		"howto.art_door": "İçeri alayım mı?",
		"game.title": "Al Beni İçeri",
		"menu.tale": "Gece sokakta kimse sağ kalmaz.\nSığınak, insandan az.\n\nBiri kapıda durmuş, içeri alınmak için yalvarıyor. İçerideki biri karar veriyor.",
		"menu.hint": "Hortlaklar aranızda. Birbirlerini bile tanımıyorlar.",
		"menu.howto": "Nasıl oynanır",
		"menu.play": "Oyna",
		"lang.pick": "Dil",
		"diff.note": "{d}: {text}",
		"diff.note_custom": "Özel zorluk: {text}",
		"settings.title": "Ayarlar",
		"settings.lang": "Dil",
		"settings.sound": "Ses",
		"settings.music": "Müzik",
		"settings.sfx": "Efektler",
		"settings.ambience": "Ortam",
		"settings.haptics_on": "Titreşim: açık",
		"settings.haptics_off": "Titreşim: kapalı",
		"settings.difficulty": "Zorluk",
		"settings.hints": "İpuçlarını yeniden göster",
		"settings.hints_reset": "İpuçları yeniden görünecek",
		"settings.note": "Her seviye 1500 oyunla denendi. Dengeyi en çok sığınak ve gece sayısı değiştirir.",
		"settings.start": "Bu ayarlarla başla",
		"ui.back": "Geri",
		"howto.day.title": "Gündüz",
		"howto.day.text": "Köyde insanlar yaşıyor, aralarında hortlaklar da var. Hortlaklar herkes gibi görünür. Sen fenerli bir köylüsün.\n\nGündüz herkes meydandadır. Bir köylüye dokun: onu suçla, geceyi birlikte geçirmeye çağır ya da nerede kalacağını sor. Başının üstündeki kırmızı göz, köyün ondan şüphelendiği anlamına gelir.\n\nBir iş simgesine dokun: su, odun, fenerler. Erzak ne kadar çoksa gece o kadar aydınlık olur. Hortlaklar çalışıyormuş gibi yapar, hatta yapılanı bozar. Bazen meydanda bir sandık belirir: ilk açan içindekini alır.",
		"howto.night.title": "Gece",
		"howto.night.text": "Akşam çan çalar ve herkes evine koşar. Çan çalarken bir eve dokun. Sığınak insandan az: dışarıda kalan sabahı zor görür.\n\nEvde yalnız kalmak da tehlikeli. Gündüz kiminle kalacağına karar ver ve çatlamış muskayı onar: muskası kırık eve ormandaki yaratık girer.",
		"howto.door.title": "Kapı",
		"howto.door.text": "Eve ilk varan kimin gireceğine karar verir.\n\nBir hortlağı içeri alırsan sabahı göremezsin. Kimseyi almazsan yalnız kalırsın. Sabah kimin nerede yattığına ve kimin yalan söylediğine bak.\n\nBazen kapıyı, şu an başka bir evde olan ya da çoktan ölmüş birinin sesiyle çalarlar. Bu Taklitçidir: açma.\n\nBazı insanların görevi vardır: Köyün Yaşlısı, Şifacı, Muhtar. Oyun başına bir kez gündüz çanı çalıp hemen oylamaya geçebilirsin. Herkes hakkında bilinen her şey Günlük'te.",
		"howto.title": "Nasıl oynanır · {a}/{b}",
		"howto.got_it": "Anladım",
		"ui.next": "İleri",
		"ui.skip": "Geç",
		"crash.title": "Rapor",
		"crash.head": "Önceki oturum beklenmedik şekilde kapandı",
		"crash.text": "Bu oyunun hatası, senin değil. “Raporu kopyala”ya dokun ve bize gönder: her şeyin hangi adımda durduğu görünüyor.",
		"crash.steps": "Son adımlar:",
		"crash.copy": "Raporu kopyala",
		"crash.copied": "Kopyalandı: sohbete yapıştır",
		"ui.continue": "Devam",
		"prologue.title": "İlk geceden önce",
		"prologue.pre": "Senin rolün…",
		"prologue.upyr": "Sen bir hortlaksın",
		"prologue.human": "Sen bir insansın",
		"prologue.upyr_text": "Senin gibi başka kim var, bilmiyorsun. Sokak seni korkutmaz, seninle aynı kapının ardında kalan sabahı göremez. Gündüz insan gibi konuş.",
		"prologue.human_text": "Gece dışarıda neredeyse kesin ölürsün. Sığınakta yalnız kalamazsın: muska söner. Bir kişi daha lazım, ama hangisinin insan olduğunu bilmiyorsun.",
		"prologue.facts": "{p} köylü, {u} hortlak. {s} sığınak, her birinde {c} yer. {n}. şafağa kadar dayanmalısın.",
		"prologue.go": "İnsanların yanına çık",
		"prologue.elder": "Sen köyün yaşlısısın. Oyun başına bir kez gündüz bir köylüye dokun ve resimlere bak: hortlak olup olmadığını öğrenirsin. Yalnızca sen.",
		"prologue.healer": "Sen şifacısın. Oyun başına bir kez geceden önce otlarını al: evde yanında biri saldırıya uğrarsa onu iyileştirirsin.",
		"prologue.headman": "Sen muhtarsın. Sürgünde oyun iki sayılır.",
		"end.title": "Değerlendirme",
		"end.people": "İnsanlar dayandı",
		"end.upyri": "Köy boşaldı",
		"end.won": "Senin tarafın kazandı.",
		"end.lost": "Senin tarafın kaybetti.",
		"end.who": "Kim kimdi",
		"end.upyr": "hortlak",
		"end.human": "insan",
		"end.with_role": "{a}, {role}",
		"end.chip": "{who}: {what}",
		"end.how": "Nasıl geçti",
		"end.again": "Yeniden oyna",
		"end.verdict": "Oyunu ne belirledi",
		"end.offer_easier": "Kolaylaştıralım mı?",
		"end.offer_harder": "Üst üste iki zafer. Daha zorunu dener misin?",
		"end.easier": "Kolaylaştır",
		"end.harder": "Daha zor dene",
		"vote.title": "Sürgün",
		"vote.bell_you": "Acil toplantı: çanı sen çaldın.",
		"vote.bell": "Acil toplantı: çanı {who} çaldı.",
		"vote.ask": "Köyden kimi kovalım? Sürülen sonsuza dek gider. Ne olduğunu sonunda öğreneceksiniz.",
		"day.diary": "Günlük",
		"vote.headman": "Sen muhtarsın: oyun iki sayılır.",
		"vote.dead": "Öldün, sadece izliyorsun.",
		"vote.watch": "Sonucu gör",
		"vote.go": "Sür",
		"vote.none": "Kimse sürülmedi",
		"vote.gone": "{who} gitti",
		"vote.gone_you": "Sürüldün",
		"vote.row": "{who}: {n}",
		"vote.night": "Gece çöküyor",
		"mo.title": "Sabah",
		"mo.all_alive": "Herkes sağ",
		"mo.one_dead": "Biri eksik",
		"mo.dead_n": "Eksik: {n}",
		"mo.why": "Neden öldün",
		"mo.event": "Bu gece: {e}.",
		"mo.street_dead": "{who.cap} {house.to} alınmadı. {who:Sokakta bulundu.|Sokakta bulundu.|Sokakta öldün.}",
		"mo.alone_dead": "{who.cap} {house.in} yalnız {who:kaldı|kaldı|kaldın}. Muska söndü.",
		"mo.killed": "{who.cap} {house.in} {who:öldü|öldü|öldün}. Yanında: {others}.",
		"mo.street_ok": "{who.cap} geceyi dışarıda {who:geçirdi. Ve geri döndü.|geçirdi. Ve geri döndü.|geçirdin. Ve geri döndün.}",
		"mo.alone_ok": "{who.cap} {house.in} yalnız {who:kaldı ve sağ|kaldı ve sağ|kaldın ve sağsın}.",
		"mo.clean": "{house.in.cap} {list} kaldı. Herkes sağ.",
		"mo.liar": "{who.cap} {said.to} gideceğini söyledi, ama {house.in} {who:yattı|yattı|yattın}.",
		"mo.creature": "{house.of.cap} muskası kırıktı. Ormandaki yaratık {who.acc} götürdü.",
		"mo.talisman_cracked": "{house.of.cap} muskası çatladı. Gündüz onarılabilir.",
		"mo.talisman_broken": "{house.of.cap} muskası kırıldı. Gündüz onarılabilir.",
		"mo.saved_upyr": "{house.in.cap} bizden biri {who.dat} saldırdı, ama {healer} {who.acc} {h:iyileştirdi|iyileştirdi|iyileştirdin}.",
		"mo.saved_creature": "{house.in.cap} ormandaki yaratık {who.dat} saldırdı, ama {healer} {who.acc} {h:iyileştirdi|iyileştirdi|iyileştirdin}.",
		"mo.saved_mimic": "{house.in.cap} Taklitçi {who.dat} saldırdı, ama {healer} {who.acc} {h:iyileştirdi|iyileştirdi|iyileştirdin}.",
		"mo.tunnel": "{who.cap} {from.to} alınmadı ve tünelden {house.to} {who:geçti|geçti|geçtin}.",
		"mo.mimic_kill": "{house.in.cap} {voice.gen} sesini içeri aldılar. O değildi: Taklitçi {who.acc} götürdü.",
		"mo.mimic_spared": "{house.in.cap} {voice.gen} sesini içeri aldılar. O değildi, ama sabaha herkes sağ çıktı.",
		"mo.mimic_knock": "Gece {house.of} kapısını {voice.gen} sesiyle çaldılar. Kimse açmadı. Taklitçiydi.",
		"mo.mimic_knock_away": "Gece {house.of} kapısını {voice.gen} sesiyle çaldılar. Kimse açmadı. {voice} ise o sırada {away.in} idi.",
		"list.sep": ", ",
		"night.dusk": "Hava kararıyor. Çan çalıyor.",
		"night.dead": "Artık yoksun. Gece sensiz sürüyor.",
		"night.bell": "Çan çalıyor! Bir eve koş: ona dokun.",
		"night.going": "gidecekler: {list}",
		"night.pact": "{who.ins} anlaşma",
		"night.tunnel": "tünel: {house.nom}",
		"night.tal_broken": "muska kırık",
		"night.tal_cracked": "muska çatlak",
		"night.rule": "Kapıya ilk varan içeride olur ve kimin gireceğine karar verir. Çan çalarken ev seçmezsen, söylediğin yere en son koşarsın.",
		"night.heal": "Otları al: bu gece bir komşuyu kurtaracağım",
		"night.hint": "Çan uzun çalmaz. Meydandaki ya da listedeki bir eve dokun ve koş. Kapıya ilk varan kimin gireceğine karar verir.",
		"night.heal_on": "Otlar yanında: yanında biri saldırıya uğrarsa onu iyileştirirsin",
		"night.first": "İlk sen varacaksın: kimin gireceğine sen karar vereceksin.",
		"night.ahead": "Kapıda senden önce: {list}. Kararı {who} verecek.",
		"night.run": "{house.to.cap} koşuyorsun. {rest}",
		"door.title": "Kapıda",
		"door.hint_host": "Güvendiğin birini içeri al. Kimseye açmazsan yalnız kalırsın, yalnız da sağ kalınmaz.",
		"door.hint_guest": "Kapının ardından ne söyleyeceğini seç. Ev sahibi daha önce birlikte kalıp kalmadığınızı hatırlıyor.",
		"door.hint_alone": "Burada yalnız sağ kalınmaz. Bir dahaki sefere gündüz birini yanına çağır.",
		"door.host": "{house.to.cap} ilk sen vardın. Kapı çalınıyor.",
		"door.cap": "İçeri alabileceğin: {n}",
		"door.quote": "“{text}”",
		"door.admit": "İçeri al",
		"door.admitting": "Alıyorum",
		"door.elsewhere": "Diğer kapılarda: {list}.",
		"door.upyr_note": "İçeri aldığın sabahı göremeyecek.",
		"door.alone_note": "Kimseye açmazsan yalnız kalırsın ve muska söner.",
		"door.open": "Kapıyı aç",
		"door.refuse": "Kimseye açma",
		"door.locked": "{house.nom} içeriden çoktan kilitlendi. İçeride {who} var.",
		"door.rivals": "Kapıda seninle birlikte: {list}. Herkese yer yok.",
		"door.mimic": "Arkanda karanlıkta biri {voice.gen} sesiyle konuşuyor. Ama {voice} burada değil.",
		"door.say": "Kapının ardından ne diyeceksin?",
		"door.knock": "{house.of.cap} kapısını çalıyorsun…",
		"door.let_in": "Sürgü tıklıyor. {who} seni içeri alıyor.",
		"door.shut": "Adımlar kapıdan uzaklaşıyor. Dışarıda kalıyorsun.",
		"door.hatch": "Evin arkasında bir kapak var. Tünel {house.to} çıkıyor, orada yer var. Geçen içeride olur, ama sabah herkes nereden geldiğini öğrenir.",
		"door.tunnel": "Tünelden {house.to} geç",
		"door.wait": "Şafağı bekle",
		"door.alone": "{house.to.cap} ilk sen vardın. Başka kimse gelmedi.",
		"door.alone_upyr": "Yalnız bir hortlak sokaktan korkmaz.",
		"door.alone_human": "Muska titriyor. Yalnız onu sabaha kadar tutamazsın.",
		"day.journal": "Kayıt",
		"day.journal_n": "Kayıt ({n})",
		"day.dead": "Artık yoksun. Sadece izliyorsun.",
		"day.skip": "Günü geç",
		"day.defend": "Kendini savun",
		"day.invite": "Çağır…",
		"day.accuse": "Suçla…",
		"day.say": "Söyle…",
		"day.bell": "Toplantı!",
		"day.ready": "Geceye hazırım",
		"day.hint": "Bir köylüye dokun: suçla, yanına çağır ya da nerede kalacağını sor. Bir iş simgesine dokun: erzak gece fenerleri yakar.",
		"day.bell_ask": "Çanı çalalım mı? Herkes hemen oylamaya toplanır. Oyun başına bir kez yapılabilir.",
		"day.bell_do": "Çanı çal",
		"day.preview": "{who}: {text}",
		"day.say_aloud": "Yüksek sesle söyle",
		"day.person_ev": "{who} · {ev}",
		"day.p_accuse": "Suçla: “Bu {who}”",
		"day.p_invite": "Geceye çağır",
		"day.p_ask": "Nerede kalacağını sor",
		"day.p_elder": "Köyün yaşlısının resimlerine bak: o ne?",
		"day.work": "Çalış: {job.low}",
		"day.spoil": "Yapılanı boz ({place})",
		"day.who_accuse": "Kimi suçlayalım?",
		"day.who_invite": "Kimi çağıralım?",
		"day.where_with": "{who.ins} nereye gidiyorsun?",
	}
