extends Gram
## Tiếng Việt. Một làng cổ tích: chú Cuội, cô Tấm, chị Hằng, Thạch Sanh, Gióng,
## chú trâu Sửu và cô thỏ ngọc. Quái vật ở đây là ma cà rồng. Người chơi là «bạn».
## Tên không biến đổi. Cần người bản ngữ đọc lại trước khi phát hành.


func code() -> String:
	return "vi"


func plural_index(_n: int) -> int:
	return 0


func data() -> Dictionary:
	return {
		"and": " và ",
		"you": {"nom": "bạn", "acc": "bạn", "gen": "bạn", "dat": "bạn", "ins": "bạn"},
		"you_name": "Bạn",
		"someone": {"nom": "người khác", "acc": "người khác", "gen": "người khác", "dat": "người khác"},
		## nom — biển và danh sách; in — «ở kho thóc»; to — «đến kho thóc»; of — «kho thóc» (sau danh từ).
		"houses": [
			{"nom": "Nhà bên sông", "in": "ở nhà bên sông", "to": "đến nhà bên sông", "of": "nhà bên sông"},
			{"nom": "Kho thóc", "in": "ở kho thóc", "to": "đến kho thóc", "of": "kho thóc"},
			{"nom": "Tháp chuông", "in": "ở tháp chuông", "to": "đến tháp chuông", "of": "tháp chuông"},
			{"nom": "Hầm", "in": "dưới hầm", "to": "xuống hầm", "of": "hầm"},
			{"nom": "Nhà xe", "in": "ở nhà xe", "to": "đến nhà xe", "of": "nhà xe"},
		],
		"names": [
			["Tấm", true], ["Cuội", false], ["Hằng", true], ["Gióng", false], ["Lan", true], ["Sanh", false],
			["Minh", false], ["Mai", true], ["Hùng", false], ["Hoa", true], ["Sửu", false], ["Thỏ", true],
		],
		"looks": "res://config/looks_vi.tres",
		"ph.ANNOUNCE": [
			"Tối nay tôi ngủ {house.in}.",
			"Tôi đi {house.to}. Ai đi cùng không?",
			"Tôi ngủ {house.in}, báo trước vậy.",
			"{house.nom}. Quyết rồi.",
		],
		"ph.ACCUSE_STRONG": [
			"{who}, giải thích xem sao bạn sống được tới sáng.",
			"Với tôi thì rõ rồi. {who}.",
			"Lúc chuyện xảy ra, {who} ở ngay đó. Trùng hợp à?",
			"Tôi bỏ phiếu cho {who}. Không cần bàn.",
		],
		"ph.ACCUSE_STREET": [
			"{who} ngủ ngoài đường cả đêm mà vẫn về được. Người thường không làm nổi.",
			"{who}, bạn ở ngoài suốt đêm. Không định nói gì sao?",
		],
		"ph.ACCUSE_LIAR": [
			"{who} nói đi {house.to}, mà lại ngủ chỗ khác. Nói dối làm gì?",
			"{who}, bạn định đi chỗ khác cơ mà. Sao đổi?",
		],
		"ph.DEFEND": [
			"Ừ, tôi ở đó. Thì sao?",
			"Tôi không phải ma cà rồng. Đêm nay cứ thử tôi.",
			"Tôi chỉ xui chọn nhầm phòng.",
			"Đuổi tôi bây giờ, sáng mai các người sẽ mất thêm hai người nữa.",
		],
		"ph.UPYR_DEFLECT": [
			"Là các bạn thì tôi sẽ để mắt tới {who}.",
			"Các bạn cãi nhau, còn đêm thì sắp tới.",
			"Đừng vội. Sai một lần là mất người mình.",
			"{who}, sao bạn cứ im lặng suốt thế?",
			"Hôm qua tôi ngồi im và sống sót. Vậy là tôi làm đúng.",
		],
		"ph.FILLER": [
			"Chúng ta ngày càng ít đi. Tự đếm đi.",
			"Quyết nhanh lên, trời tối rồi.",
			"Tôi không tin ai cả. Không một ai.",
			"Có người ở đây đang nói dối.",
		],
		"ph.REPLY_TO_ACCUSED_HUMAN": [
			"Tôi á? Thật à? Nhìn {who} đi thì hơn.",
			"Bạn nhầm tôi với ai rồi.",
			"Được. Đuổi tôi đi. Sáng mai sẽ hiểu.",
		],
		"ph.REPLY_TO_ACCUSED_UPYR": [
			"Buồn cười thật. Nói chuyện về bạn thì hơn.",
			"Thế là dìm người nhà. Tiện ghê.",
			"Bạn vội đuổi tôi quá. Đáng ngờ đấy.",
		],
		"ph.AGREE_ACCUSE": [
			"Đồng ý. Tôi cũng không ưa {who}.",
			"Ủng hộ. {who}.",
		],
		"ph.DISAGREE_ACCUSE": [
			"Không, {who} có vẻ tử tế mà. Bạn sao thế?",
			"Yếu lắm. Bằng chứng đâu?",
		],
		"ph.INVITE_YES": [
			"Được. Gặp nhau {house.in} nhé.",
			"Thôi được, tôi đi {house.to} với bạn.",
			"Đồng ý. Chỉ đừng bỏ tôi lại.",
		],
		"ph.INVITE_NO": [
			"Không, tôi không đi với bạn. Đừng giận.",
			"Tôi chưa tin bạn.",
			"Tôi có người đi cùng rồi.",
		],
		"ph.ASK_ANSWER_HUMAN": [
			"Tôi {house.in}. Không giấu.",
			"Nói rồi mà: {house.nom}.",
		],
		"ph.ASK_ANSWER_UNSURE": [
			"Chưa quyết.",
			"Để xem ai đi đâu đã.",
		],
		"ph.PLAYER_DEFEND_REACTION": [
			"Ừ, ừ.",
			"Để xem.",
			"Ai cũng nói thế.",
			"Được, tôi tin. Tạm thời.",
		],
		"ph.GENERIC_REACTION": [
			"Thế bạn muốn nói gì?",
			"Trơn tru. Trơn tru quá.",
			"Bạn nói cho mình nghe hay cho chúng tôi?",
			"Nghe rồi. Không thuyết phục.",
		],
		"ph.AT_PLAYER": [
			"Tôi có nhiều câu hỏi nhất là với bạn đấy.",
			"Bạn bình tĩnh quá mức.",
			"Bạn đang giấu gì đó.",
			"Nhìn lại mình đi.",
			"Tôi không tin bạn. Chút nào.",
		],
		"ph.PLEA_AFTER_STREET": [
			"Hôm qua đã không ai cho tôi vào. Lần hai tôi không chịu nổi đâu.",
			"Tôi ngồi ngoài cả đêm rồi. Mở cửa đi.",
		],
		"ph.PLEA_SUSPECT": [
			"Tôi biết trông thế nào. Nhưng tôi không phải ma cà rồng.",
			"Tin tôi một lần. Sau đó đuổi cũng được.",
		],
		"ph.PLEA_NORMAL": [
			"Mở cửa đi, ngoài này lạnh.",
			"Tôi đây. Cho tôi vào.",
			"Hai người thì cầm cự được tới sáng.",
			"Nhanh lên, ngoài này có gì đang đi lại.",
		],
		"ph.PLEA_PACT": [
			"Tôi đây, mình đã hẹn rồi mà.",
			"Mở cửa đi, như đã hẹn.",
		],
		"ph.JOB_FAKE": [
			"{who} đứng {place} mãi mà chẳng được gì.",
			"Tôi thấy {who} loay hoay {place} mà không làm được gì.",
			"Lạ thật. {who} ra {place}, mà đồ dự trữ chẳng tăng.",
			"{who} chỉ giả vờ làm việc. Ở {place}: trống trơn.",
			"{who} làm gì {place} vậy? Xô vẫn rỗng như cũ.",
		],
		"ph.JOB_FAKE_AT_PLAYER": [
			"Bạn {place} chỉ tốn thời gian. Đồ dự trữ chẳng tăng.",
			"Bạn giả vờ làm việc {place}. Tôi thấy rồi.",
			"Bạn {place} được tích sự gì? Xô vẫn rỗng.",
		],
		"ph.MIMIC_PLEAS": [
			"Cho tôi vào. Tôi đây. Tôi đây, {who}. Cho tôi vào.",
			"Mở cửa đi, làm ơn. Làm ơn. Lạnh lắm. Lạnh lắm.",
			"Bạn biết tôi mà. Mở cửa ra. Mở cửa ra.",
			"Tôi về nhà rồi. Cho tôi vào nhà.",
		],
		"ph.SABOTAGE_SEEN": [
			"{who} lảng vảng {place}, giờ thì hỏng hết.",
			"Tôi thấy {who} làm gì đó {place}. Chính {who:anh ấy|cô ấy}.",
			"Ai phá đồ dự trữ? {who} là người cuối cùng ở {place}.",
		],
		"ph.SABOTAGE_SEEN_AT_PLAYER": [
			"Bạn làm gì {place} thế? Tôi thấy: sau bạn là hỏng hết.",
			"Sau khi bạn đi, {place} hỏng hết cả. Tôi thấy.",
		],
		"ph.ELDER_UPYR": [
			"Tôi là già làng. Tôi xem tranh rồi: {who} là ma cà rồng.",
			"Nghe này. Tôi là già làng, và trong tranh {who} không phải người.",
		],
		"ph.ELDER_HUMAN": [
			"Tôi là già làng. {who} là người, tôi đã xem.",
			"Theo tranh thì {who} trong sạch. Tôi là già làng, cứ tin tôi.",
		],
		"ph.MEETING_CALL": [
			"Nói đủ rồi. Bỏ phiếu ngay: {who}.",
			"Tôi đánh chuông. {who} nói dối, quyết trước khi trời tối.",
			"Tập hợp. Tôi không ngủ cạnh {who} đâu.",
		],
		"ph.BOX_NOTE": [
			"Trong rương có mảnh giấy: “{a} hoặc {b}”. Một trong hai là ma cà rồng.",
			"Tôi mở rương. Bên trong có giấy: “{a} hoặc {b}. Một trong hai không phải người”.",
		],
		"ph.BOX_OIL": [
			"Trong rương có dầu đèn. Đêm nay sẽ sáng hơn.",
			"Tôi mở rương: dầu. Mình đổ đầy đèn thôi.",
		],
		"ph.BOX_CHALK": [
			"Trong rương có phấn. Tôi đã vẽ lại bùa của {house.of}.",
		],
		"plea.shared.label": "Mình từng ngủ chung rồi",
		"plea.shared.text": "Mình đã ở chung một đêm, có sao đâu.",
		"plea.promise.label": "Hứa mai sẽ mở cửa",
		"plea.promise.text": "Cho tôi vào. Mai tôi sẽ mở cửa cho bạn trước tiên.",
		"plea.name.label": "Nói ra ma cà rồng",
		"plea.name.text": "Tôi biết là ai. Cho tôi vào, tôi kể.",
		"plea.beg.label": "Van xin",
		"plea.beg.text": "Làm ơn. Ngoài này không ai sống nổi.",
		"spoil.water": "xô nước bị đổ",
		"spoil.wood": "củi bị vứt vương vãi trong bùn",
		"spoil.lamp": "dầu bị đổ hết",
		"spoil.fish": "cá bị thả lại xuống sông",
		"spoil.any": "mọi thứ bị phá hỏng",
		"quick.house": "Tôi ngủ {house.in}. Ai đi cùng không?",
		"quick": ["Tôi không phải ma cà rồng. Thề đấy.", "Ai ngoài đường về là ma cà rồng.", "Mình đi theo cặp đi.", "Ai nói dối chỗ ngủ thì đuổi."],
		"intent.accuse": ["ma cà rồng", "là nó", "nói dối", "khả nghi", "nghi", "không tin", "đuổi", "sát nhân", "có tội"],
		"intent.invite": ["đi cùng", "với tôi", "cùng nhau", "đi thôi", "qua nhà"],
		"intent.defend": ["không phải tôi", "tôi không", "tôi là người", "thề", "vô tội", "tin tôi"],
		"intent.ask": ["ở đâu", "đi đâu", "nhà nào"],
		"intent.houses": ["sông", "kho", "tháp", "hầm", "nhà xe"],
		"ev.street": "sống sót trở về từ ngoài đường",
		"ev.times": " ({n} lần)",
		"ev.liar": "nói dối về chỗ ngủ",
		"ev.death": "ở gần khi có người chết",
		"ev.fake": "làm việc công cốc",
		"ev.sabotage": "ở cạnh việc bị phá",
		"ev.tunnel": "chui đường hầm sang nhà khác",
		"ev.sep": "; ",
		"sys.sabotage": "Có người phá hoại {place}: {what}. Đồ dự trữ giảm.",
		"claim.elder_upyr": "tự nhận là già làng: {who} là ma cà rồng",
		"claim.elder_human": "tự nhận là già làng: {who} là người",
		"claim.healer": "{role}: đã cứu {who} đêm {n}",
		"when.night": "Đêm {n}",
		"when.day": "Ngày {n}",
		"chron.line": "{title}: {text}",
		"chron.morning": "Sáng ra: {text}",
		"log.exiled": "cả làng đã đuổi {who}.",
		"log.supplies": "đồ dự trữ gom được: {p}%.",
		"log.tunnel": "{who.cap} không được vào {from.of}, và đã chui đường hầm {house.to}.",
		"log.street_upyr": "{who.cap} không được vào {house.of}, nhưng vẫn sống tới sáng.",
		"log.street_dead": "{who.cap} không được vào {house.of}. {who:Sáng ra người ta thấy anh ấy ngoài đường.|Sáng ra người ta thấy cô ấy ngoài đường.|Bạn đã chết ngoài đường.}",
		"log.street_ok": "{who.cap} ngủ ngoài đường và sống sót.",
		"log.mimic_knock": "có ai gõ cửa {house.of} bằng giọng của {voice}. Không ai mở.",
		"log.mimic_spared": "{house.in} đã cho giọng của {voice} vào. Đó không phải {voice}, nhưng mọi người vẫn sống tới sáng.",
		"log.mimic_kill": "{house.in} đã cho giọng của {voice} vào. Đó là Kẻ Nhại Giọng: nó đã bắt {who}.",
		"log.alone_dead": "{who.cap} ở một mình {house.in}. Bùa đã tắt.",
		"log.killed": "{who.cap} đã chết {house.in}. Bên cạnh: {others}.",
		"log.clean": "{house.in} có {list} ngủ. Mọi người đều bình an.",
		"log.creature": "bùa của {house.of} đã vỡ. Con quái trong rừng đã bắt {who}.",
		"log.liar": "{who.cap} nói đi {said.to}, nhưng lại ngủ {house.in}.",
		"log.talisman_cracked": "bùa của {house.of} bị nứt.",
		"log.talisman_broken": "bùa của {house.of} bị vỡ.",
		"log.saved": "{house.in} {who} bị tấn công, nhưng {healer} đã chữa cho {who:anh ấy|cô ấy|bạn}.",
		"log.meeting": "{who.cap} đã đánh chuông: họp khẩn.",
		"log.event": "{e}.",
		"sys.dawn1": "Trời sáng. Mọi người ra quảng trường.",
		"sys.dawn": "Ngày {d}. Còn sống: {n}.",
		"job.water.title": "Gánh nước",
		"job.water.place": "ở giếng",
		"job.water.done": "Đủ nước tới sáng.",
		"job.wood.title": "Bổ củi",
		"job.wood.place": "ở đống củi",
		"job.wood.done": "Đủ củi cả đêm.",
		"job.lamp.title": "Đổ dầu đèn",
		"job.lamp.place": "bên cột đèn",
		"job.lamp.done": "Đèn đã đầy dầu.",
		"job.fish.title": "Bắt cá",
		"job.fish.place": "bên sông",
		"job.fish.done": "Có cá cho bữa tối.",
		"job.talisman.title": "Sửa bùa",
		"job.talisman.place": "bên lá bùa",
		"job.talisman.done": "Bùa như mới.",
		"job.box.title": "Mở rương",
		"job.box.place": "bên cái rương",
		"role.elder": "Già làng",
		"role.elder.mid": "già làng",
		"role.healer": "{who:Thầy lang|Bà lang|Thầy lang}",
		"role.healer.mid": "{who:thầy lang|bà lang|thầy lang}",
		"role.headman": "Trưởng thôn",
		"role.headman.mid": "trưởng thôn",
		"role.named": "{role} {who}",
		"event.fog.title": "Sương mù",
		"event.fog.mid": "sương mù",
		"event.fog.text": "Sương mù át tiếng chuông: ít thời gian chạy hơn, ngoài đường nguy hiểm hơn.",
		"event.moon.title": "Trăng tròn",
		"event.moon.mid": "trăng tròn",
		"event.moon.text": "Trăng tròn: tới sáng mọi lá bùa đều yếu đi.",
		"event.quiet.title": "Đêm yên",
		"event.quiet.mid": "đêm yên",
		"event.quiet.text": "Đêm yên: ngoài đường an toàn hơn, Kẻ Nhại Giọng không tới.",
		"event.rain.title": "Mưa như trút",
		"event.rain.mid": "mưa như trút",
		"event.rain.text": "Mưa dập tắt đèn: dầu dự trữ đêm nay vô dụng.",
		"recap.street_host": "Bạn không được vào {house.of}: người giữ cửa là {who}.",
		"recap.street": "Bạn đã ở ngoài đường cả đêm. Ở đó gần như ai cũng chết.",
		"recap.street_p": "Khả năng chết ngoài đường đêm đó: {p}%.",
		"recap.killer": "{who} đã giết bạn. {who:Anh ấy|Cô ấy} là ma cà rồng.",
		"recap.you_opened": "Chính bạn đã mở cửa cho {who}.",
		"recap.killer_opened": "Chính {who} đã mở cửa cho bạn.",
		"recap.near": "Bên cạnh: {others}.",
		"recap.alone": "Bạn ở một mình {house.in}. Một người không giữ nổi bùa tới sáng.",
		"recap.alone_p": "Khả năng chết một mình trong nhà đó: {p}%. Ban ngày hãy rủ ai đó đi cùng.",
		"recap.creature": "Bùa của {house.of} đã vỡ, và con quái trong rừng đã vào nhà.",
		"recap.creature_tip": "Ban ngày có thể sửa bùa: đó là một việc ở quảng trường.",
		"recap.mimic_you": "Bạn đã mở cửa cho giọng của {voice}. Đó là Kẻ Nhại Giọng.",
		"recap.mimic_host": "{who} đã cho giọng của {voice} vào. Đó là Kẻ Nhại Giọng.",
		"recap.voice_dead": "Lúc đó {voice} đã chết rồi.",
		"recap.voice_away": "Còn {voice} lúc đó đang {house.in}.",
		"recap.exiled": "Bạn bị đuổi vào ngày {d}. Phiếu chống bạn: {list}.",
		"recap.exiled_many": "Bạn bị đuổi vào ngày {d}. Phiếu chống bạn: số đông.",
		"recap.seen": "Cả làng đã thấy: {ev}.",
		"recap.exiled0": "Bạn đã bị đuổi.",
		"recap.died": "Bạn chết vào đêm {n}. {why}",
		"verdict.mimic": "Đêm {n}, bạn đã mở cửa cho Kẻ Nhại Giọng, bằng giọng của {voice}.",
		"verdict.let_upyr": "Đêm {n}, bạn đã cho {who} vào, và {who:anh ấy|cô ấy} là ma cà rồng.",
		"verdict.vote_upyr": "Ngày {n}, phiếu của bạn đã giúp đuổi một ma cà rồng: {who}.",
		"verdict.vote_human": "Ngày {n}, bạn bỏ phiếu chống {who}, và {who:anh ấy|cô ấy} là người.",
		"verdict.clean": "Bạn chưa từng mở cửa cho ma cà rồng và đã thấy bình minh.",
		"verdict.dead": "Bạn đã không sống tới bình minh.",
		"verdict.kills": " Thành tích của bạn: {n}.",
		"verdict.upyr_won": "Cả làng không bao giờ biết ma cà rồng chính là bạn.",
		"verdict.upyr_lost": "Bạn sống tới bình minh, nhưng làng vẫn trụ được.",
		"sys.box": "Ở rìa quảng trường có một cái rương. Hôm qua chưa có.",
		"sys.elder_upyr": "Tranh của già làng: {who} là ma cà rồng. Chỉ mình bạn biết.",
		"sys.elder_human": "Tranh của già làng: {who} là người. Chỉ mình bạn biết.",
		"sys.bell_you": "Bạn đánh chuông. Họp khẩn!",
		"sys.bell": "{who} đánh chuông. Họp khẩn!",
		"box.note": "Trong rương có giấy: “{a.cap} hoặc {b}”. Một trong hai là ma cà rồng. Chỉ mình bạn thấy tờ giấy.",
		"box.oil": "Trong rương có dầu đèn: dự trữ +{n}.",
		"box.chalk": "Trong rương có phấn: bùa của {house.of} đã được vẽ lại.",
		"box.empty": "Rương trống không.",
		"say.accuse": "Tôi nghĩ là {who}.",
		"say.invite": "{who}, cùng đi {house.to} không?",
		"say.ask": "{who}, tối nay bạn ngủ ở đâu?",
		"say.defend": ["Tôi không phải ma cà rồng. Thề đấy.", "Tôi là người nhà mà. Đêm nay cứ thử tôi.", "Không phải tôi. Tìm tiếp đi."],
		"toast.elder_upyr": "Tranh: {who} là ma cà rồng",
		"toast.elder_human": "Tranh: {who} là người",
		"toast.box_taken": "Rương đã có người mở",
		"toast.job_done": "“{job}”: hôm nay xong rồi",
		"toast.box": "Có cái rương xuất hiện ở quảng trường",
		"toast.back_exit": "Nhấn lần nữa để thoát",
		"quit.ask": "Bỏ ván này?",
		"quit.stay": "Ở lại",
		"quit.leave": "Về menu",
		"cfg.players": "Người chơi",
		"cfg.monsters": "Ma cà rồng",
		"cfg.shelters": "Chỗ trú",
		"cfg.capacity": "Chỗ trong mỗi nơi trú",
		"cfg.nights": "Số đêm tới bình minh",
		"cfg.day_seconds": "Ban ngày, giây",
		"cfg.door_seconds": "Quyết định ở cửa, giây",
		"cfg.run_seconds": "Chạy về nhà, giây",
		"cfg.outside_death": "Chết ngoài đường, %",
		"cfg.first_night_outside_death": "Như trên, đêm đầu, %",
		"cfg.vote_from_day": "Đuổi người từ ngày",
		"diff.easy": "Dễ",
		"diff.normal": "Thường",
		"diff.hard": "Khó",
		"diff.custom": "Tự chỉnh",
		"diff.cast": "{p} dân làng, {u} ma cà rồng.",
		"diff.human": " Bạn luôn là người.",
		"diff.easy_note": " Ngày dài hơn.",
		"diff.hard_note": " Ngày ngắn hơn, ngoài đường nguy hiểm hơn.",
		"diary.exiled": "Bị đuổi vào ngày {n}.",
		"diary.died": "Chết vào đêm {n}.",
		"diary.night": "{n}: {where}",
		"diary.street": "ngoài đường",
		"diary.said": " (đã nói: {house})",
		"diary.nights": "Các đêm: {list}.",
		"diary.today": "Hôm nay định đi: {house}.",
		"diary.evidence": "Manh mối: {ev}.",
		"diary.own_claim": "{text}.",
		"diary.claim": "{who.cap} {text}.",
		"diary.seen_upyr": "Tranh của bạn: ma cà rồng.",
		"diary.seen_human": "Tranh của bạn: người.",
		"diary.nothing": "Chưa biết gì cả.",
		"diary.head": "Nhật ký: những gì biết về từng người",
		"diary.gone": "{who} · đã chết",
		"journal.who": "{who}:",
		"journal.head": "Ghi chép trong ngày",
		"ui.close": "Đóng",
		"ui.cancel": "Huỷ",
		"say.placeholder": "Hoặc tự viết",
		"say.send": "Nói",
		"chip.exiled": " · bị đuổi",
		"supplies": "Dự trữ {a}/{b}",
		"howto.art_accuse": "Bạn là ma cà rồng!",
		"howto.art_street": "‹ ngoài đường",
		"howto.art_door": "Cho vào?",
		"game.title": "Cho Tôi Vào",
		"menu.tale": "Ban đêm không ai sống nổi ngoài đường.\nChỗ trú ít hơn số người.\n\nCó người đứng trước cửa xin vào. Người bên trong quyết định.",
		"menu.hint": "Ma cà rồng ở ngay giữa các bạn. Chúng còn không biết nhau.",
		"menu.howto": "Cách chơi",
		"menu.play": "Chơi",
		"lang.pick": "Ngôn ngữ",
		"diff.note": "{d}: {text}",
		"diff.note_custom": "Độ khó tự chỉnh: {text}",
		"settings.title": "Cài đặt",
		"settings.lang": "Ngôn ngữ",
		"settings.sound": "Âm thanh",
		"settings.music": "Nhạc",
		"settings.sfx": "Hiệu ứng",
		"settings.ambience": "Không khí",
		"settings.haptics_on": "Rung: bật",
		"settings.haptics_off": "Rung: tắt",
		"settings.difficulty": "Độ khó",
		"settings.hints": "Hiện lại gợi ý",
		"settings.hints_reset": "Gợi ý sẽ hiện lại",
		"settings.note": "Mỗi mức đã được thử qua 1500 ván. Số chỗ trú và số đêm ảnh hưởng tới cân bằng nhiều nhất.",
		"settings.start": "Bắt đầu với cài đặt này",
		"ui.back": "Quay lại",
		"howto.day.title": "Ban ngày",
		"howto.day.text": "Trong làng có người, và giữa họ có ma cà rồng. Ma cà rồng trông như mọi người. Bạn là một dân làng cầm đèn lồng.\n\nBan ngày mọi người ở quảng trường. Chạm vào một dân làng: buộc tội, rủ ngủ chung hoặc hỏi họ ngủ ở đâu. Con mắt đỏ trên đầu nghĩa là cả làng đang nghi người đó.\n\nChạm vào biểu tượng công việc: nước, củi, đèn. Càng nhiều dự trữ, đêm càng sáng. Ma cà rồng giả vờ làm việc, thậm chí phá việc đã làm. Đôi khi có cái rương xuất hiện ở quảng trường: ai mở trước thì được đồ bên trong.",
		"howto.night.title": "Ban đêm",
		"howto.night.text": "Chiều tối chuông vang và ai cũng chạy về nhà. Khi chuông còn vang, hãy chạm vào một ngôi nhà. Chỗ trú ít hơn số người: ai ở lại ngoài đường khó mà thấy được buổi sáng.\n\nỞ một mình trong nhà cũng nguy hiểm. Ban ngày hãy hẹn trước ngủ với ai, và sửa lá bùa bị nứt: nhà có bùa vỡ sẽ bị con quái trong rừng vào.",
		"howto.door.title": "Cánh cửa",
		"howto.door.text": "Ai tới nhà đầu tiên sẽ quyết định ai được vào.\n\nCho ma cà rồng vào thì bạn không thấy được buổi sáng. Không cho ai vào thì bạn ở một mình. Sáng ra, hãy xem ai ngủ ở đâu và ai đã nói dối.\n\nĐôi khi tiếng gõ cửa mang giọng của người đang ở nhà khác hoặc đã chết. Đó là Kẻ Nhại Giọng: đừng mở.\n\nMột số người có vai trò: Già làng, Thầy lang, Trưởng thôn. Mỗi ván, một lần trong ngày bạn có thể đánh chuông và bỏ phiếu ngay. Mọi điều biết được về từng người đều có trong Nhật ký.",
		"howto.title": "Cách chơi · {a}/{b}",
		"howto.got_it": "Đã hiểu",
		"ui.next": "Tiếp",
		"ui.skip": "Bỏ qua",
		"crash.title": "Báo cáo",
		"crash.head": "Lần trước trò chơi bị tắt đột ngột",
		"crash.text": "Đây là lỗi của trò chơi, không phải của bạn. Chạm “Sao chép báo cáo” và gửi cho chúng tôi: trong đó có ghi mọi thứ dừng ở bước nào.",
		"crash.steps": "Các bước cuối:",
		"crash.copy": "Sao chép báo cáo",
		"crash.copied": "Đã sao chép: dán vào khung chat",
		"ui.continue": "Tiếp tục",
		"prologue.title": "Trước đêm đầu tiên",
		"prologue.pre": "Vai của bạn…",
		"prologue.upyr": "Bạn là ma cà rồng",
		"prologue.human": "Bạn là người",
		"prologue.upyr_text": "Bạn không biết còn ai giống mình. Ngoài đường không làm bạn sợ, còn ai chung cửa với bạn sẽ không sống tới sáng. Ban ngày hãy nói như người thường.",
		"prologue.human_text": "Đêm ngoài đường bạn gần như chắc chắn chết. Ở nơi trú không được ở một mình: bùa sẽ tắt. Bạn cần thêm một người, mà không biết ai trong họ là người.",
		"prologue.facts": "{p} dân làng, {u} ma cà rồng. {s} chỗ trú, mỗi nơi {c} chỗ. Phải sống tới bình minh thứ {n}.",
		"prologue.go": "Ra với mọi người",
		"prologue.elder": "Bạn là già làng. Mỗi ván một lần, ban ngày, chạm vào một dân làng và xem tranh: bạn sẽ biết người đó có phải ma cà rồng không. Chỉ mình bạn biết.",
		"prologue.healer": "Bạn là thầy lang. Mỗi ván một lần, trước khi đêm xuống, hãy mang thảo dược theo: nếu ai đó cạnh bạn trong nhà bị tấn công, bạn sẽ cứu họ.",
		"prologue.headman": "Bạn là trưởng thôn. Khi bỏ phiếu đuổi người, phiếu của bạn tính gấp đôi.",
		"end.title": "Tổng kết",
		"end.people": "Con người đã trụ vững",
		"end.upyri": "Làng đã vắng tanh",
		"end.won": "Phe của bạn thắng.",
		"end.lost": "Phe của bạn thua.",
		"end.who": "Ai là ai",
		"end.upyr": "ma cà rồng",
		"end.human": "người",
		"end.with_role": "{a}, {role}",
		"end.chip": "{who}: {what}",
		"end.how": "Diễn biến",
		"end.again": "Chơi ván nữa",
		"end.verdict": "Điều gì quyết định ván này",
		"end.offer_easier": "Giảm độ khó nhé?",
		"end.offer_harder": "Thắng hai ván liền. Thử khó hơn không?",
		"end.easier": "Dễ hơn",
		"end.harder": "Thử khó hơn",
		"vote.title": "Đuổi khỏi làng",
		"vote.bell_you": "Họp khẩn: bạn đã đánh chuông.",
		"vote.bell": "Họp khẩn: {who} đã đánh chuông.",
		"vote.ask": "Đuổi ai khỏi làng? Người bị đuổi đi mãi mãi. Họ là ai, cuối ván sẽ rõ.",
		"day.diary": "Nhật ký",
		"vote.headman": "Bạn là trưởng thôn: phiếu của bạn tính gấp đôi.",
		"vote.dead": "Bạn đã chết, chỉ có thể xem.",
		"vote.watch": "Xem kết quả",
		"vote.go": "Đuổi",
		"vote.none": "Không ai bị đuổi",
		"vote.gone": "{who} đã ra đi",
		"vote.gone_you": "Bạn đã bị đuổi",
		"vote.row": "{who}: {n}",
		"vote.night": "Màn đêm buông xuống",
		"mo.title": "Buổi sáng",
		"mo.all_alive": "Mọi người đều sống",
		"mo.one_dead": "Thiếu một người",
		"mo.dead_n": "Thiếu: {n}",
		"mo.why": "Vì sao bạn chết",
		"mo.event": "Đêm nay: {e}.",
		"mo.street_dead": "{who.cap} không được vào {house.of}. {who:Người ta thấy anh ấy ngoài đường.|Người ta thấy cô ấy ngoài đường.|Bạn đã chết ngoài đường.}",
		"mo.alone_dead": "{who.cap} ở một mình {house.in}. Bùa đã tắt.",
		"mo.killed": "{who.cap} đã chết {house.in}. Bên cạnh: {others}.",
		"mo.street_ok": "{who.cap} ngủ ngoài đường cả đêm. Và đã trở về.",
		"mo.alone_ok": "{who.cap} ở một mình {house.in} và vẫn bình an.",
		"mo.clean": "{house.in.cap} có {list} ngủ. Mọi người đều bình an.",
		"mo.liar": "{who.cap} nói đi {said.to}, nhưng lại ngủ {house.in}.",
		"mo.creature": "Bùa của {house.of} đã vỡ. Con quái trong rừng đã bắt {who}.",
		"mo.talisman_cracked": "Bùa của {house.of} bị nứt. Ban ngày có thể sửa.",
		"mo.talisman_broken": "Bùa của {house.of} bị vỡ. Ban ngày có thể sửa.",
		"mo.saved_upyr": "{house.in.cap}, một người trong làng đã tấn công {who}, nhưng {healer} đã chữa cho {who:anh ấy|cô ấy|bạn}.",
		"mo.saved_creature": "{house.in.cap}, con quái trong rừng đã tấn công {who}, nhưng {healer} đã chữa cho {who:anh ấy|cô ấy|bạn}.",
		"mo.saved_mimic": "{house.in.cap}, Kẻ Nhại Giọng đã tấn công {who}, nhưng {healer} đã chữa cho {who:anh ấy|cô ấy|bạn}.",
		"mo.tunnel": "{who.cap} không được vào {from.of}, và đã chui đường hầm {house.to}.",
		"mo.mimic_kill": "{house.in.cap} đã cho giọng của {voice} vào. Đó không phải {voice}: Kẻ Nhại Giọng đã bắt {who}.",
		"mo.mimic_spared": "{house.in.cap} đã cho giọng của {voice} vào. Đó không phải {voice}, nhưng mọi người vẫn sống tới sáng.",
		"mo.mimic_knock": "Đêm qua có ai gõ cửa {house.of} bằng giọng của {voice}. Không ai mở. Đó là Kẻ Nhại Giọng.",
		"mo.mimic_knock_away": "Đêm qua có ai gõ cửa {house.of} bằng giọng của {voice}. Không ai mở. Còn {voice} lúc đó đang {away.in}.",
		"list.sep": ", ",
		"night.dusk": "Trời tối dần. Chuông đang vang.",
		"night.dead": "Bạn không còn nữa. Đêm vẫn trôi mà không có bạn.",
		"night.bell": "Chuông vang rồi! Chạy về nhà: chạm vào một ngôi nhà.",
		"night.going": "định tới: {list}",
		"night.pact": "đã hẹn với {who}",
		"night.tunnel": "đường hầm {house.to}",
		"night.tal_broken": "bùa đã vỡ",
		"night.tal_cracked": "bùa bị nứt",
		"night.rule": "Ai tới cửa đầu tiên sẽ ở trong và quyết định ai được vào. Nếu không chọn nhà khi chuông vang, bạn sẽ chạy tới chỗ đã nói, sau cùng.",
		"night.heal": "Mang thảo dược: đêm nay tôi sẽ cứu một người",
		"night.hint": "Chuông không vang lâu. Chạm vào một ngôi nhà ở quảng trường hoặc trong danh sách rồi chạy. Ai tới cửa trước sẽ quyết định ai được vào.",
		"night.heal_on": "Đã mang thảo dược: nếu người cạnh bạn bị tấn công, bạn sẽ cứu họ",
		"night.first": "Bạn sẽ tới đầu tiên: bạn quyết định ai được vào.",
		"night.ahead": "Tới cửa trước bạn: {list}. {who} sẽ quyết định.",
		"night.run": "Bạn chạy {house.to}. {rest}",
		"door.title": "Trước cửa",
		"door.hint_host": "Cho người bạn tin vào. Không mở cho ai thì bạn ở một mình, mà một mình thì không sống nổi.",
		"door.hint_guest": "Chọn điều muốn nói qua cánh cửa. Chủ nhà nhớ hai người đã từng ngủ chung chưa.",
		"door.hint_alone": "Ở đây một mình không sống nổi. Lần sau hãy rủ ai đó đi cùng từ ban ngày.",
		"door.host": "Bạn tới {house.of} đầu tiên. Có người gõ cửa.",
		"door.cap": "Có thể cho vào: {n}",
		"door.quote": "“{text}”",
		"door.admit": "Cho vào",
		"door.admitting": "Cho vào rồi",
		"door.elsewhere": "Ở các cửa khác: {list}.",
		"door.upyr_note": "Người bạn cho vào sẽ không sống tới sáng.",
		"door.alone_note": "Không mở cho ai thì bạn ở một mình, và bùa sẽ tắt.",
		"door.open": "Mở cửa",
		"door.refuse": "Không mở cho ai",
		"door.locked": "{house.nom} đã khoá từ bên trong. Ở trong là {who}.",
		"door.rivals": "Đứng cùng bạn trước cửa: {list}. Không đủ chỗ cho tất cả.",
		"door.mimic": "Trong bóng tối sau lưng bạn, có ai đang nói bằng giọng của {voice}. Nhưng {voice} không có ở đây.",
		"door.say": "Bạn sẽ nói gì qua cánh cửa?",
		"door.knock": "Bạn gõ cửa {house.of}…",
		"door.let_in": "Then cửa kêu cạch. {who} cho bạn vào.",
		"door.shut": "Tiếng bước chân xa dần khỏi cửa. Bạn vẫn ở bên ngoài.",
		"door.hatch": "Sau nhà có một cửa sập. Đường hầm dẫn {house.to}, ở đó còn chỗ. Ai chui qua sẽ được ở trong, nhưng sáng ra ai cũng biết người đó từ đâu tới.",
		"door.tunnel": "Chui đường hầm {house.to}",
		"door.wait": "Chờ bình minh",
		"door.alone": "Bạn tới {house.of} đầu tiên. Không ai tới nữa.",
		"door.alone_upyr": "Một ma cà rồng đơn độc không sợ ngoài đường.",
		"door.alone_human": "Lá bùa chập chờn. Một mình bạn không giữ được nó tới sáng.",
		"day.journal": "Ghi chép",
		"day.journal_n": "Ghi chép ({n})",
		"day.dead": "Bạn không còn nữa. Bạn chỉ có thể xem.",
		"day.skip": "Bỏ qua ngày",
		"day.defend": "Thanh minh",
		"day.invite": "Rủ…",
		"day.accuse": "Buộc tội…",
		"day.say": "Nói…",
		"day.bell": "Họp!",
		"day.ready": "Sẵn sàng cho đêm",
		"day.hint": "Chạm vào một dân làng: buộc tội, rủ đi cùng hoặc hỏi họ ngủ ở đâu. Chạm vào biểu tượng công việc: đồ dự trữ thắp đèn ban đêm.",
		"day.bell_ask": "Đánh chuông? Mọi người sẽ tập hợp bỏ phiếu ngay. Mỗi ván chỉ một lần.",
		"day.bell_do": "Đánh chuông",
		"day.preview": "{who}: {text}",
		"day.say_aloud": "Nói to",
		"day.person_ev": "{who} · {ev}",
		"day.p_accuse": "Buộc tội: “Là {who}”",
		"day.p_invite": "Rủ ngủ chung đêm nay",
		"day.p_ask": "Hỏi ngủ ở đâu",
		"day.p_elder": "Xem tranh của già làng: {who:anh ấy|cô ấy} là ai?",
		"day.work": "Làm việc: {job.low}",
		"day.spoil": "Phá việc đã làm ({place})",
		"day.who_accuse": "Buộc tội ai?",
		"day.who_invite": "Rủ ai?",
		"day.where_with": "Bạn đi đâu với {who}?",
	}
