extends Gram
## 简体中文。一个传说里的村子：熊猫滚滚、戴金箍的悟空、猪八戒、福娃阿福、花木兰和嫦娥。
## 怪物是僵尸，护身靠门上的符。玩家是「你」。名字不变格，列举用「、」和「和」。


func code() -> String:
	return "zh"


func plural_index(_n: int) -> int:
	return 0


func join(parts: PackedStringArray) -> String:
	if parts.size() <= 1:
		return "".join(parts)
	return "、".join(parts.slice(0, parts.size() - 1)) + "和" + parts[parts.size() - 1]


func cap(s: String) -> String:
	return s


func data() -> Dictionary:
	return {
		"and": "和",
		"you": {"nom": "你", "acc": "你", "gen": "你", "dat": "你", "ins": "你"},
		"you_name": "你",
		"someone": {"nom": "别人", "acc": "别人", "gen": "别人", "dat": "别人"},
		## nom — 门牌和列表；in — 「在谷仓」；to — 「去谷仓」；of — 「谷仓」（后接「的」）。
		"houses": [
			{"nom": "河边小屋", "in": "在河边小屋", "to": "去河边小屋", "of": "河边小屋"},
			{"nom": "谷仓", "in": "在谷仓", "to": "去谷仓", "of": "谷仓"},
			{"nom": "钟楼", "in": "在钟楼", "to": "去钟楼", "of": "钟楼"},
			{"nom": "地窖", "in": "在地窖", "to": "去地窖", "of": "地窖"},
			{"nom": "车库", "in": "在车库", "to": "去车库", "of": "车库"},
		],
		"names": [
			["木兰", true], ["滚滚", false], ["嫦娥", true], ["悟空", false], ["小红", true], ["阿福", false],
			["老王", false], ["阿美", true], ["八戒", false], ["春花", true], ["阿强", false], ["王奶奶", true],
		],
		"looks": "res://config/looks_zh.tres",
		"ph.ANNOUNCE": [
			"我今晚{house.in}过夜。",
			"我{house.to}。谁跟我一起？",
			"我{house.in}睡，跟大家说一声。",
			"{house.nom}。就这么定了。",
		],
		"ph.ACCUSE_STRONG": [
			"{who}，你说说你是怎么活到天亮的。",
			"我看已经很清楚了。{who}。",
			"出事的时候{who}就在旁边。巧合吗？",
			"我投{who}。没什么好说的。",
		],
		"ph.ACCUSE_STREET": [
			"{who}在外面过了一夜还回来了。人可做不到。",
			"{who}，你在外面待了一整夜。没什么要说的吗？",
		],
		"ph.ACCUSE_LIAR": [
			"{who}说要{house.to}，结果睡在别处。为什么撒谎？",
			"{who}，你本来要去别的地方。怎么变了？",
		],
		"ph.DEFEND": [
			"对，我在那儿。那又怎样？",
			"我不是僵尸。今晚可以试试我。",
			"我只是挑错了屋子。",
			"现在把我赶走，明天早上你们还会少两个人。",
		],
		"ph.UPYR_DEFLECT": [
			"换我是你们，我就盯着{who}。",
			"你们还在吵，天就要黑了。",
			"别急着赶人。赶错了，就少了自己人。",
			"{who}，你怎么一直不说话？",
			"我昨天一声没吭，活下来了。说明我做得对。",
		],
		"ph.FILLER": [
			"我们越来越少了。自己数数。",
			"快点决定吧，天黑了。",
			"我谁都不信。谁都不信。",
			"你们中间有人正在撒谎。",
		],
		"ph.REPLY_TO_ACCUSED_HUMAN": [
			"我？真的假的？你还是看看{who}吧。",
			"你认错人了。",
			"好啊。赶我走。明天早上你们就明白了。",
		],
		"ph.REPLY_TO_ACCUSED_UPYR": [
			"好笑。还是聊聊你吧。",
			"自己人就是这么被害的。真方便。",
			"你这么急着赶我走。很可疑。",
		],
		"ph.AGREE_ACCUSE": [
			"同意。我也看{who}不顺眼。",
			"附议。{who}。",
		],
		"ph.DISAGREE_ACCUSE": [
			"不会吧，{who}看着挺正常的。你怎么了？",
			"太牵强了。证据呢？",
		],
		"ph.INVITE_YES": [
			"行。我们{house.in}见。",
			"好吧，我跟你{house.to}。",
			"好。只是别坑我。",
		],
		"ph.INVITE_NO": [
			"不了，我不跟你去。别介意。",
			"我还不信你。",
			"我已经有伴了。",
		],
		"ph.ASK_ANSWER_HUMAN": [
			"我{house.in}。不瞒你。",
			"说过了：{house.nom}。",
		],
		"ph.ASK_ANSWER_UNSURE": [
			"还没想好。",
			"我看看谁去哪儿。",
		],
		"ph.PLAYER_DEFEND_REACTION": [
			"嗯嗯。",
			"走着瞧。",
			"谁都这么说。",
			"好吧，我信你。暂时。",
		],
		"ph.GENERIC_REACTION": [
			"你这话什么意思？",
			"说得真好听。太好听了。",
			"你这是说给自己听，还是说给我们听？",
			"听到了。没说服我。",
		],
		"ph.AT_PLAYER": [
			"我最想问的就是你。",
			"你太冷静了。",
			"你在隐瞒什么。",
			"先看看你自己吧。",
			"我不信你。一点都不信。",
		],
		"ph.PLEA_AFTER_STREET": [
			"昨天就没人让我进。再来一次我就活不成了。",
			"我在外面坐了一整夜。开门吧。",
		],
		"ph.PLEA_SUSPECT": [
			"我知道这看起来像什么。可我不是僵尸。",
			"信我一次。之后你想赶就赶。",
		],
		"ph.PLEA_NORMAL": [
			"开门吧，外面冷。",
			"是我。让我进去。",
			"两个人能撑到天亮。",
			"快点，外面有东西在走动。",
		],
		"ph.PLEA_PACT": [
			"是我，我们说好的。",
			"开门，按说好的来。",
		],
		"ph.JOB_FAKE": [
			"{who}在{place}站了半天，什么也没干成。",
			"我看见{who}在{place}磨蹭，什么都没做。",
			"奇怪。{who}去了{place}，可存粮没多。",
			"{who}只是装作干活。在{place}待过：什么都没有。",
			"{who}在{place}干什么呢？桶还是空的。",
		],
		"ph.JOB_FAKE_AT_PLAYER": [
			"你在{place}只是浪费时间。存粮没多。",
			"你在{place}装作干活。我看见了。",
			"你在{place}有什么用？桶还是空的。",
		],
		"ph.MIMIC_PLEAS": [
			"让我进去。是我。是我，{who}。让我进去。",
			"开门，求你。求你。好冷。好冷。",
			"你认识我的。开门。开门。",
			"我回家了。让我回家。",
		],
		"ph.SABOTAGE_SEEN": [
			"{who}在{place}转来转去，现在全毁了。",
			"我看见{who}在{place}干了什么。就是{who:他|她}。",
			"谁在糟蹋存粮？最后在{place}的是{who}。",
		],
		"ph.SABOTAGE_SEEN_AT_PLAYER": [
			"你在{place}干什么？我看见了：你走后全毁了。",
			"你一走，{place}就全毁了。我看见了。",
		],
		"ph.ELDER_UPYR": [
			"我是长老。我看过画了：{who}是僵尸。",
			"听着。我是长老，画上的{who}不是人。",
		],
		"ph.ELDER_HUMAN": [
			"我是长老。{who}是人，我查过了。",
			"照画上看，{who}是清白的。我是长老，可以信我。",
		],
		"ph.MEETING_CALL": [
			"别聊了。现在就投票：{who}。",
			"我敲钟了。{who}在撒谎，天黑前定下来。",
			"都过来。我可不跟{who}睡在一起。",
		],
		"ph.BOX_NOTE": [
			"箱子里有张纸条：“{a}或{b}”。其中一个是僵尸。",
			"我打开了箱子。里面有张纸条：“{a}或{b}。两人中有一个不是人”。",
		],
		"ph.BOX_OIL": [
			"箱子里有灯油。今晚会亮一些。",
			"我打开了箱子：是油。把灯都加满。",
		],
		"ph.BOX_CHALK": [
			"箱子里有朱砂。我把{house.of}的符重画了一遍。",
		],
		"plea.shared.label": "我们一起住过",
		"plea.shared.text": "我们一起过过一夜，什么事都没有。",
		"plea.promise.label": "保证明天先开门",
		"plea.promise.text": "让我进去。明天我第一个给你开门。",
		"plea.name.label": "说出僵尸是谁",
		"plea.name.text": "我知道是谁。让我进去，我告诉你。",
		"plea.beg.label": "苦苦哀求",
		"plea.beg.text": "求你了。外面没人活得下来。",
		"spoil.water": "水桶被打翻了",
		"spoil.wood": "柴火被扔进了泥里",
		"spoil.lamp": "灯油被洒了",
		"spoil.fish": "鱼被扔回了河里",
		"spoil.any": "全被毁了",
		"quick.house": "我{house.in}过夜。谁跟我一起？",
		"quick": ["我不是僵尸。我发誓。", "从外面回来的就是僵尸。", "我们两人一组吧。", "谁在睡哪儿的事上撒谎，就赶谁走。"],
		"intent.no_spaces": "1",
		"intent.accuse": ["僵尸", "是他", "是她", "撒谎", "说谎", "可疑", "不信", "赶走", "凶手"],
		"intent.invite": ["一起", "跟我", "和我", "走吧", "来吧"],
		"intent.defend": ["不是我", "我是人", "发誓", "清白", "相信我"],
		"intent.ask": ["哪", "睡哪"],
		"intent.houses": ["河边", "谷仓", "钟楼", "地窖", "车库"],
		"ev.street": "从外面活着回来了",
		"ev.times": "（{n}次）",
		"ev.liar": "在睡哪儿的事上撒了谎",
		"ev.death": "有人死时就在旁边",
		"ev.fake": "白干了活",
		"ev.sabotage": "在被毁的活儿旁边",
		"ev.tunnel": "从地道钻进了别人家",
		"ev.sep": "；",
		"sys.sabotage": "有人在{place}捣乱：{what}。存粮变少了。",
		"claim.elder_upyr": "自称长老：{who}是僵尸",
		"claim.elder_human": "自称长老：{who}是人",
		"claim.healer": "{role}：第{n}夜救活了{who}",
		"when.night": "第{n}夜",
		"when.day": "第{n}天",
		"chron.line": "{title}：{text}",
		"chron.morning": "早上：{text}",
		"log.exiled": "村子赶走了{who}。",
		"log.supplies": "存粮凑齐了{p}%。",
		"log.tunnel": "{who}没能进{from.of}，从地道钻到了{house.of}。",
		"log.street_upyr": "{who}没能进{house.of}，但活到了天亮。",
		"log.street_dead": "{who}没能进{house.of}。{who:早上有人在街上发现了他。|早上有人在街上发现了她。|你死在了街上。}",
		"log.street_ok": "{who}在外面过了一夜，活了下来。",
		"log.mimic_knock": "有人用{voice}的声音敲{house.of}的门。没人开。",
		"log.mimic_spared": "{house.of}放进了{voice}的声音。那不是{voice}，但大家都活到了天亮。",
		"log.mimic_kill": "{house.of}放进了{voice}的声音。是学舌鬼：它带走了{who}。",
		"log.alone_dead": "{who}独自待{house.in}。符灭了。",
		"log.killed": "{who}死{house.in}。旁边是：{others}。",
		"log.clean": "{list}{house.in}过夜，都平安。",
		"log.creature": "{house.of}的符碎了。林中怪物带走了{who}。",
		"log.liar": "{who}说要{said.to}，却睡{house.in}。",
		"log.talisman_cracked": "{house.of}的符裂了。",
		"log.talisman_broken": "{house.of}的符碎了。",
		"log.saved": "{who}{house.in}遭到袭击，但{healer}救活了{who:他|她|你}。",
		"log.meeting": "{who}敲响了钟：紧急集合。",
		"log.event": "{e}。",
		"sys.dawn1": "天亮了。大家都来到广场。",
		"sys.dawn": "第{d}天。还活着的：{n}人。",
		"job.water.title": "挑水",
		"job.water.place": "井边",
		"job.water.done": "水够用到天亮。",
		"job.wood.title": "劈柴",
		"job.wood.place": "柴堆旁",
		"job.wood.done": "柴够烧一整夜。",
		"job.lamp.title": "给灯加油",
		"job.lamp.place": "灯旁",
		"job.lamp.done": "灯都加满了。",
		"job.fish.title": "捕鱼",
		"job.fish.place": "河边",
		"job.fish.done": "晚饭有鱼了。",
		"job.talisman.title": "补符",
		"job.talisman.place": "符旁",
		"job.talisman.done": "符跟新的一样。",
		"job.box.title": "打开箱子",
		"job.box.place": "箱子旁",
		"role.elder": "长老",
		"role.elder.mid": "长老",
		"role.healer": "郎中",
		"role.healer.mid": "郎中",
		"role.headman": "村长",
		"role.headman.mid": "村长",
		"role.named": "{role}{who}",
		"event.fog.title": "大雾",
		"event.fog.mid": "大雾",
		"event.fog.text": "大雾盖住了钟声：跑的时间更少，外面更危险。",
		"event.moon.title": "满月",
		"event.moon.mid": "满月",
		"event.moon.text": "满月：到天亮所有的符都会变弱。",
		"event.quiet.title": "静夜",
		"event.quiet.mid": "静夜",
		"event.quiet.text": "静夜：外面更安全，学舌鬼不会来。",
		"event.rain.title": "暴雨",
		"event.rain.mid": "暴雨",
		"event.rain.text": "暴雨浇灭了灯：今晚存着的灯油用不上。",
		"recap.street_host": "你没能进{house.of}：守门的是{who}。",
		"recap.street": "你在外面过了一夜。在那儿几乎没人能活。",
		"recap.street_p": "那晚在外面死去的几率：{p}%。",
		"recap.killer": "杀死你的是{who}。{who:他|她}是僵尸。",
		"recap.you_opened": "是你自己给{who}开的门。",
		"recap.killer_opened": "是{who}亲自给你开的门。",
		"recap.near": "旁边是：{others}。",
		"recap.alone": "你独自待{house.in}。一个人撑不住符到天亮。",
		"recap.alone_p": "独自在那间屋里死去的几率：{p}%。白天找个人跟你一起。",
		"recap.creature": "{house.of}的符碎了，林中怪物进了屋。",
		"recap.creature_tip": "白天可以补符：这是广场上的一项活。",
		"recap.mimic_you": "你给{voice}的声音开了门。那是学舌鬼。",
		"recap.mimic_host": "{who}放进了{voice}的声音。那是学舌鬼。",
		"recap.voice_dead": "那时{voice}已经死了。",
		"recap.voice_away": "而{voice}那时{house.in}。",
		"recap.exiled": "你在第{d}天被赶走了。投你的有：{list}。",
		"recap.exiled_many": "你在第{d}天被赶走了。投你的：大多数人。",
		"recap.seen": "村里人看到：{ev}。",
		"recap.exiled0": "你被赶走了。",
		"recap.died": "你死在第{n}夜。{why}",
		"verdict.mimic": "第{n}夜，你给学舌鬼开了门，它学的是{voice}的声音。",
		"verdict.let_upyr": "第{n}夜，你放{who}进了门，而{who:他|她}是僵尸。",
		"verdict.vote_upyr": "第{n}天，你的一票帮着赶走了僵尸：{who}。",
		"verdict.vote_human": "第{n}天，你投了{who}，而{who:他|她}是人。",
		"verdict.clean": "你从没给僵尸开过门，活到了天亮。",
		"verdict.dead": "你没能活到天亮。",
		"verdict.kills": "你一共带走了：{n}人。",
		"verdict.upyr_won": "村里人到最后也没发现僵尸就是你。",
		"verdict.upyr_lost": "你活到了天亮，但村子撑住了。",
		"sys.box": "广场边上放着一只箱子。昨天还没有。",
		"sys.elder_upyr": "长老的画：{who}是僵尸。只有你知道。",
		"sys.elder_human": "长老的画：{who}是人。只有你知道。",
		"sys.bell_you": "你敲响了钟。紧急集合！",
		"sys.bell": "{who}敲响了钟。紧急集合！",
		"box.note": "箱子里有张纸条：“{a}或{b}”。其中一个是僵尸。只有你看得到纸条。",
		"box.oil": "箱子里有灯油：存粮+{n}。",
		"box.chalk": "箱子里有朱砂：{house.of}的符重画好了。",
		"box.empty": "箱子是空的。",
		"say.accuse": "我觉得是{who}。",
		"say.invite": "{who}，我们一起{house.to}吧？",
		"say.ask": "{who}，你今晚睡哪儿？",
		"say.defend": ["我不是僵尸。我发誓。", "我是自己人。今晚可以试试我。", "不是我。再找找。"],
		"toast.elder_upyr": "画上：{who}是僵尸",
		"toast.elder_human": "画上：{who}是人",
		"toast.box_taken": "箱子已经被人打开了",
		"toast.job_done": "“{job}”：今天已经做完了",
		"toast.box": "广场上出现了一只箱子",
		"toast.back_exit": "再按一次退出",
		"quit.ask": "放弃这局？",
		"quit.stay": "留下",
		"quit.leave": "回到菜单",
		"cfg.players": "玩家",
		"cfg.monsters": "僵尸",
		"cfg.shelters": "屋子",
		"cfg.capacity": "每间屋的位置",
		"cfg.nights": "撑到天亮的夜数",
		"cfg.day_seconds": "白天，秒",
		"cfg.door_seconds": "门口决定，秒",
		"cfg.run_seconds": "跑回屋，秒",
		"cfg.outside_death": "外面死亡率，%",
		"cfg.first_night_outside_death": "第一夜同上，%",
		"cfg.vote_from_day": "从第几天开始赶人",
		"diff.easy": "简单",
		"diff.normal": "普通",
		"diff.hard": "困难",
		"diff.custom": "自定义",
		"diff.cast": "{p}个村民，{u}个僵尸。",
		"diff.human": "你一定是人。",
		"diff.easy_note": "白天更长。",
		"diff.hard_note": "白天更短，外面更危险。",
		"diary.exiled": "第{n}天被赶走。",
		"diary.died": "死于第{n}夜。",
		"diary.night": "{n}：{where}",
		"diary.street": "外面",
		"diary.said": "（说过：{house}）",
		"diary.nights": "每夜：{list}。",
		"diary.today": "今天打算去：{house}。",
		"diary.evidence": "疑点：{ev}。",
		"diary.own_claim": "{text}。",
		"diary.claim": "{who}{text}。",
		"diary.seen_upyr": "你看的画：僵尸。",
		"diary.seen_human": "你看的画：人。",
		"diary.nothing": "还什么都不知道。",
		"diary.head": "日记：每个人的情况",
		"diary.gone": "{who} · 已死",
		"journal.who": "{who}：",
		"journal.head": "今日记录",
		"ui.close": "关闭",
		"ui.cancel": "取消",
		"say.placeholder": "或者自己写",
		"say.send": "说",
		"chip.exiled": " · 被赶走",
		"supplies": "存粮 {a}/{b}",
		"howto.art_accuse": "你就是僵尸！",
		"howto.art_street": "‹ 外面",
		"howto.art_door": "开门吗？",
		"game.title": "让我进去",
		"menu.tale": "夜里，外面没人活得下来。\n屋子比人少。\n\n有人站在门外求着进去。屋里的人来决定。",
		"menu.hint": "僵尸就在你们中间。他们彼此也不认识。",
		"menu.howto": "玩法",
		"menu.play": "开始",
		"lang.pick": "语言",
		"diff.note": "{d}：{text}",
		"diff.note_custom": "自定义难度：{text}",
		"settings.title": "设置",
		"settings.lang": "语言",
		"settings.sound": "声音",
		"settings.music": "音乐",
		"settings.sfx": "音效",
		"settings.ambience": "环境音",
		"settings.haptics_on": "振动：开",
		"settings.haptics_off": "振动：关",
		"settings.difficulty": "难度",
		"settings.hints": "重新显示提示",
		"settings.hints_reset": "提示会重新出现",
		"settings.note": "每个难度都用1500局测试过。最影响平衡的是屋子数和夜数。",
		"settings.start": "用这些设置开始",
		"ui.back": "返回",
		"howto.day.title": "白天",
		"howto.day.text": "村里住着人，人群中藏着僵尸。僵尸看起来和大家一样。你是提着灯笼的村民。\n\n白天大家都在广场上。点一个村民：指认他、邀他一起过夜，或者问他睡哪儿。头上的红眼睛表示村里人在怀疑他。\n\n点活计图标：水、柴、灯。存粮越多，夜里越亮。僵尸会装作干活，甚至毁掉做好的活。有时广场上会出现一只箱子：谁先打开，东西就归谁。",
		"howto.night.title": "夜晚",
		"howto.night.text": "傍晚钟声响起，大家都往屋里跑。钟响的时候，点一间屋子。屋子比人少：留在外面的人很难见到早晨。\n\n一个人待在屋里也危险。白天约好和谁一起过夜，再把裂了的符补好：符碎了的屋子，林中怪物会进去。",
		"howto.door.title": "门口",
		"howto.door.text": "谁先跑到屋子，谁决定放谁进来。\n\n放进僵尸，你就见不到早晨。谁都不放，你就只剩一个人。早上看看谁睡在哪儿、谁撒了谎。\n\n有时敲门的是一个人的声音，可那人正在别的屋里，或者早已死了。那是学舌鬼：别开门。\n\n有些人有身份：长老、郎中、村长。每局可以在白天敲一次钟，马上投票。关于每个人知道的一切，都在日记里。",
		"howto.title": "玩法 · {a}/{b}",
		"howto.got_it": "明白了",
		"ui.next": "下一步",
		"ui.skip": "跳过",
		"crash.title": "报告",
		"crash.head": "上次游戏意外关闭了",
		"crash.text": "这是游戏的错误，不是你的。点“复制报告”发给我们：从中能看出在哪一步出的问题。",
		"crash.steps": "最后几步：",
		"crash.copy": "复制报告",
		"crash.copied": "已复制：粘贴到聊天里",
		"ui.continue": "继续",
		"prologue.title": "第一夜之前",
		"prologue.pre": "你的身份……",
		"prologue.upyr": "你是僵尸",
		"prologue.human": "你是人",
		"prologue.upyr_text": "你不知道还有谁和你一样。外面吓不到你，和你关在同一扇门后的人活不到天亮。白天要像人一样说话。",
		"prologue.human_text": "夜里在外面，你几乎必死。屋里不能只有你一个人：符会灭。你需要一个伴，却不知道他们之中谁是人。",
		"prologue.facts": "{p}个村民，{u}个僵尸。{s}间屋子，每间{c}个位置。要撑到第{n}个天亮。",
		"prologue.go": "出去见大家",
		"prologue.elder": "你是长老。每局一次，白天点一个村民看画：就能知道他是不是僵尸。只有你知道。",
		"prologue.healer": "你是郎中。每局一次，入夜前带上草药：屋里你身边的人遭到袭击，你能救活他。",
		"prologue.headman": "你是村长。赶人投票时，你的一票算两票。",
		"end.title": "复盘",
		"end.people": "人们撑住了",
		"end.upyri": "村子空了",
		"end.won": "你这一方赢了。",
		"end.lost": "你这一方输了。",
		"end.who": "谁是谁",
		"end.upyr": "僵尸",
		"end.human": "人",
		"end.with_role": "{a}，{role}",
		"end.chip": "{who}：{what}",
		"end.how": "经过",
		"end.again": "再来一局",
		"end.verdict": "这局的关键",
		"end.offer_easier": "调简单一点？",
		"end.offer_harder": "连赢两局。试试更难的？",
		"end.easier": "调简单",
		"end.harder": "试试更难",
		"vote.title": "赶人",
		"vote.bell_you": "紧急集合：是你敲的钟。",
		"vote.bell": "紧急集合：{who}敲响了钟。",
		"vote.ask": "把谁赶出村子？被赶走的人永远不会回来。他是什么，最后才知道。",
		"day.diary": "日记",
		"vote.headman": "你是村长：你的一票算两票。",
		"vote.dead": "你已经死了，只能看着。",
		"vote.watch": "看结果",
		"vote.go": "赶走",
		"vote.none": "谁也没被赶走",
		"vote.gone": "{who}走了",
		"vote.gone_you": "你被赶走了",
		"vote.row": "{who}：{n}",
		"vote.night": "夜幕降临",
		"mo.title": "早晨",
		"mo.all_alive": "大家都活着",
		"mo.one_dead": "少了一个人",
		"mo.dead_n": "少了：{n}人",
		"mo.why": "你为什么死了",
		"mo.event": "这一夜：{e}。",
		"mo.street_dead": "{who}没能进{house.of}。{who:在街上被发现了。|在街上被发现了。|你死在了街上。}",
		"mo.alone_dead": "{who}独自待{house.in}。符灭了。",
		"mo.killed": "{who}死{house.in}。旁边是：{others}。",
		"mo.street_ok": "{who}在外面过了一夜。又回来了。",
		"mo.alone_ok": "{who}独自待{house.in}，平安无事。",
		"mo.clean": "{list}{house.in}过夜，都平安。",
		"mo.liar": "{who}说要{said.to}，却睡{house.in}。",
		"mo.creature": "{house.of}的符碎了。林中怪物带走了{who}。",
		"mo.talisman_cracked": "{house.of}的符裂了。白天可以补。",
		"mo.talisman_broken": "{house.of}的符碎了。白天可以补。",
		"mo.saved_upyr": "{house.in}，自己人里有谁袭击了{who}，但{healer}救活了{who:他|她|你}。",
		"mo.saved_creature": "{house.in}，林中怪物袭击了{who}，但{healer}救活了{who:他|她|你}。",
		"mo.saved_mimic": "{house.in}，学舌鬼袭击了{who}，但{healer}救活了{who:他|她|你}。",
		"mo.tunnel": "{who}没能进{from.of}，从地道钻到了{house.of}。",
		"mo.mimic_kill": "{house.of}放进了{voice}的声音。那不是{voice}：学舌鬼带走了{who}。",
		"mo.mimic_spared": "{house.of}放进了{voice}的声音。那不是{voice}，但大家都活到了天亮。",
		"mo.mimic_knock": "夜里有人用{voice}的声音敲{house.of}的门。没人开。那是学舌鬼。",
		"mo.mimic_knock_away": "夜里有人用{voice}的声音敲{house.of}的门。没人开。而{voice}那时{away.in}。",
		"list.sep": "、",
		"night.dusk": "天黑了。钟声响了。",
		"night.dead": "你已经不在了。夜晚照旧过去。",
		"night.bell": "钟响了！跑回屋：点一间屋子。",
		"night.going": "要去的：{list}",
		"night.pact": "和{who}约好了",
		"night.tunnel": "地道通往{house.of}",
		"night.tal_broken": "符碎了",
		"night.tal_cracked": "符裂了",
		"night.rule": "谁先跑到门口，谁就在屋里，决定放谁进来。钟响时没选屋子，你会最后一个跑去你说过的地方。",
		"night.heal": "带上草药：今晚救一个邻居",
		"night.hint": "钟声不会响太久。点广场上或列表里的一间屋子，然后跑。谁先到门口，谁决定放谁进来。",
		"night.heal_on": "草药带着：身边有人遇袭，你能救活他",
		"night.first": "你会第一个到：由你决定放谁进来。",
		"night.ahead": "比你先到门口的：{list}。由{who}决定。",
		"night.run": "你正跑{house.to}。{rest}",
		"door.title": "门口",
		"door.hint_host": "放你信得过的人进来。谁都不放，你就一个人，一个人活不下来。",
		"door.hint_guest": "选一句隔着门说的话。屋主记得你们有没有一起住过。",
		"door.hint_alone": "这里一个人活不下来。下次白天找个人跟你一起。",
		"door.host": "你第一个跑到了{house.of}。有人在敲门。",
		"door.cap": "可以放进来：{n}人",
		"door.quote": "“{text}”",
		"door.admit": "放进来",
		"door.admitting": "放他进来",
		"door.elsewhere": "在别的门口：{list}。",
		"door.upyr_note": "你放进来的人活不到天亮。",
		"door.alone_note": "谁都不放，你就一个人，符会灭。",
		"door.open": "开门",
		"door.refuse": "谁都不开",
		"door.locked": "{house.nom}已经从里面锁上了。里面是{who}。",
		"door.rivals": "和你一起在门口的：{list}。位置不够所有人。",
		"door.mimic": "你身后的黑暗里，有人用{voice}的声音说话。可{voice}不在这儿。",
		"door.say": "隔着门你要说什么？",
		"door.knock": "你敲响了{house.of}的门……",
		"door.let_in": "门闩一响。{who}放你进去了。",
		"door.shut": "脚步声离门而去。你被留在了外面。",
		"door.hatch": "屋后有个暗门。地道通往{house.of}，那里还有位置。钻过去就在屋里了，但早上大家都会知道你是从哪儿来的。",
		"door.tunnel": "钻地道{house.to}",
		"door.wait": "等天亮",
		"door.alone": "你第一个跑到了{house.of}。再没有别人来。",
		"door.alone_upyr": "落单的僵尸不怕外面。",
		"door.alone_human": "符在闪烁。一个人撑不到天亮。",
		"day.journal": "记录",
		"day.journal_n": "记录（{n}）",
		"day.dead": "你已经不在了。只能看着。",
		"day.skip": "跳过白天",
		"day.defend": "辩解",
		"day.invite": "邀请……",
		"day.accuse": "指认……",
		"day.say": "说……",
		"day.bell": "集合！",
		"day.ready": "准备过夜",
		"day.hint": "点一个村民：指认他、邀他同行，或者问他睡哪儿。点活计图标：存粮能在夜里点亮灯。",
		"day.bell_ask": "敲钟吗？大家会马上集合投票。每局只能一次。",
		"day.bell_do": "敲钟",
		"day.preview": "{who}：{text}",
		"day.say_aloud": "大声说",
		"day.person_ev": "{who} · {ev}",
		"day.p_accuse": "指认：“就是{who}”",
		"day.p_invite": "邀请一起过夜",
		"day.p_ask": "问睡哪儿",
		"day.p_elder": "看长老的画：{who:他|她}是什么？",
		"day.work": "干活：{job}",
		"day.spoil": "毁掉做好的活（{place}）",
		"day.who_accuse": "指认谁？",
		"day.who_invite": "邀请谁？",
		"day.where_with": "你和{who}去哪儿？",
	}
